# Reproduce Martin ------------------
## Train
#sbatch --time=12:00:00 --array=1-1%1 --job-name=pointrcnn-snow-wet-coupled-martin  tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_snow_wet_coupled_martin.yaml  --data_dir /home/nisarbar/projects/rrg-swasland/Datasets/Dense --infos_dir /home/nisarbar/projects/rrg-swasland/Datasets/Dense/Martin_Infos  --tcp_port 18880 --ckpt_save_interval 1 --fix_random_seed
#sbatch --time=12:00:00 --array=1-1%1 --job-name=pointrcnn-clear-martin  tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_clear_martin.yaml  --data_dir /home/nisarbar/projects/rrg-swasland/Datasets/Dense --infos_dir /home/nisarbar/projects/rrg-swasland/Datasets/Dense/Martin_Infos  --tcp_port 18881 --ckpt_save_interval 1 --fix_random_seed


## Test
# sbatch --time=03:00:00 --array=1-1%1 --job-name=pointrcnn-snow-wet-coupled-martin-test-clear  tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_snow_wet_coupled_martin.yaml  --data_dir /home/nisarbar/projects/rrg-swasland/Datasets/Dense --infos_dir /home/nisarbar/projects/rrg-swasland/Datasets/Dense/Martin_Infos  --tcp_port 18870 --fix_random_seed --test_only --eval_tag test_clear --test_info_pkl dense_infos_test_clear.pkl --test_data_split test_clear
# sbatch --time=03:00:00 --array=1-1%1 --job-name=pointrcnn-snow-wet-coupled-martin-test-snow-light  tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_snow_wet_coupled_martin.yaml  --data_dir /home/nisarbar/projects/rrg-swasland/Datasets/Dense --infos_dir /home/nisarbar/projects/rrg-swasland/Datasets/Dense/Martin_Infos  --tcp_port 18871 --fix_random_seed --test_only --eval_tag test_snow_light --test_info_pkl dense_infos_test_snow_light.pkl --test_data_split test_snow_light
# sbatch --time=03:00:00 --array=1-1%1 --job-name=pointrcnn-snow-wet-coupled-martin-test-snow-heavy  tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_snow_wet_coupled_martin.yaml  --data_dir /home/nisarbar/projects/rrg-swasland/Datasets/Dense --infos_dir /home/nisarbar/projects/rrg-swasland/Datasets/Dense/Martin_Infos  --tcp_port 18872 --fix_random_seed --test_only --eval_tag test_snow_heavy --test_info_pkl dense_infos_test_snow_heavy.pkl --test_data_split test_snow_heavy

# sbatch --time=03:00:00 --array=1-1%1 --job-name=pointrcnn-clear-martin-test-clear  tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_clear_martin.yaml  --data_dir /home/nisarbar/projects/rrg-swasland/Datasets/Dense --infos_dir /home/nisarbar/projects/rrg-swasland/Datasets/Dense/Martin_Infos  --tcp_port 18873 --fix_random_seed --test_only --eval_tag test_clear --test_info_pkl dense_infos_test_clear.pkl --test_data_split test_clear
# sbatch --time=03:00:00 --array=1-1%1 --job-name=pointrcnn-clear-martin-test-snow-light  tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_clear_martin.yaml  --data_dir /home/nisarbar/projects/rrg-swasland/Datasets/Dense --infos_dir /home/nisarbar/projects/rrg-swasland/Datasets/Dense/Martin_Infos  --tcp_port 18874 --fix_random_seed --test_only --eval_tag test_snow_light --test_info_pkl dense_infos_test_snow_light.pkl --test_data_split test_snow_light
# sbatch --time=03:00:00 --array=1-1%1 --job-name=pointrcnn-clear-martin-test-snow-heavy  tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_clear_martin.yaml  --data_dir /home/nisarbar/projects/rrg-swasland/Datasets/Dense --infos_dir /home/nisarbar/projects/rrg-swasland/Datasets/Dense/Martin_Infos  --tcp_port 18875 --fix_random_seed --test_only --eval_tag test_snow_heavy --test_info_pkl dense_infos_test_snow_heavy.pkl --test_data_split test_snow_heavy

# sbatch --time=03:00:00 --array=1-1%1 --job-name=pointrcnn-snow-wet-coupled-martin-test-light-fog  tools/scripts/compute_canada_train_eval_dense.sh --sing_img /home/nisarbar/projects/rrg-swasland/singularity/openpcdet_martin.sif --cfg_file tools/cfgs/dense_models/pointrcnn_train_clear_FOV3000_60_snow.yaml    --tcp_port 18882 --fix_random_seed --test_only --eval_tag test_light_fog_FOV3000 --test_info_pkl dense_infos_test_light_fog_FOV3000_25.pkl --test_data_split test_light_fog_FOV3000_25
# sbatch --time=03:00:00 --array=1-1%1 --job-name=pointrcnn-snow-wet-coupled-martin-test-dense-fog  tools/scripts/compute_canada_train_eval_dense.sh --sing_img /home/nisarbar/projects/rrg-swasland/singularity/openpcdet_martin.sif --cfg_file tools/cfgs/dense_models/pointrcnn_train_clear_FOV3000_60_snow.yaml    --tcp_port 18883 --fix_random_seed --test_only --eval_tag test_dense_fog_FOV3000 --test_info_pkl dense_infos_test_dense_fog_FOV3000_25.pkl --test_data_split test_dense_fog_FOV3000_25
# sbatch --time=03:00:00 --array=1-1%1 --job-name=pointrcnn-snow-wet-coupled-martin-test-all  tools/scripts/compute_canada_train_eval_dense.sh --sing_img /home/nisarbar/projects/rrg-swasland/singularity/openpcdet_martin.sif --cfg_file tools/cfgs/dense_models/pointrcnn_train_clear_FOV3000_60_snow.yaml    --tcp_port 18884 --fix_random_seed --test_only --eval_tag test_all_FOV3000 --test_info_pkl dense_infos_test_all_FOV3000_25.pkl --test_data_split test_all_FOV3000_25
# Reproduce Martin ------------------