
#!/bin/bash

TRY=0
KITTI_EPOCH_1=5
KITTI_EPOCH_2=80
WAYMO_EPOCH_1=5
WAYMO_EPOCH_2=80

# Get command line arguments
while :; do
    case $1 in
    -t|--try)       # Takes an option argument; ensure it has been specified.
        if [ "$2" ]; then
            TRY=$2
            shift
        else
            die 'ERROR: "--num_epochs_1" requires a non-empty option argument.'
        fi
        ;;
    -?*)
        printf 'WARN: Unknown option (ignored): %s\n' "$1" >&2
        ;;
    *)               # Default case: No more options, so break out of the loop.
        break
    esac

    shift
done

#Kitti
#TODO fix kitti eval division by zero in iou
#5 percent
TRY=0
# sbatch --time=8:00:00 --array=1-6%1 --job-name=kitti_scratch_bs2_"$KITTI_EPOCH_2"ep_5percent_$TRY tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_minkunet_0p05_$TRY.yaml --mode scratch --tcp_port 16920 --extra_tag scratch_bs2 --num_epochs_1 $KITTI_EPOCH_2 --test_start_epoch 55 --wandb_run_name scratch_minkunet_pointrcnn --wandb_group ep"$KITTI_EPOCH_2"_bs2_try$TRY --batch_size_per_gpu 2
sbatch --time=8:00:00 --array=1-3%1 --job-name=kitti_seg_bs2_"$KITTI_EPOCH_1"ep_"$KITTI_EPOCH_2"ep_5percent_$TRY tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_minkunet_0p05_$TRY.yaml --tcp_port 16921 --extra_tag segcontrast_bs2 --pretrained_model_1 /OpenPCDet/checkpoints/seg_ep199.pth.tar --num_epochs_1 $KITTI_EPOCH_1 --pretrained_model_2 /OpenPCDet/output/kitti_models/pointrcnn_minkunet_0p05_$TRY/segcontrast_bs2_ep"$KITTI_EPOCH_1"_frozen_bb/ckpt/checkpoint_epoch_$KITTI_EPOCH_1.pth --num_epochs_2 $KITTI_EPOCH_2 --test_start_epoch 55 --wandb_run_name segcontrast_10perc_waymo_minkunet --wandb_group ep"$KITTI_EPOCH_1"_ep"$KITTI_EPOCH_2"_bs2_try$TRY --batch_size_per_gpu 2
# sbatch --time=8:00:00 --array=1-6%1 --job-name=kitti_seglidarplusdet_bs2_"$KITTI_EPOCH_1"ep_"$KITTI_EPOCH_2"ep_5percent_$TRY tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_minkunet_0p05_$TRY.yaml --tcp_port 16922 --extra_tag segcontrast_lidarplusdet_bs2 --pretrained_model_1 /OpenPCDet/checkpoints/seg_lidar_plus_det_ep199_t2.pth.tar --num_epochs_1 $KITTI_EPOCH_1 --pretrained_model_2 /OpenPCDet/output/kitti_models/pointrcnn_minkunet_0p05_$TRY/segcontrast_lidarplusdet_bs2_ep"$KITTI_EPOCH_1"_frozen_bb/ckpt/checkpoint_epoch_$KITTI_EPOCH_1.pth --num_epochs_2 $KITTI_EPOCH_2 --test_start_epoch 55 --wandb_run_name segcontrast_lidarplusdet_10perc_waymo_minkunet --wandb_group ep"$KITTI_EPOCH_1"_ep"$KITTI_EPOCH_2"_bs2_try$TRY --batch_size_per_gpu 2

TRY=1
sbatch --time=8:00:00 --array=1-3%1 --job-name=kitti_scratch_bs2_"$KITTI_EPOCH_2"ep_5percent_$TRY tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_minkunet_0p05_$TRY.yaml --mode scratch --tcp_port 16923 --extra_tag scratch_bs2 --num_epochs_1 $KITTI_EPOCH_2 --test_start_epoch 55 --wandb_run_name scratch_minkunet_pointrcnn --wandb_group ep"$KITTI_EPOCH_2"_bs2_try$TRY --batch_size_per_gpu 2
sbatch --time=8:00:00 --array=1-3%1 --job-name=kitti_seg_bs2_"$KITTI_EPOCH_1"ep_"$KITTI_EPOCH_2"ep_5percent_$TRY tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_minkunet_0p05_$TRY.yaml --tcp_port 16924 --extra_tag segcontrast_bs2 --pretrained_model_1 /OpenPCDet/checkpoints/seg_ep199.pth.tar --num_epochs_1 $KITTI_EPOCH_1 --pretrained_model_2 /OpenPCDet/output/kitti_models/pointrcnn_minkunet_0p05_$TRY/segcontrast_bs2_ep"$KITTI_EPOCH_1"_frozen_bb/ckpt/checkpoint_epoch_$KITTI_EPOCH_1.pth --num_epochs_2 $KITTI_EPOCH_2 --test_start_epoch 55 --wandb_run_name segcontrast_10perc_waymo_minkunet --wandb_group ep"$KITTI_EPOCH_1"_ep"$KITTI_EPOCH_2"_bs2_try$TRY --batch_size_per_gpu 2
#sbatch --time=8:00:00 --array=1-6%1 --job-name=kitti_seglidarplusdet_bs2_"$KITTI_EPOCH_1"ep_"$KITTI_EPOCH_2"ep_5percent_$TRY tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_minkunet_0p05_$TRY.yaml --tcp_port 16925 --extra_tag segcontrast_lidarplusdet_bs2 --pretrained_model_1 /OpenPCDet/checkpoints/seg_lidar_plus_det_ep199_t2.pth.tar --num_epochs_1 $KITTI_EPOCH_1 --pretrained_model_2 /OpenPCDet/output/kitti_models/pointrcnn_minkunet_0p05_$TRY/segcontrast_lidarplusdet_bs2_ep"$KITTI_EPOCH_1"_frozen_bb/ckpt/checkpoint_epoch_$KITTI_EPOCH_1.pth --num_epochs_2 $KITTI_EPOCH_2 --test_start_epoch 55 --wandb_run_name segcontrast_lidarplusdet_10perc_waymo_minkunet --wandb_group ep"$KITTI_EPOCH_1"_ep"$KITTI_EPOCH_2"_bs2_try$TRY --batch_size_per_gpu 2

# TRY=2
# sbatch --time=8:00:00 --array=1-6%1 --job-name=kitti_scratch_bs2_"$KITTI_EPOCH_2"ep_5percent_$TRY tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_minkunet_0p05_$TRY.yaml --mode scratch --tcp_port 16926 --extra_tag scratch_bs2 --num_epochs_1 $KITTI_EPOCH_2 --test_start_epoch 55 --wandb_run_name scratch_minkunet_pointrcnn --wandb_group ep"$KITTI_EPOCH_2"_bs2_try$TRY --batch_size_per_gpu 2
# sbatch --time=8:00:00 --array=1-6%1 --job-name=kitti_seg_bs2_"$KITTI_EPOCH_1"ep_"$KITTI_EPOCH_2"ep_5percent_$TRY tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_minkunet_0p05_$TRY.yaml --tcp_port 16927 --extra_tag segcontrast_bs2 --pretrained_model_1 /OpenPCDet/checkpoints/seg_ep199.pth.tar --num_epochs_1 $KITTI_EPOCH_1 --pretrained_model_2 /OpenPCDet/output/kitti_models/pointrcnn_minkunet_0p05_$TRY/segcontrast_bs2_ep"$KITTI_EPOCH_1"_frozen_bb/ckpt/checkpoint_epoch_$KITTI_EPOCH_1.pth --num_epochs_2 $KITTI_EPOCH_2 --test_start_epoch 55 --wandb_run_name segcontrast_10perc_waymo_minkunet --wandb_group ep"$KITTI_EPOCH_1"_ep"$KITTI_EPOCH_2"_bs2_try$TRY --batch_size_per_gpu 2
# sbatch --time=8:00:00 --array=1-6%1 --job-name=kitti_seglidarplusdet_bs2_"$KITTI_EPOCH_1"ep_"$KITTI_EPOCH_2"ep_5percent_$TRY tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_minkunet_0p05_$TRY.yaml --tcp_port 16928 --extra_tag segcontrast_lidarplusdet_bs2 --pretrained_model_1 /OpenPCDet/checkpoints/seg_lidar_plus_det_ep199_t2.pth.tar --num_epochs_1 $KITTI_EPOCH_1 --pretrained_model_2 /OpenPCDet/output/kitti_models/pointrcnn_minkunet_0p05_$TRY/segcontrast_lidarplusdet_bs2_ep"$KITTI_EPOCH_1"_frozen_bb/ckpt/checkpoint_epoch_$KITTI_EPOCH_1.pth --num_epochs_2 $KITTI_EPOCH_2 --test_start_epoch 55 --wandb_run_name segcontrast_lidarplusdet_10perc_waymo_minkunet --wandb_group ep"$KITTI_EPOCH_1"_ep"$KITTI_EPOCH_2"_bs2_try$TRY --batch_size_per_gpu 2


#sbatch --time=8:00:00 --array=1-1%1 --job-name=kitti_segonlydet_"$KITTI_EPOCH_1"ep_"$KITTI_EPOCH_2"ep_5percent_$TRY tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_minkunet_0p05_$TRY.yaml --tcp_port 16924 --extra_tag segcontrast_onlydet --pretrained_model_1 /OpenPCDet/checkpoints/seg_only_det_ep199_t2.pth.tar --num_epochs_1 $KITTI_EPOCH_1 --pretrained_model_2 /OpenPCDet/output/kitti_models/pointrcnn_minkunet_0p05_$TRY/segcontrast_onlydet_ep"$KITTI_EPOCH_1"_frozen_bb/ckpt/checkpoint_epoch_$KITTI_EPOCH_1.pth --num_epochs_2 $KITTI_EPOCH_2 --test_start_epoch 55 --wandb_run_name segcontrast_det_10perc_waymo_minkunet --wandb_group ep"$KITTI_EPOCH_1"_ep"$KITTI_EPOCH_2"_try$TRY

# sbatch --time=8:00:00 --array=1-1%1 --job-name=kitti_seglidarplusdet_lnbt_"$KITTI_EPOCH_1"ep_"$KITTI_EPOCH_2"ep_5percent_$TRY tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_minkunet_0p05_$TRY.yaml --tcp_port 16923 --extra_tag segcontrast_lidarplusdet_lnbt --pretrained_model_1 /OpenPCDet/checkpoints/seg_lidar_plus_det_ep199_t2.pth.tar --num_epochs_1 $KITTI_EPOCH_1 --pretrained_model_2 /OpenPCDet/output/kitti_models/pointrcnn_minkunet_0p05_$TRY/segcontrast_lidarplusdet_lnbt_ep"$KITTI_EPOCH_1"_frozen_bb/ckpt/checkpoint_epoch_$KITTI_EPOCH_1.pth --num_epochs_2 $KITTI_EPOCH_2 --test_start_epoch 55 --wandb_run_name segcontrast_lidarplusdet_10perc_waymo_minkunet --wandb_group ep"$KITTI_EPOCH_1"_ep"$KITTI_EPOCH_2"_try"$TRY"_lnbt --load_num_batches_tracked


#Waymo
#1 percent
# which is better without or with batches tracked? and run more tries of that
# sbatch --time=8:00:00 --array=1-3%1 --job-name=waymo_scratch_"$WAYMO_EPOCH_2"ep_try$TRY tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --mode scratch --tcp_port 16929 --extra_tag scratch_t$TRY --num_epochs_1 $WAYMO_EPOCH_2 --test_start_epoch 0 --test_sample_interval 20 --eval_tag val_5perc --wandb_run_name scratch_minkunet_pointrcnn --wandb_group ep"$WAYMO_EPOCH_2"_try$TRY

# sbatch --time=8:00:00 --array=1-3%1 --job-name=waymo_seg_"$WAYMO_EPOCH_1"ep_"$WAYMO_EPOCH_2"ep_try$TRY tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --tcp_port 16930 --extra_tag segcontrast_t$TRY --pretrained_model_1 /OpenPCDet/checkpoints/seg_ep199.pth.tar --num_epochs_1 $WAYMO_EPOCH_1 --pretrained_model_2 /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class/segcontrast_t"$TRY"_ep"$WAYMO_EPOCH_1"_frozen_bb/ckpt/checkpoint_epoch_$WAYMO_EPOCH_1.pth --num_epochs_2 $WAYMO_EPOCH_2 --test_start_epoch 0 --test_sample_interval 20 --eval_tag val_5perc --wandb_run_name segcontrast_10perc_waymo_minkunet --wandb_group ep"$WAYMO_EPOCH_1"_ep"$WAYMO_EPOCH_2"_try$TRY

# sbatch --time=8:00:00 --array=1-3%1 --job-name=waymo_seglidarplusdet_"$WAYMO_EPOCH_1"ep_"$WAYMO_EPOCH_2"ep_try$TRY tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --tcp_port 16931 --extra_tag segcontrast_lidarplusdet_t$TRY --pretrained_model_1 /OpenPCDet/checkpoints/seg_lidar_plus_det_ep199_t2.pth.tar --num_epochs_1 $WAYMO_EPOCH_1 --pretrained_model_2 /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class/segcontrast_lidarplusdet_t"$TRY"_ep"$WAYMO_EPOCH_1"_frozen_bb/ckpt/checkpoint_epoch_$WAYMO_EPOCH_1.pth --num_epochs_2 $WAYMO_EPOCH_2 --test_start_epoch 0 --test_sample_interval 20 --eval_tag val_5perc --wandb_run_name segcontrast_lidarplusdet_10perc_waymo_minkunet --wandb_group ep"$WAYMO_EPOCH_1"_ep"$WAYMO_EPOCH_2"_try$TRY

# sbatch --time=8:00:00 --array=1-3%1 --job-name=waymo_segonlydet_"$WAYMO_EPOCH_1"ep_"$WAYMO_EPOCH_2"ep_try$TRY tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --tcp_port 16932 --extra_tag segcontrast_onlydet_t$TRY --pretrained_model_1 /OpenPCDet/checkpoints/seg_only_det_ep199_t2.pth.tar --num_epochs_1 $WAYMO_EPOCH_1 --pretrained_model_2 /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class/segcontrast_onlydet_t"$TRY"_ep"$WAYMO_EPOCH_1"_frozen_bb/ckpt/checkpoint_epoch_$WAYMO_EPOCH_1.pth --num_epochs_2 $WAYMO_EPOCH_2 --test_start_epoch 0 --test_sample_interval 20 --eval_tag val_5perc --wandb_run_name segcontrast_det_10perc_waymo_minkunet --wandb_group ep"$WAYMO_EPOCH_1"_ep"$WAYMO_EPOCH_2"_try$TRY 

# sbatch --time=8:00:00 --array=1-3%1 --job-name=waymo_seglidarplusdet_lnbt_"$WAYMO_EPOCH_1"ep_"$WAYMO_EPOCH_2"ep_try$TRY tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --tcp_port 16933 --extra_tag segcontrast_lidarplusdet_lnbt_t$TRY --pretrained_model_1 /OpenPCDet/checkpoints/seg_lidar_plus_det_ep199_t2.pth.tar --num_epochs_1 $WAYMO_EPOCH_1 --pretrained_model_2 /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class/segcontrast_lidarplusdet_lnbt_t"$TRY"_ep"$WAYMO_EPOCH_1"_frozen_bb/ckpt/checkpoint_epoch_$WAYMO_EPOCH_1.pth --num_epochs_2 $WAYMO_EPOCH_2 --test_start_epoch 0 --test_sample_interval 20 --eval_tag val_5perc --wandb_run_name segcontrast_lidarplusdet_10perc_waymo_minkunet --wandb_group ep"$WAYMO_EPOCH_1"_ep"$WAYMO_EPOCH_2"_try"$TRY"_lnbt --load_num_batches_tracked

# sbatch --time=8:00:00 --array=1-3%1 --job-name=waymo_seglidar_"$WAYMO_EPOCH_1"ep_"$WAYMO_EPOCH_2"ep_try$TRY tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --tcp_port 16931 --extra_tag segcontrast_lidar_t$TRY --pretrained_model_1 /OpenPCDet/checkpoints/seg_lidar_ep199.pth.tar --num_epochs_1 $WAYMO_EPOCH_1 --pretrained_model_2 /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class/segcontrast_lidar_t"$TRY"_ep"$WAYMO_EPOCH_1"_frozen_bb/ckpt/checkpoint_epoch_$WAYMO_EPOCH_1.pth --num_epochs_2 $WAYMO_EPOCH_2 --test_start_epoch 0 --test_sample_interval 20 --eval_tag val_5perc --wandb_run_name segcontrast_lidaraug_single_randh_10perc_waymo_minkunet --wandb_group ep"$WAYMO_EPOCH_1"_ep"$WAYMO_EPOCH_2"_try$TRY
# TRY=1
# sbatch --time=8:00:00 --array=1-3%1 --job-name=waymo_seglidar_"$WAYMO_EPOCH_1"ep_"$WAYMO_EPOCH_2"ep_try$TRY tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --tcp_port 16931 --extra_tag segcontrast_lidar_t$TRY --pretrained_model_1 /OpenPCDet/checkpoints/seg_lidar_ep199.pth.tar --num_epochs_1 $WAYMO_EPOCH_1 --pretrained_model_2 /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class/segcontrast_lidar_t"$TRY"_ep"$WAYMO_EPOCH_1"_frozen_bb/ckpt/checkpoint_epoch_$WAYMO_EPOCH_1.pth --num_epochs_2 $WAYMO_EPOCH_2 --test_start_epoch 0 --test_sample_interval 20 --eval_tag val_5perc --wandb_run_name segcontrast_lidaraug_single_randh_10perc_waymo_minkunet --wandb_group ep"$WAYMO_EPOCH_1"_ep"$WAYMO_EPOCH_2"_try$TRY
# TRY=2
# sbatch --time=8:00:00 --array=1-3%1 --job-name=waymo_seglidar_"$WAYMO_EPOCH_1"ep_"$WAYMO_EPOCH_2"ep_try$TRY tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --tcp_port 16931 --extra_tag segcontrast_lidar_t$TRY --pretrained_model_1 /OpenPCDet/checkpoints/seg_lidar_ep199.pth.tar --num_epochs_1 $WAYMO_EPOCH_1 --pretrained_model_2 /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class/segcontrast_lidar_t"$TRY"_ep"$WAYMO_EPOCH_1"_frozen_bb/ckpt/checkpoint_epoch_$WAYMO_EPOCH_1.pth --num_epochs_2 $WAYMO_EPOCH_2 --test_start_epoch 0 --test_sample_interval 20 --eval_tag val_5perc --wandb_run_name segcontrast_lidaraug_single_randh_10perc_waymo_minkunet --wandb_group ep"$WAYMO_EPOCH_1"_ep"$WAYMO_EPOCH_2"_try$TRY


# KITTI 100 percent
TRY=0
sbatch --time=8:00:00 --array=1-8%1 --job-name=kitti_scratch_bs2_"$KITTI_EPOCH_2"ep_100percent_try$TRY tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_minkunet.yaml --mode scratch --tcp_port 16929 --extra_tag scratch_bs2_t$TRY --num_epochs_1 $KITTI_EPOCH_2 --test_start_epoch 0 --wandb_run_name scratch_minkunet_pointrcnn --wandb_group ep"$KITTI_EPOCH_2"_bs2_try$TRY --batch_size_per_gpu 2
sbatch --time=8:00:00 --array=1-8%1 --job-name=kitti_seg_bs2_"$KITTI_EPOCH_1"ep_"$KITTI_EPOCH_2"ep_100percent_try$TRY tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_minkunet.yaml --tcp_port 16930 --extra_tag segcontrast_bs2_t$TRY --pretrained_model_1 /OpenPCDet/checkpoints/seg_ep199.pth.tar --num_epochs_1 $KITTI_EPOCH_1 --pretrained_model_2 /OpenPCDet/output/kitti_models/pointrcnn_minkunet/segcontrast_bs2_t"$TRY"_ep"$KITTI_EPOCH_1"_frozen_bb/ckpt/checkpoint_epoch_$KITTI_EPOCH_1.pth --num_epochs_2 $KITTI_EPOCH_2 --test_start_epoch 0 --wandb_run_name segcontrast_10perc_waymo_minkunet --wandb_group ep"$KITTI_EPOCH_1"_ep"$KITTI_EPOCH_2"_bs2_try$TRY --batch_size_per_gpu 2
sbatch --time=8:00:00 --array=1-8%1 --job-name=kitti_seglidarplusdet_bs2_"$KITTI_EPOCH_1"ep_"$KITTI_EPOCH_2"ep_100percent_try$TRY tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_minkunet.yaml --tcp_port 16931 --extra_tag segcontrast_lidarplusdet_bs2_t$TRY --pretrained_model_1 /OpenPCDet/checkpoints/seg_lidar_plus_det_ep199_t2.pth.tar --num_epochs_1 $KITTI_EPOCH_1 --pretrained_model_2 /OpenPCDet/output/kitti_models/pointrcnn_minkunet/segcontrast_lidarplusdet_bs2_t"$TRY"_ep"$KITTI_EPOCH_1"_frozen_bb/ckpt/checkpoint_epoch_$KITTI_EPOCH_1.pth --num_epochs_2 $KITTI_EPOCH_2 --test_start_epoch 0 --wandb_run_name segcontrast_lidarplusdet_10perc_waymo_minkunet --wandb_group ep"$KITTI_EPOCH_1"_ep"$KITTI_EPOCH_2"_bs2_try$TRY --batch_size_per_gpu 2
# TRY=1
# sbatch --time=8:00:00 --array=1-8%1 --job-name=kitti_scratch_bs2_"$KITTI_EPOCH_2"ep_100percent_try$TRY tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_minkunet.yaml --mode scratch --tcp_port 16932 --extra_tag scratch_bs2_t$TRY --num_epochs_1 $KITTI_EPOCH_2 --test_start_epoch 0 --wandb_run_name scratch_minkunet_pointrcnn --wandb_group ep"$KITTI_EPOCH_2"_bs2_try$TRY --batch_size_per_gpu 2
# sbatch --time=8:00:00 --array=1-8%1 --job-name=kitti_seg_bs2_"$KITTI_EPOCH_1"ep_"$KITTI_EPOCH_2"ep_100percent_try$TRY tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_minkunet.yaml --tcp_port 16933 --extra_tag segcontrast_bs2_t$TRY --pretrained_model_1 /OpenPCDet/checkpoints/seg_ep199.pth.tar --num_epochs_1 $KITTI_EPOCH_1 --pretrained_model_2 /OpenPCDet/output/kitti_models/pointrcnn_minkunet/segcontrast_bs2_t"$TRY"_ep"$KITTI_EPOCH_1"_frozen_bb/ckpt/checkpoint_epoch_$KITTI_EPOCH_1.pth --num_epochs_2 $KITTI_EPOCH_2 --test_start_epoch 0 --wandb_run_name segcontrast_10perc_waymo_minkunet --wandb_group ep"$KITTI_EPOCH_1"_ep"$KITTI_EPOCH_2"_bs2_try$TRY --batch_size_per_gpu 2
# sbatch --time=8:00:00 --array=1-8%1 --job-name=kitti_seglidarplusdet_bs2_"$KITTI_EPOCH_1"ep_"$KITTI_EPOCH_2"ep_100percent_try$TRY tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_minkunet.yaml --tcp_port 16934 --extra_tag segcontrast_lidarplusdet_bs2_t$TRY --pretrained_model_1 /OpenPCDet/checkpoints/seg_lidar_plus_det_ep199_t2.pth.tar --num_epochs_1 $KITTI_EPOCH_1 --pretrained_model_2 /OpenPCDet/output/kitti_models/pointrcnn_minkunet/segcontrast_lidarplusdet_bs2_t"$TRY"_ep"$KITTI_EPOCH_1"_frozen_bb/ckpt/checkpoint_epoch_$KITTI_EPOCH_1.pth --num_epochs_2 $KITTI_EPOCH_2 --test_start_epoch 0 --wandb_run_name segcontrast_lidarplusdet_10perc_waymo_minkunet --wandb_group ep"$KITTI_EPOCH_1"_ep"$KITTI_EPOCH_2"_bs2_try$TRY --batch_size_per_gpu 2
# TRY=2
# sbatch --time=8:00:00 --array=1-8%1 --job-name=kitti_scratch_bs2_"$KITTI_EPOCH_2"ep_100percent_try$TRY tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_minkunet.yaml --mode scratch --tcp_port 16935 --extra_tag scratch_bs2_t$TRY --num_epochs_1 $KITTI_EPOCH_2 --test_start_epoch 0 --wandb_run_name scratch_minkunet_pointrcnn --wandb_group ep"$KITTI_EPOCH_2"_bs2_try$TRY --batch_size_per_gpu 2
# sbatch --time=8:00:00 --array=1-8%1 --job-name=kitti_seg_bs2_"$KITTI_EPOCH_1"ep_"$KITTI_EPOCH_2"ep_100percent_try$TRY tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_minkunet.yaml --tcp_port 16936 --extra_tag segcontrast_bs2_t$TRY --pretrained_model_1 /OpenPCDet/checkpoints/seg_ep199.pth.tar --num_epochs_1 $KITTI_EPOCH_1 --pretrained_model_2 /OpenPCDet/output/kitti_models/pointrcnn_minkunet/segcontrast_bs2_t"$TRY"_ep"$KITTI_EPOCH_1"_frozen_bb/ckpt/checkpoint_epoch_$KITTI_EPOCH_1.pth --num_epochs_2 $KITTI_EPOCH_2 --test_start_epoch 0 --wandb_run_name segcontrast_10perc_waymo_minkunet --wandb_group ep"$KITTI_EPOCH_1"_ep"$KITTI_EPOCH_2"_bs2_try$TRY --batch_size_per_gpu 2
# sbatch --time=8:00:00 --array=1-8%1 --job-name=kitti_seglidarplusdet_bs2_"$KITTI_EPOCH_1"ep_"$KITTI_EPOCH_2"ep_100percent_try$TRY tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_minkunet.yaml --tcp_port 16937 --extra_tag segcontrast_lidarplusdet_bs2_t$TRY --pretrained_model_1 /OpenPCDet/checkpoints/seg_lidar_plus_det_ep199_t2.pth.tar --num_epochs_1 $KITTI_EPOCH_1 --pretrained_model_2 /OpenPCDet/output/kitti_models/pointrcnn_minkunet/segcontrast_lidarplusdet_bs2_t"$TRY"_ep"$KITTI_EPOCH_1"_frozen_bb/ckpt/checkpoint_epoch_$KITTI_EPOCH_1.pth --num_epochs_2 $KITTI_EPOCH_2 --test_start_epoch 0 --wandb_run_name segcontrast_lidarplusdet_10perc_waymo_minkunet --wandb_group ep"$KITTI_EPOCH_1"_ep"$KITTI_EPOCH_2"_bs2_try$TRY --batch_size_per_gpu 2

# sbatch --time=8:00:00 --array=1-2%1 --job-name=kitti_segonlydet_"$KITTI_EPOCH_1"ep_"$KITTI_EPOCH_2"ep_100percent_try$TRY tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_minkunet.yaml --tcp_port 16928 --extra_tag segcontrast_onlydet_t$TRY --pretrained_model_1 /OpenPCDet/checkpoints/seg_only_det_ep199_t2.pth.tar --num_epochs_1 $KITTI_EPOCH_1 --pretrained_model_2 /OpenPCDet/output/kitti_models/pointrcnn_minkunet/segcontrast_onlydet_t"$TRY"_ep"$KITTI_EPOCH_1"_frozen_bb/ckpt/checkpoint_epoch_$KITTI_EPOCH_1.pth --num_epochs_2 $KITTI_EPOCH_2 --test_start_epoch 0 --wandb_run_name segcontrast_det_10perc_waymo_minkunet --wandb_group ep"$KITTI_EPOCH_1"_ep"$KITTI_EPOCH_2"_try$TRY



# # Eval Waymo on 100% by each ckpt
# TRY=0
# WAYMO_EPOCH_2=80
# sbatch --time=6:00:00 --array=1-1%1 --job-name=waymo_scratch_"$WAYMO_EPOCH_2"ep_try"$TRY"_eval tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --mode test_only --tcp_port 16929 --extra_tag scratch_t$TRY --num_epochs_1 $WAYMO_EPOCH_2 --test_sample_interval 2 --eval_tag val_50perc  --ckpt_dir /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class/scratch_t"$TRY"_ep"$WAYMO_EPOCH_2"/ckpt --ckpt_to_eval 53,24 #80,53,24
# sbatch --time=6:00:00 --array=1-1%1 --job-name=waymo_seg_"$WAYMO_EPOCH_1"ep_"$WAYMO_EPOCH_2"ep_try"$TRY"_eval tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --mode test_only  --tcp_port 16930 --extra_tag segcontrast_t$TRY --num_epochs_1 $WAYMO_EPOCH_1 --num_epochs_2 $WAYMO_EPOCH_2 --test_sample_interval 2 --eval_tag val_50perc  --ckpt_dir /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class/segcontrast_t"$TRY"_ep"$WAYMO_EPOCH_1"_ep"$WAYMO_EPOCH_2"/ckpt --ckpt_to_eval 57,55
# sbatch --time=7:00:00 --array=1-1%1 --job-name=waymo_seglidarplusdet_"$WAYMO_EPOCH_1"ep_"$WAYMO_EPOCH_2"ep_try"$TRY"_eval tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --mode test_only  --tcp_port 16931 --extra_tag segcontrast_lidarplusdet_t$TRY --num_epochs_1 $WAYMO_EPOCH_1 --num_epochs_2 $WAYMO_EPOCH_2 --test_sample_interval 2 --eval_tag val_50perc  --ckpt_dir /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class/segcontrast_lidarplusdet_t"$TRY"_ep"$WAYMO_EPOCH_1"_ep"$WAYMO_EPOCH_2"/ckpt --ckpt_to_eval 60,63,39
# sbatch --time=7:00:00 --array=1-1%1 --job-name=waymo_segonlydet_"$WAYMO_EPOCH_1"ep_"$WAYMO_EPOCH_2"ep_try"$TRY"_eval tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --mode test_only  --tcp_port 16932 --extra_tag segcontrast_onlydet_t$TRY --num_epochs_1 $WAYMO_EPOCH_1 --num_epochs_2 $WAYMO_EPOCH_2 --test_sample_interval 2 --eval_tag val_50perc  --ckpt_dir /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class/segcontrast_onlydet_t"$TRY"_ep"$WAYMO_EPOCH_1"_ep"$WAYMO_EPOCH_2"/ckpt --ckpt_to_eval 61,57,48

# TRY=1
# sbatch --time=7:00:00 --array=1-1%1 --job-name=waymo_scratch_"$WAYMO_EPOCH_2"ep_try"$TRY"_eval tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --mode test_only --tcp_port 16933 --extra_tag scratch_t$TRY --num_epochs_1 $WAYMO_EPOCH_2 --test_sample_interval 2 --eval_tag val_50perc  --ckpt_dir /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class/scratch_t"$TRY"_ep"$WAYMO_EPOCH_2"/ckpt --ckpt_to_eval 56,29,53
# sbatch --time=7:00:00 --array=1-1%1 --job-name=waymo_seg_"$WAYMO_EPOCH_1"ep_"$WAYMO_EPOCH_2"ep_try"$TRY"_eval tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --mode test_only --tcp_port 16934 --extra_tag segcontrast_t$TRY --num_epochs_1 $WAYMO_EPOCH_1 --num_epochs_2 $WAYMO_EPOCH_2 --test_sample_interval 2 --eval_tag val_50perc  --ckpt_dir /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class/segcontrast_t"$TRY"_ep"$WAYMO_EPOCH_1"_ep"$WAYMO_EPOCH_2"/ckpt --ckpt_to_eval 53,33,37
# sbatch --time=7:00:00 --array=1-1%1 --job-name=waymo_seglidarplusdet_"$WAYMO_EPOCH_1"ep_"$WAYMO_EPOCH_2"ep_try"$TRY"_eval tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --mode test_only --tcp_port 16935 --extra_tag segcontrast_lidarplusdet_t$TRY --num_epochs_1 $WAYMO_EPOCH_1 --num_epochs_2 $WAYMO_EPOCH_2 --test_sample_interval 2 --eval_tag val_50perc  --ckpt_dir /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class/segcontrast_lidarplusdet_t"$TRY"_ep"$WAYMO_EPOCH_1"_ep"$WAYMO_EPOCH_2"/ckpt --ckpt_to_eval 70,57,47
# sbatch --time=7:00:00 --array=1-1%1 --job-name=waymo_segonlydet_"$WAYMO_EPOCH_1"ep_"$WAYMO_EPOCH_2"ep_try"$TRY"_eval tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --mode test_only --tcp_port 16936 --extra_tag segcontrast_onlydet_t$TRY --num_epochs_1 $WAYMO_EPOCH_1 --num_epochs_2 $WAYMO_EPOCH_2 --test_sample_interval 2 --eval_tag val_50perc  --ckpt_dir /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class/segcontrast_onlydet_t"$TRY"_ep"$WAYMO_EPOCH_1"_ep"$WAYMO_EPOCH_2"/ckpt --ckpt_to_eval 37,33,31

# TRY=2
# sbatch --time=7:00:00 --array=1-1%1 --job-name=waymo_scratch_"$WAYMO_EPOCH_2"ep_try"$TRY"_eval tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --mode test_only --tcp_port 16937 --extra_tag scratch_t$TRY --num_epochs_1 $WAYMO_EPOCH_2 --test_sample_interval 2 --eval_tag val_50perc  --ckpt_dir /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class/scratch_t"$TRY"_ep"$WAYMO_EPOCH_2"/ckpt --ckpt_to_eval 59,31,62
# sbatch --time=7:00:00 --array=1-1%1 --job-name=waymo_seg_"$WAYMO_EPOCH_1"ep_"$WAYMO_EPOCH_2"ep_try"$TRY"_eval tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --mode test_only --tcp_port 16938 --extra_tag segcontrast_t$TRY --num_epochs_1 $WAYMO_EPOCH_1 --num_epochs_2 $WAYMO_EPOCH_2 --test_sample_interval 2 --eval_tag val_50perc  --ckpt_dir /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class/segcontrast_t"$TRY"_ep"$WAYMO_EPOCH_1"_ep"$WAYMO_EPOCH_2"/ckpt --ckpt_to_eval 78,62,55
# sbatch --time=7:00:00 --array=1-1%1 --job-name=waymo_seglidarplusdet_"$WAYMO_EPOCH_1"ep_"$WAYMO_EPOCH_2"ep_try"$TRY"_eval tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --mode test_only --tcp_port 16939 --extra_tag segcontrast_lidarplusdet_t$TRY --num_epochs_1 $WAYMO_EPOCH_1 --num_epochs_2 $WAYMO_EPOCH_2 --test_sample_interval 2 --eval_tag val_50perc  --ckpt_dir /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class/segcontrast_lidarplusdet_t"$TRY"_ep"$WAYMO_EPOCH_1"_ep"$WAYMO_EPOCH_2"/ckpt --ckpt_to_eval 70,47,54
# sbatch --time=6:00:00 --array=1-1%1 --job-name=waymo_segonlydet_"$WAYMO_EPOCH_1"ep_"$WAYMO_EPOCH_2"ep_try"$TRY"_eval tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --mode test_only --tcp_port 16940 --extra_tag segcontrast_onlydet_t$TRY --num_epochs_1 $WAYMO_EPOCH_1 --num_epochs_2 $WAYMO_EPOCH_2 --test_sample_interval 2 --eval_tag val_50perc  --ckpt_dir /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class/segcontrast_onlydet_t"$TRY"_ep"$WAYMO_EPOCH_1"_ep"$WAYMO_EPOCH_2"/ckpt --ckpt_to_eval 72,51



# Nuscenes
# 5 percent
# which is better without or with batches tracked? and run more tries of that
# TRY=0
# WAYMO_EPOCH_2=40
# # sbatch --time=8:00:00 --array=1-6%1 --job-name=nusc_scratch_"$WAYMO_EPOCH_2"ep_try$TRY tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_1sweeps_sampled_20_all_class.yaml --mode scratch --tcp_port 15929 --extra_tag scratch_t$TRY --num_epochs_1 $WAYMO_EPOCH_2 --test_start_epoch 0 --wandb_run_name scratch_minkunet_pointrcnn --wandb_group ep"$WAYMO_EPOCH_2"_try$TRY
# # sbatch --time=8:00:00 --array=1-6%1 --job-name=nusc_seg_"$WAYMO_EPOCH_1"ep_"$WAYMO_EPOCH_2"ep_try$TRY tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_1sweeps_sampled_20_all_class.yaml --tcp_port 15930 --extra_tag segcontrast_t$TRY --pretrained_model_1 /OpenPCDet/checkpoints/seg_ep199.pth.tar --num_epochs_1 $WAYMO_EPOCH_1 --pretrained_model_2 /OpenPCDet/output/nuscenes_models/pointrcnn_minkunet_1sweeps_sampled_20_all_class/segcontrast_t"$TRY"_ep"$WAYMO_EPOCH_1"_frozen_bb/ckpt/checkpoint_epoch_$WAYMO_EPOCH_1.pth --num_epochs_2 $WAYMO_EPOCH_2 --test_start_epoch 0 --wandb_run_name segcontrast_10perc_waymo_minkunet --wandb_group ep"$WAYMO_EPOCH_1"_ep"$WAYMO_EPOCH_2"_try$TRY
# # sbatch --time=8:00:00 --array=1-6%1 --job-name=nusc_seglidarplusdet_"$WAYMO_EPOCH_1"ep_"$WAYMO_EPOCH_2"ep_try$TRY tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_1sweeps_sampled_20_all_class.yaml --tcp_port 15931 --extra_tag segcontrast_lidarplusdet_t$TRY --pretrained_model_1 /OpenPCDet/checkpoints/seg_lidar_plus_det_ep199_t2.pth.tar --num_epochs_1 $WAYMO_EPOCH_1 --pretrained_model_2 /OpenPCDet/output/nuscenes_models/pointrcnn_minkunet_1sweeps_sampled_20_all_class/segcontrast_lidarplusdet_t"$TRY"_ep"$WAYMO_EPOCH_1"_frozen_bb/ckpt/checkpoint_epoch_$WAYMO_EPOCH_1.pth --num_epochs_2 $WAYMO_EPOCH_2 --test_start_epoch 0 --wandb_run_name segcontrast_lidarplusdet_10perc_waymo_minkunet --wandb_group ep"$WAYMO_EPOCH_1"_ep"$WAYMO_EPOCH_2"_try$TRY
# # sbatch --time=8:00:00 --array=1-6%1 --job-name=nusc_segonlydet_"$WAYMO_EPOCH_1"ep_"$WAYMO_EPOCH_2"ep_try$TRY tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_1sweeps_sampled_20_all_class.yaml --tcp_port 15932 --extra_tag segcontrast_onlydet_t$TRY --pretrained_model_1 /OpenPCDet/checkpoints/seg_only_det_ep199_t2.pth.tar --num_epochs_1 $WAYMO_EPOCH_1 --pretrained_model_2 /OpenPCDet/output/nuscenes_models/pointrcnn_minkunet_1sweeps_sampled_20_all_class/segcontrast_onlydet_t"$TRY"_ep"$WAYMO_EPOCH_1"_frozen_bb/ckpt/checkpoint_epoch_$WAYMO_EPOCH_1.pth --num_epochs_2 $WAYMO_EPOCH_2 --test_start_epoch 0 --wandb_run_name segcontrast_det_10perc_waymo_minkunet --wandb_group ep"$WAYMO_EPOCH_1"_ep"$WAYMO_EPOCH_2"_try$TRY 
# sbatch --time=8:00:00 --array=1-6%1 --job-name=nusc_seglidar_"$WAYMO_EPOCH_1"ep_"$WAYMO_EPOCH_2"ep_try$TRY tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_1sweeps_sampled_20_all_class.yaml --tcp_port 15933 --extra_tag segcontrast_lidar_t$TRY --pretrained_model_1 /OpenPCDet/checkpoints/seg_lidar_ep199.pth.tar --num_epochs_1 $WAYMO_EPOCH_1 --pretrained_model_2 /OpenPCDet/output/nuscenes_models/pointrcnn_minkunet_1sweeps_sampled_20_all_class/segcontrast_lidar_t"$TRY"_ep"$WAYMO_EPOCH_1"_frozen_bb/ckpt/checkpoint_epoch_$WAYMO_EPOCH_1.pth --num_epochs_2 $WAYMO_EPOCH_2 --test_start_epoch 0 --wandb_run_name segcontrast_lidaraug_single_randh_10perc_waymo_minkunet --wandb_group ep"$WAYMO_EPOCH_1"_ep"$WAYMO_EPOCH_2"_try$TRY 

# TRY=1
# # WAYMO_EPOCH_2=40
# # sbatch --time=8:00:00 --array=1-6%1 --job-name=nusc_scratch_"$WAYMO_EPOCH_2"ep_try$TRY tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_1sweeps_sampled_20_all_class.yaml --mode scratch --tcp_port 15933 --extra_tag scratch_t$TRY --num_epochs_1 $WAYMO_EPOCH_2 --test_start_epoch 0 --wandb_run_name scratch_minkunet_pointrcnn --wandb_group ep"$WAYMO_EPOCH_2"_try$TRY
# # sbatch --time=8:00:00 --array=1-6%1 --job-name=nusc_seg_"$WAYMO_EPOCH_1"ep_"$WAYMO_EPOCH_2"ep_try$TRY tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_1sweeps_sampled_20_all_class.yaml --tcp_port 15934 --extra_tag segcontrast_t$TRY --pretrained_model_1 /OpenPCDet/checkpoints/seg_ep199.pth.tar --num_epochs_1 $WAYMO_EPOCH_1 --pretrained_model_2 /OpenPCDet/output/nuscenes_models/pointrcnn_minkunet_1sweeps_sampled_20_all_class/segcontrast_t"$TRY"_ep"$WAYMO_EPOCH_1"_frozen_bb/ckpt/checkpoint_epoch_$WAYMO_EPOCH_1.pth --num_epochs_2 $WAYMO_EPOCH_2 --test_start_epoch 0 --wandb_run_name segcontrast_10perc_waymo_minkunet --wandb_group ep"$WAYMO_EPOCH_1"_ep"$WAYMO_EPOCH_2"_try$TRY
# # sbatch --time=8:00:00 --array=1-6%1 --job-name=nusc_seglidarplusdet_"$WAYMO_EPOCH_1"ep_"$WAYMO_EPOCH_2"ep_try$TRY tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_1sweeps_sampled_20_all_class.yaml --tcp_port 15935 --extra_tag segcontrast_lidarplusdet_t$TRY --pretrained_model_1 /OpenPCDet/checkpoints/seg_lidar_plus_det_ep199_t2.pth.tar --num_epochs_1 $WAYMO_EPOCH_1 --pretrained_model_2 /OpenPCDet/output/nuscenes_models/pointrcnn_minkunet_1sweeps_sampled_20_all_class/segcontrast_lidarplusdet_t"$TRY"_ep"$WAYMO_EPOCH_1"_frozen_bb/ckpt/checkpoint_epoch_$WAYMO_EPOCH_1.pth --num_epochs_2 $WAYMO_EPOCH_2 --test_start_epoch 0 --wandb_run_name segcontrast_lidarplusdet_10perc_waymo_minkunet --wandb_group ep"$WAYMO_EPOCH_1"_ep"$WAYMO_EPOCH_2"_try$TRY
# # sbatch --time=8:00:00 --array=1-6%1 --job-name=nusc_segonlydet_"$WAYMO_EPOCH_1"ep_"$WAYMO_EPOCH_2"ep_try$TRY tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_1sweeps_sampled_20_all_class.yaml --tcp_port 15936 --extra_tag segcontrast_onlydet_t$TRY --pretrained_model_1 /OpenPCDet/checkpoints/seg_only_det_ep199_t2.pth.tar --num_epochs_1 $WAYMO_EPOCH_1 --pretrained_model_2 /OpenPCDet/output/nuscenes_models/pointrcnn_minkunet_1sweeps_sampled_20_all_class/segcontrast_onlydet_t"$TRY"_ep"$WAYMO_EPOCH_1"_frozen_bb/ckpt/checkpoint_epoch_$WAYMO_EPOCH_1.pth --num_epochs_2 $WAYMO_EPOCH_2 --test_start_epoch 0 --wandb_run_name segcontrast_det_10perc_waymo_minkunet --wandb_group ep"$WAYMO_EPOCH_1"_ep"$WAYMO_EPOCH_2"_try$TRY 
# sbatch --time=8:00:00 --array=1-6%1 --job-name=nusc_seglidar_"$WAYMO_EPOCH_1"ep_"$WAYMO_EPOCH_2"ep_try$TRY tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_1sweeps_sampled_20_all_class.yaml --tcp_port 15943 --extra_tag segcontrast_lidar_t$TRY --pretrained_model_1 /OpenPCDet/checkpoints/seg_lidar_ep199.pth.tar --num_epochs_1 $WAYMO_EPOCH_1 --pretrained_model_2 /OpenPCDet/output/nuscenes_models/pointrcnn_minkunet_1sweeps_sampled_20_all_class/segcontrast_lidar_t"$TRY"_ep"$WAYMO_EPOCH_1"_frozen_bb/ckpt/checkpoint_epoch_$WAYMO_EPOCH_1.pth --num_epochs_2 $WAYMO_EPOCH_2 --test_start_epoch 0 --wandb_run_name segcontrast_lidaraug_single_randh_10perc_waymo_minkunet --wandb_group ep"$WAYMO_EPOCH_1"_ep"$WAYMO_EPOCH_2"_try$TRY 

# TRY=2
# # WAYMO_EPOCH_2=40
# # sbatch --time=8:00:00 --array=1-6%1 --job-name=nusc_scratch_"$WAYMO_EPOCH_2"ep_try$TRY tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_1sweeps_sampled_20_all_class.yaml --mode scratch --tcp_port 15937 --extra_tag scratch_t$TRY --num_epochs_1 $WAYMO_EPOCH_2 --test_start_epoch 0 --wandb_run_name scratch_minkunet_pointrcnn --wandb_group ep"$WAYMO_EPOCH_2"_try$TRY
# # sbatch --time=8:00:00 --array=1-6%1 --job-name=nusc_seg_"$WAYMO_EPOCH_1"ep_"$WAYMO_EPOCH_2"ep_try$TRY tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_1sweeps_sampled_20_all_class.yaml --tcp_port 15938 --extra_tag segcontrast_t$TRY --pretrained_model_1 /OpenPCDet/checkpoints/seg_ep199.pth.tar --num_epochs_1 $WAYMO_EPOCH_1 --pretrained_model_2 /OpenPCDet/output/nuscenes_models/pointrcnn_minkunet_1sweeps_sampled_20_all_class/segcontrast_t"$TRY"_ep"$WAYMO_EPOCH_1"_frozen_bb/ckpt/checkpoint_epoch_$WAYMO_EPOCH_1.pth --num_epochs_2 $WAYMO_EPOCH_2 --test_start_epoch 0 --wandb_run_name segcontrast_10perc_waymo_minkunet --wandb_group ep"$WAYMO_EPOCH_1"_ep"$WAYMO_EPOCH_2"_try$TRY
# # sbatch --time=8:00:00 --array=1-6%1 --job-name=nusc_seglidarplusdet_"$WAYMO_EPOCH_1"ep_"$WAYMO_EPOCH_2"ep_try$TRY tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_1sweeps_sampled_20_all_class.yaml --tcp_port 15939 --extra_tag segcontrast_lidarplusdet_t$TRY --pretrained_model_1 /OpenPCDet/checkpoints/seg_lidar_plus_det_ep199_t2.pth.tar --num_epochs_1 $WAYMO_EPOCH_1 --pretrained_model_2 /OpenPCDet/output/nuscenes_models/pointrcnn_minkunet_1sweeps_sampled_20_all_class/segcontrast_lidarplusdet_t"$TRY"_ep"$WAYMO_EPOCH_1"_frozen_bb/ckpt/checkpoint_epoch_$WAYMO_EPOCH_1.pth --num_epochs_2 $WAYMO_EPOCH_2 --test_start_epoch 0 --wandb_run_name segcontrast_lidarplusdet_10perc_waymo_minkunet --wandb_group ep"$WAYMO_EPOCH_1"_ep"$WAYMO_EPOCH_2"_try$TRY
# # sbatch --time=8:00:00 --array=1-6%1 --job-name=nusc_segonlydet_"$WAYMO_EPOCH_1"ep_"$WAYMO_EPOCH_2"ep_try$TRY tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_1sweeps_sampled_20_all_class.yaml --tcp_port 15940 --extra_tag segcontrast_onlydet_t$TRY --pretrained_model_1 /OpenPCDet/checkpoints/seg_only_det_ep199_t2.pth.tar --num_epochs_1 $WAYMO_EPOCH_1 --pretrained_model_2 /OpenPCDet/output/nuscenes_models/pointrcnn_minkunet_1sweeps_sampled_20_all_class/segcontrast_onlydet_t"$TRY"_ep"$WAYMO_EPOCH_1"_frozen_bb/ckpt/checkpoint_epoch_$WAYMO_EPOCH_1.pth --num_epochs_2 $WAYMO_EPOCH_2 --test_start_epoch 0 --wandb_run_name segcontrast_det_10perc_waymo_minkunet --wandb_group ep"$WAYMO_EPOCH_1"_ep"$WAYMO_EPOCH_2"_try$TRY 
# sbatch --time=8:00:00 --array=1-6%1 --job-name=nusc_seglidar_"$WAYMO_EPOCH_1"ep_"$WAYMO_EPOCH_2"ep_try$TRY tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_1sweeps_sampled_20_all_class.yaml --tcp_port 15953 --extra_tag segcontrast_lidar_t$TRY --pretrained_model_1 /OpenPCDet/checkpoints/seg_lidar_ep199.pth.tar --num_epochs_1 $WAYMO_EPOCH_1 --pretrained_model_2 /OpenPCDet/output/nuscenes_models/pointrcnn_minkunet_1sweeps_sampled_20_all_class/segcontrast_lidar_t"$TRY"_ep"$WAYMO_EPOCH_1"_frozen_bb/ckpt/checkpoint_epoch_$WAYMO_EPOCH_1.pth --num_epochs_2 $WAYMO_EPOCH_2 --test_start_epoch 0 --wandb_run_name segcontrast_lidaraug_single_randh_10perc_waymo_minkunet --wandb_group ep"$WAYMO_EPOCH_1"_ep"$WAYMO_EPOCH_2"_try$TRY 

