# Train Pointrcnn Kitti 100%
# sbatch --time=03:00:00 --gres=gpu:t4:4 --array=1-5%1 --job-name=kitti-pointrcnn tools/scripts/compute_canada_train_eval_kitti.sh --cfg_file tools/cfgs/kitti_models/pointrcnn.yaml --tcp_port 18461 --ckpt_save_interval 1 --fix_random_seed

# Test Pointrcnn Kitti 100%
#sbatch --time=02:00:00 --array=1-4%1 --job-name=kitti-pointrcnn-val  tools/scripts/compute_canada_train_eval_kitti.sh --cfg_file tools/cfgs/kitti_models/pointrcnn.yaml --tcp_port 18795 --fix_random_seed --test_only --eval_tag kitti_infos_val

# Train Pointrcnn Kitti 5%
# sbatch --time=04:00:00 --gres=gpu:t4:4 --array=1-2%1 --job-name=kitti-pointrcnn_train_5_1_200epochs_allgtdb tools/scripts/compute_canada_train_eval_kitti.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_train_5_1_200epochs_allgtdb.yaml --tcp_port 18465 --ckpt_save_interval 1 --fix_random_seed
# sbatch --time=04:00:00 --gres=gpu:t4:4 --array=1-2%1 --job-name=kitti-pointrcnn_train_5_2_200epochs_allgtdb tools/scripts/compute_canada_train_eval_kitti.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_train_5_2_200epochs_allgtdb.yaml --tcp_port 18475 --ckpt_save_interval 1 --fix_random_seed
# sbatch --time=04:00:00 --gres=gpu:t4:4 --array=1-2%1 --job-name=kitti-pointrcnn_train_5_0_200epochs_allgtdb tools/scripts/compute_canada_train_eval_kitti.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_train_5_0_200epochs_allgtdb.yaml --tcp_port 18485 --ckpt_save_interval 1 --fix_random_seed


# sbatch --time=02:00:00 --gres=gpu:t4:4 --array=1-4%1 --job-name=kitti-pointrcnn_train_5_1_200epochs tools/scripts/compute_canada_train_eval_kitti.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_train_5_1_200epochs.yaml --tcp_port 18465 --ckpt_save_interval 1 --fix_random_seed
# sbatch --time=02:00:00 --gres=gpu:t4:4 --array=1-4%1 --job-name=kitti-pointrcnn_train_5_2_200epochs tools/scripts/compute_canada_train_eval_kitti.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_train_5_2_200epochs.yaml --tcp_port 18475 --ckpt_save_interval 1 --fix_random_seed
# sbatch --time=02:00:00 --gres=gpu:t4:4 --array=1-4%1 --job-name=kitti-pointrcnn_train_5_0_200epochs tools/scripts/compute_canada_train_eval_kitti.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_train_5_0_200epochs.yaml --tcp_port 18485 --ckpt_save_interval 1 --fix_random_seed

# sbatch --time=02:00:00 --gres=gpu:t4:4 --array=1-6%1 --job-name=kitti-pointrcnn_train_5_1_500epochs tools/scripts/compute_canada_train_eval_kitti.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_train_5_1_500epochs.yaml --tcp_port 18474 --ckpt_save_interval 1 --fix_random_seed
# sbatch --time=02:00:00 --gres=gpu:t4:4 --array=1-6%1 --job-name=kitti-pointrcnn_train_5_2_500epochs tools/scripts/compute_canada_train_eval_kitti.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_train_5_2_500epochs.yaml --tcp_port 18475 --ckpt_save_interval 1 --fix_random_seed
# sbatch --time=02:00:00 --gres=gpu:t4:4 --array=1-6%1 --job-name=kitti-pointrcnn_train_5_0_500epochs tools/scripts/compute_canada_train_eval_kitti.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_train_5_0_500epochs.yaml --tcp_port 18476 --ckpt_save_interval 1 --fix_random_seed

# sbatch --time=02:00:00 --gres=gpu:t4:4 --array=1-10%1 --job-name=kitti-pointrcnn_train_5_1_1000epochs tools/scripts/compute_canada_train_eval_kitti.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_train_5_1_1000epochs.yaml --tcp_port 18484 --ckpt_save_interval 12 --fix_random_seed
# sbatch --time=02:00:00 --gres=gpu:t4:4 --array=1-10%1 --job-name=kitti-pointrcnn_train_5_2_1000epochs tools/scripts/compute_canada_train_eval_kitti.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_train_5_2_1000epochs.yaml --tcp_port 18485 --ckpt_save_interval 12 --fix_random_seed
# #sbatch --time=02:00:00 --gres=gpu:t4:4 --array=1-10%1 --job-name=kitti-pointrcnn_train_5_1000epochs tools/scripts/compute_canada_train_eval_kitti.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_train_5_1000epochs.yaml --tcp_port 18486 --ckpt_save_interval 12 --fix_random_seed

# sbatch --time=02:00:00 --gres=gpu:t4:4 --array=1-20%1 --job-name=kitti-pointrcnn_train_5_1600epochs tools/scripts/compute_canada_train_eval_kitti.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_train_5_1600epochs.yaml --tcp_port 18495 --ckpt_save_interval 20 --fix_random_seed

# # TODO: Test Pointrcnn Kitti 5%
sbatch --time=10:00:00 --array=1-1%1 --job-name=kitti-pointrcnn_train_5_1_200epochs_allgtdb-val  tools/scripts/compute_canada_train_eval_kitti.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_train_5_1_200epochs_allgtdb.yaml --tcp_port 18771 --fix_random_seed --test_only --eval_tag kitti_infos_val
sbatch --time=10:00:00 --array=1-1%1 --job-name=kitti-pointrcnn_train_5_2_200epochs_allgtdb-val  tools/scripts/compute_canada_train_eval_kitti.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_train_5_2_200epochs_allgtdb.yaml --tcp_port 18781 --fix_random_seed --test_only --eval_tag kitti_infos_val
sbatch --time=10:00:00 --array=1-1%1 --job-name=kitti-pointrcnn_train_5_0_200epochs_allgtdb-val  tools/scripts/compute_canada_train_eval_kitti.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_train_5_0_200epochs_allgtdb.yaml --tcp_port 18791 --fix_random_seed --test_only --eval_tag kitti_infos_val

# sbatch --time=04:00:00 --array=1-2%1 --job-name=kitti-pointrcnn_train_5_1_200epochs-val  tools/scripts/compute_canada_train_eval_kitti.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_train_5_1_200epochs.yaml --tcp_port 18771 --fix_random_seed --test_only --eval_tag kitti_infos_val
# sbatch --time=04:00:00 --array=1-2%1 --job-name=kitti-pointrcnn_train_5_2_200epochs-val  tools/scripts/compute_canada_train_eval_kitti.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_train_5_2_200epochs.yaml --tcp_port 18781 --fix_random_seed --test_only --eval_tag kitti_infos_val
# sbatch --time=04:00:00 --array=1-2%1 --job-name=kitti-pointrcnn_train_5_0_200epochs-val  tools/scripts/compute_canada_train_eval_kitti.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_train_5_0_200epochs.yaml --tcp_port 18791 --fix_random_seed --test_only --eval_tag kitti_infos_val
# sbatch --time=02:00:00 --array=1-4%1 --job-name=kitti-pointrcnn_train_5_0_500epochs-val  tools/scripts/compute_canada_train_eval_kitti.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_train_5_0_500epochs.yaml --tcp_port 18792 --fix_random_seed --test_only --eval_tag kitti_infos_val
# sbatch --time=02:00:00 --array=1-4%1 --job-name=kitti-pointrcnn_train_5_1_500epochs-val  tools/scripts/compute_canada_train_eval_kitti.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_train_5_1_500epochs.yaml --tcp_port 18793 --fix_random_seed --test_only --eval_tag kitti_infos_val
# sbatch --time=02:00:00 --array=1-4%1 --job-name=kitti-pointrcnn_train_5_2_500epochs-val  tools/scripts/compute_canada_train_eval_kitti.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_train_5_2_500epochs.yaml --tcp_port 18794 --fix_random_seed --test_only --eval_tag kitti_infos_val

# sbatch --time=02:00:00 --array=1-4%1 --job-name=kitti-pointrcnn_train_5_1_1000epochs-val  tools/scripts/compute_canada_train_eval_kitti.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_train_5_1_1000epochs.yaml --tcp_port 18795 --fix_random_seed --test_only --eval_tag kitti_infos_val
# sbatch --time=02:00:00 --array=1-4%1 --job-name=kitti-pointrcnn_train_5_2_1000epochs-val  tools/scripts/compute_canada_train_eval_kitti.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_train_5_2_1000epochs.yaml --tcp_port 18796 --fix_random_seed --test_only --eval_tag kitti_infos_val

# sbatch --time=02:00:00 --array=1-4%1 --job-name=kitti-pointrcnn_train_5_1000epochs-val  tools/scripts/compute_canada_train_eval_kitti.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_train_5_1000epochs.yaml --tcp_port 18793 --fix_random_seed --test_only --eval_tag kitti_infos_val
# sbatch --time=02:00:00 --array=1-4%1 --job-name=kitti-pointrcnn_train_5_1600epochs-val  tools/scripts/compute_canada_train_eval_kitti.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_train_5_1600epochs.yaml --tcp_port 18794 --fix_random_seed --test_only --eval_tag kitti_infos_val

# Finetune pointrcnn on Kitti 5%
# sbatch --time=04:00:00 --gres=gpu:t4:4 --array=1-2%1 --job-name=finetune-kitti-200epochs_5_0_seg_semkitti_all_ep401_allgtdb tools/scripts/compute_canada_train_eval_kitti.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_finetune_train_5_0_200epochs_allgtdb.yaml --extra_tag seg_semKitti_all_ep401 --tcp_port 18821 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/seg_semkitti_all_checkpoint.pth.tar
# sbatch --time=04:00:00 --gres=gpu:t4:4 --array=1-2%1 --job-name=finetune-kitti-200epochs_5_1_seg_semkitti_all_ep401_allgtdb tools/scripts/compute_canada_train_eval_kitti.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_finetune_train_5_1_200epochs_allgtdb.yaml --extra_tag seg_semKitti_all_ep401 --tcp_port 18822 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/seg_semkitti_all_checkpoint.pth.tar
# sbatch --time=04:00:00 --gres=gpu:t4:4 --array=1-2%1 --job-name=finetune-kitti-200epochs_5_2_seg_semkitti_all_ep401_allgtdb tools/scripts/compute_canada_train_eval_kitti.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_finetune_train_5_2_200epochs_allgtdb.yaml --extra_tag seg_semKitti_all_ep401 --tcp_port 18823 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/seg_semkitti_all_checkpoint.pth.tar

# sbatch --time=02:00:00 --gres=gpu:t4:4 --array=1-4%1 --job-name=finetune-kitti-200epochs_5_0_seg_semkitti_all_ep401 tools/scripts/compute_canada_train_eval_kitti.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_finetune_train_5_0_200epochs.yaml --extra_tag seg_semKitti_all_ep401 --tcp_port 18821 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/seg_semkitti_all_checkpoint.pth.tar
# sbatch --time=02:00:00 --gres=gpu:t4:4 --array=1-4%1 --job-name=finetune-kitti-200epochs_5_1_seg_semkitti_all_ep401 tools/scripts/compute_canada_train_eval_kitti.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_finetune_train_5_1_200epochs.yaml --extra_tag seg_semKitti_all_ep401 --tcp_port 18822 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/seg_semkitti_all_checkpoint.pth.tar
# sbatch --time=02:00:00 --gres=gpu:t4:4 --array=1-4%1 --job-name=finetune-kitti-200epochs_5_2_seg_semkitti_all_ep401 tools/scripts/compute_canada_train_eval_kitti.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_finetune_train_5_2_200epochs.yaml --extra_tag seg_semKitti_all_ep401 --tcp_port 18823 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/seg_semkitti_all_checkpoint.pth.tar

# sbatch --time=02:00:00 --gres=gpu:t4:4 --array=1-6%1 --job-name=finetune-kitti-500epochs_5_0_seg_semkitti_all_ep401 tools/scripts/compute_canada_train_eval_kitti.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_finetune_train_5_0_500epochs.yaml --extra_tag seg_semKitti_all_ep401 --tcp_port 18824 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/seg_semkitti_all_checkpoint.pth.tar
# sbatch --time=02:00:00 --gres=gpu:t4:4 --array=1-6%1 --job-name=finetune-kitti-500epochs_5_1_seg_semkitti_all_ep401 tools/scripts/compute_canada_train_eval_kitti.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_finetune_train_5_1_500epochs.yaml --extra_tag seg_semKitti_all_ep401 --tcp_port 18825 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/seg_semkitti_all_checkpoint.pth.tar
# sbatch --time=02:00:00 --gres=gpu:t4:4 --array=1-6%1 --job-name=finetune-kitti-500epochs_5_2_seg_semkitti_all_ep401 tools/scripts/compute_canada_train_eval_kitti.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_finetune_train_5_2_500epochs.yaml --extra_tag seg_semKitti_all_ep401 --tcp_port 18826 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/seg_semkitti_all_checkpoint.pth.tar

# Test finetune
sbatch --time=10:00:00 --array=1-1%1 --job-name=kitti-200epochs_5_0_seg_semkitti_all_ep401_allgtdb-val  tools/scripts/compute_canada_train_eval_kitti.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_finetune_train_5_0_200epochs_allgtdb.yaml --extra_tag seg_semKitti_all_ep401 --tcp_port 18795 --fix_random_seed --test_only --eval_tag kitti_infos_val
sbatch --time=10:00:00 --array=1-1%1 --job-name=kitti-200epochs_5_1_seg_semkitti_all_ep401_allgtdb-val  tools/scripts/compute_canada_train_eval_kitti.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_finetune_train_5_1_200epochs_allgtdb.yaml --extra_tag seg_semKitti_all_ep401 --tcp_port 18796 --fix_random_seed --test_only --eval_tag kitti_infos_val
sbatch --time=10:00:00 --array=1-1%1 --job-name=kitti-200epochs_5_2_seg_semkitti_all_ep401_allgtdb-val  tools/scripts/compute_canada_train_eval_kitti.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_finetune_train_5_2_200epochs_allgtdb.yaml --extra_tag seg_semKitti_all_ep401 --tcp_port 18797 --fix_random_seed --test_only --eval_tag kitti_infos_val


# sbatch --time=02:00:00 --array=1-7%1 --job-name=kitti-200epochs_5_0_seg_semkitti_all_ep401-val  tools/scripts/compute_canada_train_eval_kitti.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_finetune_train_5_0_200epochs.yaml --extra_tag seg_semKitti_all_ep401 --tcp_port 18795 --fix_random_seed --test_only --eval_tag kitti_infos_val
# sbatch --time=02:00:00 --array=1-7%1 --job-name=kitti-200epochs_5_1_seg_semkitti_all_ep401-val  tools/scripts/compute_canada_train_eval_kitti.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_finetune_train_5_1_200epochs.yaml --extra_tag seg_semKitti_all_ep401 --tcp_port 18796 --fix_random_seed --test_only --eval_tag kitti_infos_val
# sbatch --time=02:00:00 --array=1-7%1 --job-name=kitti-200epochs_5_2_seg_semkitti_all_ep401-val  tools/scripts/compute_canada_train_eval_kitti.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_finetune_train_5_2_200epochs.yaml --extra_tag seg_semKitti_all_ep401 --tcp_port 18797 --fix_random_seed --test_only --eval_tag kitti_infos_val

# sbatch --time=02:00:00 --array=1-10%1 --job-name=kitti-500epochs_5_0_seg_semkitti_all_ep401-val  tools/scripts/compute_canada_train_eval_kitti.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_finetune_train_5_0_500epochs.yaml --extra_tag seg_semKitti_all_ep401 --tcp_port 18792 --fix_random_seed --test_only --eval_tag kitti_infos_val
# sbatch --time=02:00:00 --array=1-10%1 --job-name=kitti-500epochs_5_1_seg_semkitti_all_ep401-val  tools/scripts/compute_canada_train_eval_kitti.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_finetune_train_5_1_500epochs.yaml --extra_tag seg_semKitti_all_ep401 --tcp_port 18793 --fix_random_seed --test_only --eval_tag kitti_infos_val
# sbatch --time=02:00:00 --array=1-10%1 --job-name=kitti-500epochs_5_2_seg_semkitti_all_ep401-val  tools/scripts/compute_canada_train_eval_kitti.sh --cfg_file tools/cfgs/kitti_models/pointrcnn_finetune_train_5_2_500epochs.yaml --extra_tag seg_semKitti_all_ep401 --tcp_port 18794 --fix_random_seed --test_only --eval_tag kitti_infos_val