########### Pretrained on dense + kitti ###########
########### seg + weather aug ###########

# TODO (2nd High priority)
sbatch  --time=02:00:00 --gres=gpu:t4:4 --array=1-20%1 --job-name=finetune-all_splits_5_seg_1in2_cube_up_dense_kitti_ep200 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_5.yaml --extra_tag seg_1in2_cube_up_dense_kitti_ep200 --tcp_port 18855 --ckpt_save_interval 20 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/seg_1in2_cube_up_dense_kitti_ep200.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_splits_10_seg_1in2_cube_up_dense_kitti_ep200 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_10.yaml --extra_tag seg_1in2_cube_up_dense_kitti_ep200 --tcp_port 18855 --ckpt_save_interval 10 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/seg_1in2_cube_up_dense_kitti_ep200.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_splits_20_seg_1in2_cube_up_dense_kitti_ep200 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_20.yaml --extra_tag seg_1in2_cube_up_dense_kitti_ep200 --tcp_port 18855 --ckpt_save_interval 5 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/seg_1in2_cube_up_dense_kitti_ep200.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_splits_30_seg_1in2_cube_up_dense_kitti_ep200 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_30.yaml --extra_tag seg_1in2_cube_up_dense_kitti_ep200 --tcp_port 18855 --ckpt_save_interval 3 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/seg_1in2_cube_up_dense_kitti_ep200.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_splits_40_seg_1in2_cube_up_dense_kitti_ep200 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_40.yaml --extra_tag seg_1in2_cube_up_dense_kitti_ep200 --tcp_port 18855 --ckpt_save_interval 2 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/seg_1in2_cube_up_dense_kitti_ep200.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_splits_50_seg_1in2_cube_up_dense_kitti_ep200 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_50.yaml --extra_tag seg_1in2_cube_up_dense_kitti_ep200 --tcp_port 18855 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/seg_1in2_cube_up_dense_kitti_ep200.pth.tar

#sbatch --time=03:00:00 --gres=gpu:t4:4 --array=1-1%1 --job-name=finetune-all_60_1_seg_1in2_cube_up_dense_kitti_ep200 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_1.yaml --extra_tag seg_1in2_cube_up_dense_kitti_ep200 --tcp_port 18525 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/seg_1in2_cube_up_dense_kitti_ep200.pth.tar
#sbatch --time=02:00:00 --gres=gpu:t4:4 --array=1-6%1 --job-name=finetune-all_60_1_adamw_seg_1in2_cube_up_dense_kitti_ep200 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_1_adamw.yaml --extra_tag seg_1in2_cube_up_dense_kitti_ep200 --tcp_port 18225 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/seg_1in2_cube_up_dense_kitti_ep200.pth.tar

sbatch --time=02:00:00 --gres=gpu:t4:4 --array=1-6%1 --job-name=finetune-all_60_1_adamO_0p003_0p001_0p4_seg_1in2_cube_up_dense_kitti_ep200 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_1_adamO_0p003_0p001_0p4.yaml --extra_tag seg_1in2_cube_up_dense_kitti_ep200 --tcp_port 18225 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/seg_1in2_cube_up_dense_kitti_ep200.pth.tar
sbatch --time=02:00:00 --gres=gpu:t4:4 --array=1-6%1 --job-name=finetune-all_60_1_adamW_0p003_0p001_0p1_seg_1in2_cube_up_dense_kitti_ep200 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_1_adamW_0p003_0p001_0p1.yaml --extra_tag seg_1in2_cube_up_dense_kitti_ep200 --tcp_port 18226 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/seg_1in2_cube_up_dense_kitti_ep200.pth.tar
sbatch --time=02:00:00 --gres=gpu:t4:4 --array=1-6%1 --job-name=finetune-all_60_1_adamW_0p003_0p001_0p4_seg_1in2_cube_up_dense_kitti_ep200 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_1_adamW_0p003_0p001_0p4.yaml --extra_tag seg_1in2_cube_up_dense_kitti_ep200 --tcp_port 18227 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/seg_1in2_cube_up_dense_kitti_ep200.pth.tar
sbatch --time=02:00:00 --gres=gpu:t4:4 --array=1-6%1 --job-name=finetune-all_60_1_adamW_0p003_0p001_0p8_seg_1in2_cube_up_dense_kitti_ep200 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_1_adamW_0p003_0p001_0p8.yaml --extra_tag seg_1in2_cube_up_dense_kitti_ep200 --tcp_port 18228 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/seg_1in2_cube_up_dense_kitti_ep200.pth.tar

# TODO (2nd High priority)
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_60_5_seg_1in2_cube_up_dense_kitti_ep200 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_5.yaml --extra_tag seg_1in2_cube_up_dense_kitti_ep200 --tcp_port 18855 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/seg_1in2_cube_up_dense_kitti_ep200.pth.tar

# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_60_5_seg_1in2_cube_up_dense_kitti_ep200 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_5.yaml --extra_tag seg_1in2_cube_up_dense_kitti_ep200 --tcp_port 18855 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/seg_1in2_cube_up_dense_kitti_ep200.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_60_10_seg_1in2_cube_up_dense_kitti_ep200 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_10.yaml --extra_tag seg_1in2_cube_up_dense_kitti_ep200 --tcp_port 18855 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/seg_1in2_cube_up_dense_kitti_ep200.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_60_20_seg_1in2_cube_up_dense_kitti_ep200 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_20.yaml --extra_tag seg_1in2_cube_up_dense_kitti_ep200 --tcp_port 18855 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/seg_1in2_cube_up_dense_kitti_ep200.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_60_30_seg_1in2_cube_up_dense_kitti_ep200 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_30.yaml --extra_tag seg_1in2_cube_up_dense_kitti_ep200 --tcp_port 18855 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/seg_1in2_cube_up_dense_kitti_ep200.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_60_40_seg_1in2_cube_up_dense_kitti_ep200 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_40.yaml --extra_tag seg_1in2_cube_up_dense_kitti_ep200 --tcp_port 18855 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/seg_1in2_cube_up_dense_kitti_ep200.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_60_50_seg_1in2_cube_up_dense_kitti_ep200 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_50.yaml --extra_tag seg_1in2_cube_up_dense_kitti_ep200 --tcp_port 18855 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/seg_1in2_cube_up_dense_kitti_ep200.pth.tar

########### Pretrained on dense + kitti ###########
########### seg ###########
# TODO (2nd High priority)
sbatch  --time=02:00:00 --gres=gpu:t4:4 --array=1-20%1 --job-name=finetune-all_splits_5_seg_dense_kitti_ep200 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_5.yaml --extra_tag seg_dense_kitti_ep200 --tcp_port 18856 --ckpt_save_interval 20 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/seg_dense_kitti_ep200.pth.tar

# sbatch --time=15:00:00 --array=1-2%1 --job-name=finetune-all_splits_5_seg_dense_kitti_ep200 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_5.yaml --extra_tag seg_dense_kitti_ep200 --tcp_port 18855 --ckpt_save_interval 20 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/seg_dense_kitti_ep200.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_splits_10_seg_dense_kitti_ep200 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_10.yaml --extra_tag seg_dense_kitti_ep200 --tcp_port 18855 --ckpt_save_interval 10 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/seg_dense_kitti_ep200.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_splits_20_seg_dense_kitti_ep200 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_20.yaml --extra_tag seg_dense_kitti_ep200 --tcp_port 18855 --ckpt_save_interval 5 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/seg_dense_kitti_ep200.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_splits_30_seg_dense_kitti_ep200 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_30.yaml --extra_tag seg_dense_kitti_ep200 --tcp_port 18855 --ckpt_save_interval 3 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/seg_dense_kitti_ep200.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_splits_40_seg_dense_kitti_ep200 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_40.yaml --extra_tag seg_dense_kitti_ep200 --tcp_port 18855 --ckpt_save_interval 2 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/seg_dense_kitti_ep200.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_splits_50_seg_dense_kitti_ep200 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_50.yaml --extra_tag seg_dense_kitti_ep200 --tcp_port 18855 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/seg_dense_kitti_ep200.pth.tar

#sbatch --time=03:00:00 --gres=gpu:t4:4 --array=1-1%1 --job-name=finetune-all_60_1_seg_dense_kitti_ep200 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_1.yaml --extra_tag seg_dense_kitti_ep200 --tcp_port 18125 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/seg_dense_kitti_ep200.pth.tar
#sbatch --time=02:00:00 --gres=gpu:t4:4 --array=1-6%1 --job-name=finetune-all_60_1_adamw_seg_dense_kitti_ep200 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_1_adamw.yaml --extra_tag seg_dense_kitti_ep200 --tcp_port 18425 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/seg_dense_kitti_ep200.pth.tar


sbatch --time=02:00:00 --gres=gpu:t4:4 --array=1-6%1 --job-name=finetune-all_60_1_adamO_0p003_0p001_0p4_seg_dense_kitti_ep200 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_1_adamO_0p003_0p001_0p4.yaml --extra_tag seg_dense_kitti_ep200 --tcp_port 18230 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/seg_dense_kitti_ep200.pth.tar

# TODO (2nd High priority)
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_60_5_seg_dense_kitti_ep200 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_5.yaml --extra_tag seg_dense_kitti_ep200 --tcp_port 18855 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/seg_dense_kitti_ep200.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_60_10_seg_dense_kitti_ep200 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_10.yaml --extra_tag seg_dense_kitti_ep200 --tcp_port 18855 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/seg_dense_kitti_ep200.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_60_20_seg_dense_kitti_ep200 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_20.yaml --extra_tag seg_dense_kitti_ep200 --tcp_port 18855 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/seg_dense_kitti_ep200.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_60_30_seg_dense_kitti_ep200 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_30.yaml --extra_tag seg_dense_kitti_ep200 --tcp_port 18855 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/seg_dense_kitti_ep200.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_60_40_seg_dense_kitti_ep200 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_40.yaml --extra_tag seg_dense_kitti_ep200 --tcp_port 18855 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/seg_dense_kitti_ep200.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_60_50_seg_dense_kitti_ep200 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_50.yaml --extra_tag seg_dense_kitti_ep200 --tcp_port 18855 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/seg_dense_kitti_ep200.pth.tar



#(Pretrained on dense + semkitti: Lowest Priority)