
#seg_49 is from turing segcontrast_waymo10
#seg_plus_det_nusc_ep49 is from lovelace segcontrast_waymo10_lidar_aug_single_randh_det0p5w
#seg_plus_det0p8_ep49 is from narval /home/nisarbar/projects/rrg-swasland/nisarbar/DepthContrast/checkpoints/minkunet/minkunet_pretrain_segcontrast_waymo10_dethead_0p8w/pretrain_waymo

tools/scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 0,1 --tcp_port 19835 --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_100.yaml --extra_tag turing_segcontrast_car --pretrained_model /OpenPCDet/checkpoints/seg_ep49.pth.tar --test_start_epoch 20 > ./output/log/seg_car_30ep_1perc_waymo_$(date +%Y-%m-%d_%H:%M).out 2>&1
tools/scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 0,1 --tcp_port 19835 --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_100.yaml --extra_tag turing_segcontrast_plus_det_car --pretrained_model /OpenPCDet/checkpoints/seg_plus_det_ep49_t2.pth.tar --test_start_epoch 20 > ./output/log/segdet_car_30ep_1perc_waymo_$(date +%Y-%m-%d_%H:%M).out 2>&1
tools/scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 2,3 --tcp_port 19836 --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_100.yaml --extra_tag turing_scratch_car --test_start_epoch 20 > ./output/log/scratch_car_30ep_1perc_waymo_$(date +%Y-%m-%d_%H:%M).out 2>&1

tools/scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 0,1 --tcp_port 19835 --cfg_file tools/cfgs/waymo_models/pointrcnn_scene_sampled_100.yaml --extra_tag turing_pts_seg_car_ep30_t2 --pretrained_model /OpenPCDet/checkpoints/pts_seg_ep49_t2.pth.tar --test_start_epoch 20 --test_only > ./output/log/pts_seg_car_30ep_1perc_waymo_t2_$(date +%Y-%m-%d_%H:%M).out 2>&1
tools/scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 2,3 --tcp_port 19836 --cfg_file tools/cfgs/waymo_models/pointrcnn_scene_sampled_100.yaml --extra_tag turing_pts_seg_only_det_car_ep30 --pretrained_model /OpenPCDet/checkpoints/pts_seg_only_det_ep49.pth.tar --test_start_epoch 20 > ./output/log/pts_seg_only_det_car_30ep_1perc_waymo_$(date +%Y-%m-%d_%H:%M).out 2>&1

tools/scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 0,1 --tcp_port 19835 --cfg_file tools/cfgs/waymo_models/pointrcnn_scene_sampled_100.yaml --extra_tag turing_pts_seg_car_ep100_t2 --pretrained_model /OpenPCDet/checkpoints/pts_seg_ep49_t2.pth.tar --test_start_epoch 20 --test_only > ./output/log/pts_seg_car_30ep_1perc_waymo_t2_$(date +%Y-%m-%d_%H:%M).out 2>&1
tools/scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 2,3 --tcp_port 19836 --cfg_file tools/cfgs/waymo_models/pointrcnn_scene_sampled_100.yaml --extra_tag turing_pts_seg_only_det_car_ep100 --pretrained_model /OpenPCDet/checkpoints/pts_seg_only_det_ep49.pth.tar --test_start_epoch 20 > ./output/log/pts_seg_only_det_car_30ep_1perc_waymo_$(date +%Y-%m-%d_%H:%M).out 2>&1

# only car 30 ep 1% Waymo
# sbatch --time=3:00:00 --array=1-1%1 --job-name=segcar-30ep-scene100-pretrained_ep_200 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_100.yaml --tcp_port 17912 --extra_tag segcontrast_car_pretrained_ep199 --pretrained_model /OpenPCDet/checkpoints/seg_ep199.pth.tar --test_start_epoch 20
# sbatch --time=3:00:00 --array=1-1%1 --job-name=segdetcar-30ep-scene100-pretrained_ep_200 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_100.yaml --tcp_port 17913 --extra_tag segcontrast_only_det_car_pretrained_ep199 --pretrained_model /OpenPCDet/checkpoints/seg_only_det_ep199.pth.tar --test_start_epoch 20
# sbatch --time=3:00:00 --array=1-1%1 --job-name=seglidarplusdetcar-30ep-scene100-pretrained_ep_200 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_100.yaml --tcp_port 17914 --extra_tag segcontrast_lidarplusdet_car_pretrained_ep198 --pretrained_model /OpenPCDet/checkpoints/seg_lidar_plus_det_ep198.pth.tar --test_start_epoch 20

# only car 80 ep 1% Waymo
# sbatch --time=8:30:00 --array=1-3%1 --job-name=segcar-80ep-scene100-pretrained_ep_200 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_80ep_scene_sampled_100.yaml --tcp_port 17915 --extra_tag segcontrast_car_pretrained_ep199 --pretrained_model /OpenPCDet/checkpoints/seg_ep199.pth.tar --test_start_epoch 70
# sbatch --time=8:30:00 --array=1-3%1 --job-name=segdetcar-80ep-scene100-pretrained_ep_200 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_80ep_scene_sampled_100.yaml --tcp_port 17916 --extra_tag segcontrast_only_det_car_pretrained_ep199 --pretrained_model /OpenPCDet/checkpoints/seg_only_det_ep199.pth.tar --test_start_epoch 70
# sbatch --time=8:30:00 --array=1-3%1 --job-name=seglidarplusdetcar-80ep-scene100-pretrained_ep_200 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_80ep_scene_sampled_100.yaml --tcp_port 17917 --extra_tag segcontrast_lidarplusdet_car_pretrained_ep198 --pretrained_model /OpenPCDet/checkpoints/seg_lidar_plus_det_ep198.pth.tar --test_start_epoch 70
############################################################3
#only car frozen finetune-eval on 25% waymo val set left, eval on 5% val set done
# 	Eval on waymo all
# scratch car 30	last 5 #done
sbatch --time=4:00:00 --array=1-1%1 --job-name=waymo-scratchcar-30ep-test-last5 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100.yaml --tcp_port 17911 --extra_tag scratch_car_30ep --test_only --test_start_epoch 25 --test_sample_interval 2 --eval_tag val_50perc
# scratch car 40	40th epoch #done
sbatch --time=2:00:00 --array=1-1%1 --job-name=waymo-scratchcar-40ep-test-last tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100.yaml --tcp_port 17912 --extra_tag scratch_car_40ep --test_only --test_start_epoch 39 --test_sample_interval 2 --eval_tag val_50perc
# scratch car 80	80th epoch #done
sbatch --time=4:00:00 --array=1-1%1 --job-name=waymo-scratchcar-80ep-test-last tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100.yaml --tcp_port 17913 --extra_tag scratch_car_80ep --test_only --test_start_epoch 79 --test_sample_interval 2 --eval_tag val_50perc
# scratch car 110	last 10 #done took 3 hours 45 mins 
sbatch --time=8:00:00 --array=1-3%1 --job-name=waymo-scratchcar-110ep-test-last10 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100.yaml --tcp_port 17914 --extra_tag scratch_car_110ep --test_only --test_start_epoch 100 --test_sample_interval 2 --eval_tag val_50perc

# segcontrast car 30	last 5 #done
sbatch --time=8:00:00 --array=1-2%1 --job-name=waymo_segcar_frozen_fintune_10ep_30ep-testlast5 tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100.yaml --tcp_port 17915 --extra_tag segcontrast_car --num_epochs_2 30 --test_only --test_start_epoch 25 --test_sample_interval 2 --eval_tag val_50perc

# segcontrast car 80	78th epoch #done 
sbatch --time=3:00:00 --array=1-1%1 --job-name=waymo_segcar_frozen_fintune_30ep_80ep-test78ep tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100.yaml --tcp_port 17916 --extra_tag segcontrast_car --num_epochs_2 80 --test_only --ckpt_to_eval /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100/segcontrast_car_ep80/ckpt/checkpoint_epoch_78.pth --test_sample_interval 2 --eval_tag val_50perc

# ours car 30	29th epoch  #done
sbatch --time=3:00:00 --array=1-1%1 --job-name=waymo_seglidarplusdetcar_frozen_fintune_10ep_30ep-test29ep tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100.yaml --tcp_port 17917 --extra_tag segcontrast_lidarplusdet_car --num_epochs_2 30 --test_only --ckpt_to_eval /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100/segcontrast_lidarplusdet_car_ep30/ckpt/checkpoint_epoch_29.pth --test_sample_interval 2 --eval_tag val_50perc

##segcontrast wins
# ours car 80	71th epoch #done  --#TODO try 10ep_80ep and val last 10 on 50%
sbatch --time=3:00:00 --array=1-1%1 --job-name=waymo_seglidarplusdetcar_frozen_fintune_30ep_80ep-test71ep tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100.yaml --tcp_port 17918 --extra_tag segcontrast_lidarplusdet_car --num_epochs_2 80 --test_only --ckpt_to_eval /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100/segcontrast_lidarplusdet_car_ep80/ckpt/checkpoint_epoch_71.pth --test_sample_interval 2 --eval_tag val_50perc
#TODO - in progress
#sbatch --time=5:00:00 --array=1-1%1 --job-name=waymo_seglidarplusdetcar_frozen_10ep tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100.yaml --tcp_port 17917 --extra_tag segcontrast_lidarplusdet_car --pretrained_model_1 /OpenPCDet/checkpoints/seg_lidar_plus_det_ep198.pth.tar --num_epochs_1 10 --mode train_frozen
sbatch --time=5:00:00 --array=1-1%1 --job-name=waymo_seglidarplusdetcar_frozen_20ep tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100.yaml --tcp_port 17918 --extra_tag segcontrast_lidarplusdet_car --pretrained_model_1 /OpenPCDet/checkpoints/seg_lidar_plus_det_ep198.pth.tar --num_epochs_1 20 --mode train_frozen
#sbatch --time=5:00:00 --array=1-1%1 --job-name=waymo_segcar_frozen_10ep tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100.yaml --tcp_port 17919 --extra_tag segcontrast_car --pretrained_model_1 /OpenPCDet/checkpoints/seg_ep199.pth.tar --num_epochs_1 10 --mode train_frozen
#sbatch --time=5:00:00 --array=1-1%1 --job-name=waymo_segcar_frozen_20ep tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100.yaml --tcp_port 17920 --extra_tag segcontrast_car --pretrained_model_1 /OpenPCDet/checkpoints/seg_ep199.pth.tar --num_epochs_1 20 --mode train_frozen

sbatch --time=8:00:00 --array=1-4%1 --job-name=waymo_seglidarplusdetcar_frozen_fintune_10ep_80ep tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100.yaml --tcp_port 17921 --extra_tag segcontrast_lidarplusdet_car --pretrained_model_1 /OpenPCDet/checkpoints/seg_lidar_plus_det_ep198.pth.tar --num_epochs_1 10 --pretrained_model_2 /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100/segcontrast_lidarplusdet_car_ep10_frozen_bb/ckpt/checkpoint_epoch_10.pth --num_epochs_2 80 --test_start_epoch 70 --test_sample_interval 2 --eval_tag val_50perc --mode train_second
sbatch --time=8:00:00 --array=1-4%1 --job-name=waymo_seglidarplusdetcar_frozen_fintune_10ep_70ep tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100.yaml --tcp_port 17923 --extra_tag segcontrast_lidarplusdet_car --pretrained_model_1 /OpenPCDet/checkpoints/seg_lidar_plus_det_ep198.pth.tar --num_epochs_1 10 --pretrained_model_2 /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100/segcontrast_lidarplusdet_car_ep10_frozen_bb/ckpt/checkpoint_epoch_10.pth --num_epochs_2 70 --test_start_epoch 60 --test_sample_interval 2 --eval_tag val_50perc --mode train_second
sbatch --time=8:00:00 --dependency=afterok:28572916 --array=1-4%1 --job-name=waymo_seglidarplusdetcar_frozen_fintune_20ep_80ep tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100.yaml --tcp_port 17922 --extra_tag segcontrast_lidarplusdet_car --pretrained_model_1 /OpenPCDet/checkpoints/seg_lidar_plus_det_ep198.pth.tar --num_epochs_1 20 --pretrained_model_2 /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100/segcontrast_lidarplusdet_car_ep20_frozen_bb/ckpt/checkpoint_epoch_20.pth --num_epochs_2 80 --test_start_epoch 70 --test_sample_interval 2 --eval_tag val_50perc --mode train_second
sbatch --time=8:00:00 --dependency=afterok:28572916 --array=1-4%1 --job-name=waymo_seglidarplusdetcar_frozen_fintune_20ep_70ep tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100.yaml --tcp_port 17924 --extra_tag segcontrast_lidarplusdet_car --pretrained_model_1 /OpenPCDet/checkpoints/seg_lidar_plus_det_ep198.pth.tar --num_epochs_1 20 --pretrained_model_2 /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100/segcontrast_lidarplusdet_car_ep20_frozen_bb/ckpt/checkpoint_epoch_20.pth --num_epochs_2 70 --test_start_epoch 60 --test_sample_interval 2 --eval_tag val_50perc --mode train_second

#IN PROGRESS
#sbatch --time=8:00:00 --array=1-1%1 --job-name=waymo_seglidarplusdetcar_frozen_fintune_40ep_80ep tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100.yaml --tcp_port 17921 --extra_tag segcontrast_lidarplusdet_car --pretrained_model_1 /OpenPCDet/checkpoints/seg_lidar_plus_det_ep198.pth.tar --num_epochs_1 40 --pretrained_model_2 /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100/segcontrast_lidarplusdet_car_ep40_frozen_bb/ckpt/checkpoint_epoch_40.pth --num_epochs_2 80 --test_start_epoch 60 --test_sample_interval 2 --eval_tag val_50perc --mode test_only 
#sbatch --time=8:00:00 --array=1-1%1 --job-name=waymo_segcar_frozen_fintune_40ep_80ep tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100.yaml --tcp_port 17922 --extra_tag segcontrast_car --pretrained_model_1 /OpenPCDet/checkpoints/seg_ep199.pth.tar --num_epochs_1 40 --pretrained_model_2 /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100/segcontrast_car_ep40_frozen_bb/ckpt/checkpoint_epoch_40.pth --num_epochs_2 80 --test_start_epoch 60 --test_sample_interval 2 --eval_tag val_50perc --mode test_only 
#S4
sbatch --time=5:00:00 --array=1-1%1 --job-name=waymo_seglidarplusdetcar_frozen_fintune_50ep_80ep tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100.yaml --tcp_port 17923 --extra_tag segcontrast_lidarplusdet_car --pretrained_model_1 /OpenPCDet/checkpoints/seg_lidar_plus_det_ep198.pth.tar --num_epochs_1 50 --pretrained_model_2 /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100/segcontrast_lidarplusdet_car_ep50_frozen_bb/ckpt/checkpoint_epoch_50.pth --num_epochs_2 80 --test_start_epoch 60 --test_sample_interval 2 --eval_tag val_50perc --mode train_all 
#S5
sbatch --time=8:00:00 --array=1-1%1 --job-name=waymo_segcar_frozen_fintune_50ep_80ep tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100.yaml --tcp_port 17924 --extra_tag segcontrast_car --pretrained_model_1 /OpenPCDet/checkpoints/seg_ep199.pth.tar --num_epochs_1 50 --pretrained_model_2 /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100/segcontrast_car_ep50_frozen_bb/ckpt/checkpoint_epoch_50.pth --num_epochs_2 80 --test_start_epoch 60 --test_sample_interval 2 --eval_tag val_50perc --mode train_all 

#done
sbatch --time=8:00:00 --array=1-1%1 --job-name=waymo_seglidarplusdetcar_frozen_fintune_10ep_80ep tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100.yaml --tcp_port 17923 --extra_tag segcontrast_lidarplusdet_car --pretrained_model_1 /OpenPCDet/checkpoints/seg_lidar_plus_det_ep198.pth.tar --num_epochs_1 10 --pretrained_model_2 /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100/segcontrast_lidarplusdet_car_ep10_frozen_bb/ckpt/checkpoint_epoch_10.pth --num_epochs_2 80 --test_start_epoch 60 --test_sample_interval 2 --eval_tag val_50perc --mode test_only 
sbatch --time=8:00:00 --array=1-1%1 --job-name=waymo_seglidarplusdetcar_frozen_fintune_20ep_80ep tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100.yaml --tcp_port 17924 --extra_tag segcontrast_lidarplusdet_car --pretrained_model_1 /OpenPCDet/checkpoints/seg_lidar_plus_det_ep198.pth.tar --num_epochs_1 20 --pretrained_model_2 /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100/segcontrast_lidarplusdet_car_ep20_frozen_bb/ckpt/checkpoint_epoch_20.pth --num_epochs_2 80 --test_start_epoch 60 --test_sample_interval 2 --eval_tag val_50perc --mode test_only 
sbatch --time=8:00:00 --array=1-1%1 --job-name=waymo_seglidarplusdetcar_frozen_fintune_30ep_80ep tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100.yaml --tcp_port 17925 --extra_tag segcontrast_lidarplusdet_car --pretrained_model_1 /OpenPCDet/checkpoints/seg_lidar_plus_det_ep198.pth.tar --num_epochs_1 30 --pretrained_model_2 /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100/segcontrast_lidarplusdet_car_ep30_frozen_bb/ckpt/checkpoint_epoch_30.pth --num_epochs_2 80 --test_start_epoch 60 --test_sample_interval 2 --eval_tag val_50perc --mode test_only 

#S7-done recently
sbatch --time=11:00:00 --dependency=afterany:28784197 --array=1-1%1 --job-name=waymo_segcar_frozen_fintune_10ep_80ep tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100.yaml --tcp_port 17926 --extra_tag segcontrast_car --pretrained_model_1 /OpenPCDet/checkpoints/seg_ep199.pth.tar --num_epochs_1 10 --pretrained_model_2 /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100/segcontrast_car_ep10_frozen_bb/ckpt/checkpoint_epoch_10.pth --num_epochs_2 80 --test_start_epoch 60 --test_sample_interval 2 --eval_tag val_50perc --mode train_all 
#S8
sbatch --time=2:59:00  --array=1-1%1 --job-name=waymo_segcar_frozen_fintune_20ep_80ep tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100.yaml --tcp_port 17927 --extra_tag segcontrast_car --pretrained_model_1 /OpenPCDet/checkpoints/seg_ep199.pth.tar --num_epochs_1 20 --pretrained_model_2 /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100/segcontrast_car_ep20_frozen_bb/ckpt/checkpoint_epoch_20.pth --num_epochs_2 80 --test_start_epoch 60 --test_sample_interval 2 --eval_tag val_50perc --mode train_all 
#S2-done
sbatch --time=8:00:00 --array=1-1%1 --job-name=waymo_segcar_frozen_fintune_30ep_80ep tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100.yaml --tcp_port 17928 --extra_tag segcontrast_car --pretrained_model_1 /OpenPCDet/checkpoints/seg_ep199.pth.tar --num_epochs_1 30 --pretrained_model_2 /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100/segcontrast_car_ep30_frozen_bb/ckpt/checkpoint_epoch_30.pth --num_epochs_2 80 --test_start_epoch 60 --test_sample_interval 2 --eval_tag val_50perc --mode test_only 

# 	Eval on waymo 5%, all class experiments on all epochs
#TODO
# ep 29 vehicle, ep 18 ped, ep 19 cyclist --TODO val 50% -skip
sbatch --time=8:00:00 --array=1-3%1 --job-name=waymo-scratch-30ep-test-all-5perc-val tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --tcp_port 16911 --extra_tag scratch_30ep --num_epochs 30 --test_start_epoch 0 --test_sample_interval 20 --eval_tag val_5perc
#ep 26 cyclist, ep32 ped, ep38 vehicle --TODO val 50% -skip
sbatch --time=8:00:00 --array=1-3%1 --job-name=waymo-scratch-40ep-test-all-5perc-val tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --tcp_port 16912 --extra_tag scratch_40ep --num_epochs 40 --test_start_epoch 0 --test_sample_interval 20 --eval_tag val_5perc
#done
#ep 69 veh, ep54 cyc, ep 69 ped --TODO val 50%
sbatch --time=8:00:00 --array=1-2%1 --job-name=waymo-scratch-80ep-test-all-5perc-val tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --tcp_port 16913 --extra_tag scratch_80ep --test_only --test_start_epoch 0 --test_sample_interval 20 --eval_tag val_5perc

sbatch --time=2:00:00 --array=1-1%1 --job-name=waymo-scratch-80ep-test-veh-ped-69ep tools/scripts/submit_ddp_${CLUSTER_NAME}.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --tcp_port 16923 --extra_tag scratch_80ep  --test_only --ckpt_to_eval /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class/scratch_80ep/ckpt/checkpoint_epoch_69.pth --test_sample_interval 2 --eval_tag val_50perc
sbatch --time=2:00:00 --array=1-1%1 --job-name=waymo-scratch-80ep-test-cyc-54ep tools/scripts/submit_ddp_${CLUSTER_NAME}.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --tcp_port 16924 --extra_tag scratch_80ep  --test_only --ckpt_to_eval /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class/scratch_80ep/ckpt/checkpoint_epoch_54.pth --test_sample_interval 2 --eval_tag val_50perc

#ep 104 veh, ep58 ped, ep63 cyc --TODO val 50%
sbatch --time=8:00:00 --array=1-2%1 --job-name=waymo-scratch-110ep-test-all-5perc-val tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --tcp_port 16914 --extra_tag scratch_110ep --test_only --test_start_epoch 0 --test_sample_interval 20 --eval_tag val_5perc

sbatch --time=2:00:00 --array=1-1%1 --job-name=waymo-scratch-110ep-test-veh-104ep tools/scripts/submit_ddp_${CLUSTER_NAME}.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --tcp_port 16925 --extra_tag scratch_110ep  --test_only --ckpt_to_eval /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class/scratch_110ep/ckpt/checkpoint_epoch_104.pth --test_sample_interval 2 --eval_tag val_50perc
sbatch --time=2:00:00 --array=1-1%1 --job-name=waymo-scratch-110ep-test-ped-58ep tools/scripts/submit_ddp_${CLUSTER_NAME}.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --tcp_port 16926 --extra_tag scratch_110ep  --test_only --ckpt_to_eval /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class/scratch_110ep/ckpt/checkpoint_epoch_58.pth --test_sample_interval 2 --eval_tag val_50perc
sbatch --time=2:00:00 --array=1-1%1 --job-name=waymo-scratch-110ep-test-cyc-63ep tools/scripts/submit_ddp_${CLUSTER_NAME}.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --tcp_port 16927 --extra_tag scratch_110ep  --test_only --ckpt_to_eval /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class/scratch_110ep/ckpt/checkpoint_epoch_63.pth --test_sample_interval 2 --eval_tag val_50perc


#done
#segcontrast wins
sbatch --time=8:00:00 --array=1-1%1 --job-name=waymo_seg_frozen_fintune_10ep_30ep-test-all-5perc-val tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --tcp_port 16915 --extra_tag segcontrast --num_epochs_2 30 --test_only --test_start_epoch 0 --test_sample_interval 20 --eval_tag val_5perc
sbatch --time=8:00:00 --array=1-1%1 --job-name=waymo_seglidarplusdet_frozen_fintune_10ep_30ep-test-all-5perc-val tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --tcp_port 16916 --extra_tag segcontrast_lidarplusdet --num_epochs_2 30 --test_only --test_start_epoch 0 --test_sample_interval 20 --eval_tag val_5perc

#segcontrast wins on ped and cyc  --#TODO try 10ep_80ep and val all - 5perc -in progress see below
sbatch --time=8:00:00 --array=1-2%1 --job-name=waymo_seg_frozen_fintune_30ep_80ep-test-all-5perc-val tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --tcp_port 16917 --extra_tag segcontrast --num_epochs_2 80 --test_only --test_start_epoch 0 --test_sample_interval 20 --eval_tag val_5perc
#seg: 56 veh, 51 cyc, 31 ped
#seg+lidar: 57 veh, 53 cyc, 38 ped
sbatch --time=2:00:00 --array=1-1%1 --job-name=waymo_seglidarplusdet_frozen_fintune_30ep_80ep-test57ep-veh tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --tcp_port 17918 --extra_tag segcontrast_lidarplusdet --num_epochs_1 30 --num_epochs_2 80 --test_only --ckpt_to_eval /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class/segcontrast_lidarplusdet_ep30_ep80/ckpt/checkpoint_epoch_57.pth --test_sample_interval 2 --eval_tag val_50perc
sbatch --time=2:00:00 --array=1-1%1 --job-name=waymo_seglidarplusdet_frozen_fintune_30ep_80ep-test53ep-cyc tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --tcp_port 17919 --extra_tag segcontrast_lidarplusdet --num_epochs_1 30 --num_epochs_2 80 --test_only --ckpt_to_eval /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class/segcontrast_lidarplusdet_ep30_ep80/ckpt/checkpoint_epoch_53.pth --test_sample_interval 2 --eval_tag val_50perc
sbatch --time=2:00:00 --array=1-1%1 --job-name=waymo_seglidarplusdet_frozen_fintune_30ep_80ep-test38ep-ped tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --tcp_port 17920 --extra_tag segcontrast_lidarplusdet --num_epochs_1 30 --num_epochs_2 80 --test_only --ckpt_to_eval /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class/segcontrast_lidarplusdet_ep30_ep80/ckpt/checkpoint_epoch_38.pth --test_sample_interval 2 --eval_tag val_50perc

sbatch --time=2:00:00 --array=1-1%1 --job-name=waymo_seg_frozen_fintune_30ep_80ep-test56ep-veh tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --tcp_port 17921 --extra_tag segcontrast --num_epochs_1 30 --num_epochs_2 80 --test_only --ckpt_to_eval /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class/segcontrast_ep30_ep80/ckpt/checkpoint_epoch_56.pth --test_sample_interval 2 --eval_tag val_50perc
sbatch --time=2:00:00 --array=1-1%1 --job-name=waymo_seg_frozen_fintune_30ep_80ep-test51ep-cyc tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --tcp_port 17922 --extra_tag segcontrast --num_epochs_1 30 --num_epochs_2 80 --test_only --ckpt_to_eval /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class/segcontrast_ep30_ep80/ckpt/checkpoint_epoch_51.pth --test_sample_interval 2 --eval_tag val_50perc
sbatch --time=2:00:00 --array=1-1%1 --job-name=waymo_seg_frozen_fintune_30ep_80ep-test31ep-ped tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --tcp_port 17923 --extra_tag segcontrast --num_epochs_1 30 --num_epochs_2 80 --test_only --ckpt_to_eval /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class/segcontrast_ep30_ep80/ckpt/checkpoint_epoch_31.pth --test_sample_interval 2 --eval_tag val_50perc

sbatch --time=8:00:00 --array=1-2%1 --job-name=waymo_seglidarplusdet_frozen_fintune_30ep_80ep-test-all-5perc-val tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --tcp_port 16918 --extra_tag segcontrast_lidarplusdet --num_epochs_2 80 --test_only --test_start_epoch 0 --test_sample_interval 20 --eval_tag val_5perc

#TODO -in progress
# sbatch --time=5:00:00 --array=1-1%1 --job-name=waymo_seglidarplusdet_frozen_10ep tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --tcp_port 16917 --extra_tag segcontrast_lidarplusdet --pretrained_model_1 /OpenPCDet/checkpoints/seg_lidar_plus_det_ep198.pth.tar --num_epochs_1 10 --mode train_frozen
# sbatch --time=5:00:00 --array=1-1%1 --job-name=waymo_seglidarplusdet_frozen_20ep tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --tcp_port 16918 --extra_tag segcontrast_lidarplusdet --pretrained_model_1 /OpenPCDet/checkpoints/seg_lidar_plus_det_ep198.pth.tar --num_epochs_1 20 --mode train_frozen
# sbatch --time=5:00:00 --array=1-1%1 --job-name=waymo_seg_frozen_10ep tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --tcp_port 16919 --extra_tag segcontrast --pretrained_model_1 /OpenPCDet/checkpoints/seg_ep199.pth.tar --num_epochs_1 10 --mode train_frozen
# sbatch --time=5:00:00 --array=1-1%1 --job-name=waymo_seg_frozen_20ep tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --tcp_port 16920 --extra_tag segcontrast --pretrained_model_1 /OpenPCDet/checkpoints/seg_ep199.pth.tar --num_epochs_1 20 --mode train_frozen

#sbatch --time=8:00:00 --array=1-2%1 --job-name=waymo_seg_frozen_fintune_10ep_80ep-test-all-5perc-val tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --tcp_port 16920 --extra_tag segcontrast --pretrained_model_1 /OpenPCDet/checkpoints/seg_ep199.pth.tar --num_epochs_1 10 --pretrained_model_2 /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class/segcontrast_ep10_frozen_bb/ckpt/checkpoint_epoch_10.pth --num_epochs_2 80 --test_start_epoch 0 --test_sample_interval 20 --eval_tag val_5perc --mode train_second
# sbatch --time=8:00:00 --array=1-4%1 --job-name=waymo_seg_frozen_fintune_10ep_70ep-test-all-5perc-val tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --tcp_port 16921 --extra_tag segcontrast --pretrained_model_1 /OpenPCDet/checkpoints/seg_ep199.pth.tar --num_epochs_1 10 --pretrained_model_2 /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class/segcontrast_ep10_frozen_bb/ckpt/checkpoint_epoch_10.pth --num_epochs_2 70 --test_start_epoch 0 --test_sample_interval 20 --eval_tag val_5perc
#sbatch --time=8:00:00 --array=1-1%1 --job-name=waymo_seglidarplusdet_frozen_fintune_10ep_80ep-test-all-5perc-val tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --tcp_port 16922 --extra_tag segcontrast_lidarplusdet --pretrained_model_1 /OpenPCDet/checkpoints/seg_lidar_plus_det_ep198.pth.tar --num_epochs_1 10 --pretrained_model_2 /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class/segcontrast_lidarplusdet_ep10_frozen_bb/ckpt/checkpoint_epoch_10.pth --num_epochs_2 80 --test_start_epoch 0 --test_sample_interval 20 --eval_tag val_5perc --mode train_second
#sbatch --time=8:00:00 --array=1-1%1 --job-name=waymo_seglidarplusdet_frozen_fintune_10ep_70ep-test-all-5perc-val tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --tcp_port 16923 --extra_tag segcontrast_lidarplusdet --pretrained_model_1 /OpenPCDet/checkpoints/seg_lidar_plus_det_ep198.pth.tar --num_epochs_1 10 --pretrained_model_2 /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class/segcontrast_lidarplusdet_ep10_frozen_bb/ckpt/checkpoint_epoch_10.pth --num_epochs_2 70 --test_start_epoch 0 --test_sample_interval 20 --eval_tag val_5perc --mode train_second
#sbatch --time=8:00:00 --array=1-2%1 --job-name=waymo_seglidarplusdet_frozen_fintune_20ep_80ep-test-all-5perc-val tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --tcp_port 16924 --extra_tag segcontrast_lidarplusdet --pretrained_model_1 /OpenPCDet/checkpoints/seg_lidar_plus_det_ep198.pth.tar --num_epochs_1 20 --pretrained_model_2 /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class/segcontrast_lidarplusdet_ep20_frozen_bb/ckpt/checkpoint_epoch_20.pth --num_epochs_2 80 --test_start_epoch 0 --test_sample_interval 20 --eval_tag val_5perc --mode train_second
#sbatch --time=8:00:00 --array=1-2%1 --job-name=waymo_seglidarplusdet_frozen_fintune_20ep_70ep-test-all-5perc-val tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --tcp_port 16925 --extra_tag segcontrast_lidarplusdet --pretrained_model_1 /OpenPCDet/checkpoints/seg_lidar_plus_det_ep198.pth.tar --num_epochs_1 20 --pretrained_model_2 /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class/segcontrast_lidarplusdet_ep20_frozen_bb/ckpt/checkpoint_epoch_20.pth --num_epochs_2 70 --test_start_epoch 0 --test_sample_interval 20 --eval_tag val_5perc --mode train_second
#IN PROGRESS
#sbatch --time=8:00:00 --dependency=afterany:28624365 --array=1-2%1 --job-name=waymo_seglidarplusdet_frozen_fintune_40ep_80ep-test-all-5perc-val tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --tcp_port 16924 --extra_tag segcontrast_lidarplusdet --pretrained_model_1 /OpenPCDet/checkpoints/seg_lidar_plus_det_ep198.pth.tar --num_epochs_1 40 --pretrained_model_2 /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class/segcontrast_lidarplusdet_ep40_frozen_bb/ckpt/checkpoint_epoch_40.pth --num_epochs_2 80 --test_start_epoch 0 --test_sample_interval 20 --eval_tag val_5perc --mode train_all
#not done
#S1-done
sbatch --time=8:00:00 --array=1-2%1 --job-name=waymo_seglidarplusdet_frozen_fintune_50ep_80ep-test-all-5perc-val tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --tcp_port 16925 --extra_tag segcontrast_lidarplusdet --pretrained_model_1 /OpenPCDet/checkpoints/seg_lidar_plus_det_ep198.pth.tar --num_epochs_1 50 --pretrained_model_2 /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class/segcontrast_lidarplusdet_ep50_frozen_bb/ckpt/checkpoint_epoch_50.pth --num_epochs_2 80 --test_start_epoch 0 --test_sample_interval 20 --eval_tag val_5perc --mode train_all
#S6-done-recently
sbatch --time=8:00:00 --array=1-3%1 --job-name=t2_waymo_seglidarplusdet_frozen_fintune_50ep_80ep-test-all-5perc-val tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --tcp_port 16926 --extra_tag segcontrast_lidarplusdet_t2 --pretrained_model_1 /OpenPCDet/checkpoints/seg_lidar_plus_det_ep198.pth.tar --num_epochs_1 50 --pretrained_model_2 /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class/segcontrast_lidarplusdet_ep50_frozen_bb/ckpt/checkpoint_epoch_50.pth --num_epochs_2 80 --test_start_epoch 0 --test_sample_interval 20 --eval_tag val_5perc --mode train_all

#sbatch --time=8:00:00 --dependency=afterany:28624370 --array=1-3%1 --job-name=waymo_seg_frozen_fintune_40ep_80ep-test-all-5perc-val tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --tcp_port 16926 --extra_tag segcontrast --pretrained_model_1 /OpenPCDet/checkpoints/seg_ep199.pth.tar --num_epochs_1 40 --pretrained_model_2 /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class/segcontrast_ep40_frozen_bb/ckpt/checkpoint_epoch_40.pth --num_epochs_2 80 --test_start_epoch 0 --test_sample_interval 20 --eval_tag val_5perc --mode train_all
#sbatch --time=8:00:00 --dependency=afterany:28624371 --array=1-3%1 --job-name=waymo_seg_frozen_fintune_50ep_80ep-test-all-5perc-val tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --tcp_port 16927 --extra_tag segcontrast --pretrained_model_1 /OpenPCDet/checkpoints/seg_ep199.pth.tar --num_epochs_1 50 --pretrained_model_2 /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class/segcontrast_ep50_frozen_bb/ckpt/checkpoint_epoch_50.pth --num_epochs_2 80 --test_start_epoch 0 --test_sample_interval 20 --eval_tag val_5perc --mode train_all
#S3 
sbatch --time=10:00:00 --array=1-1%1 --job-name=waymo_seglidarplusdet_frozen_fintune_60ep_80ep-test-all-5perc-val tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --tcp_port 16924 --extra_tag segcontrast_lidarplusdet --pretrained_model_1 /OpenPCDet/checkpoints/seg_lidar_plus_det_ep198.pth.tar --num_epochs_1 60 --pretrained_model_2 /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class/segcontrast_lidarplusdet_ep60_frozen_bb/ckpt/checkpoint_epoch_60.pth --num_epochs_2 80 --test_start_epoch 0 --test_sample_interval 20 --eval_tag val_5perc --mode train_all
#S9
sbatch --time=8:00:00 --array=1-4%1 --job-name=waymo_seg_frozen_fintune_60ep_80ep-test-all-5perc-val tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_waymo.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --tcp_port 16925 --extra_tag segcontrast --pretrained_model_1 /OpenPCDet/checkpoints/seg_ep199.pth.tar --num_epochs_1 60 --pretrained_model_2 /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class/segcontrast_ep60_frozen_bb/ckpt/checkpoint_epoch_60.pth --num_epochs_2 80 --test_start_epoch 0 --test_sample_interval 20 --eval_tag val_5perc --mode train_all


#done
# lower lr bb, segcontrast only car 30 epochs
sbatch --time=8:00:00 --array=1-1%1 --job-name=waymo-segcar-30ep-lrbb-0p003 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100.yaml --tcp_port 16919 --extra_tag segcontrast_car_lrbb0p003_30ep --lr_bb 0.003 --num_epochs 30 --pretrained_model /OpenPCDet/checkpoints/seg_ep199.pth.tar --test_start_epoch 25 --test_sample_interval 2 --eval_tag val_50perc
sbatch --time=8:00:00 --array=1-1%1 --job-name=waymo-segcar-30ep-lrbb-0p0006 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100.yaml --tcp_port 16920 --extra_tag segcontrast_car_lrbb0p0006_30ep --lr_bb 0.0006 --num_epochs 30 --pretrained_model /OpenPCDet/checkpoints/seg_ep199.pth.tar --test_start_epoch 25 --test_sample_interval 2 --eval_tag val_50perc
sbatch --time=8:00:00 --array=1-1%1 --job-name=waymo-segcar-30ep-lrbb-0p001 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100.yaml --tcp_port 16921 --extra_tag segcontrast_car_lrbb0p001_30ep --lr_bb 0.001 --num_epochs 30 --pretrained_model /OpenPCDet/checkpoints/seg_ep199.pth.tar --test_start_epoch 25 --test_sample_interval 2 --eval_tag val_50perc
sbatch --time=8:00:00 --array=1-1%1 --job-name=waymo-segcar-40ep-lrbb-0p001 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100.yaml --tcp_port 15922 --extra_tag segcontrast_car_lrbb0p001_40ep --lr_bb 0.001 --num_epochs 40 --pretrained_model /OpenPCDet/checkpoints/seg_ep199.pth.tar --test_start_epoch 25 --test_sample_interval 2 --eval_tag val_50perc













# sbatch --time=8:00:00 --array=1-1%1 --job-name=waymo_segcar_frozen_fintune_10ep_30ep tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100.yaml --tcp_port 17914 --extra_tag segcontrast_car --pretrained_model_1 /OpenPCDet/checkpoints/seg_ep199.pth.tar --num_epochs_1 10 --pretrained_model_2 /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100/segcontrast_car_ep10_frozen_bb/ckpt/checkpoint_epoch_10.pth --num_epochs_2 30 --test_only
# sbatch --time=8:00:00 --array=1-1%1 --job-name=waymo_seglidarplusdetcar_frozen_fintune_10ep_30ep tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100.yaml --tcp_port 17915 --extra_tag segcontrast_lidarplusdet_car --pretrained_model_1 /OpenPCDet/checkpoints/seg_lidar_plus_det_ep198.pth.tar --num_epochs_1 10 --pretrained_model_2 /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100/segcontrast_lidarplusdet_car_ep10_frozen_bb/ckpt/checkpoint_epoch_10.pth --num_epochs_2 30 --test_only
sbatch --time=8:00:00 --array=1-4%1 --job-name=waymo_segcar_frozen_fintune_30ep_80ep tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100.yaml --tcp_port 17916 --extra_tag segcontrast_car --pretrained_model_1 /OpenPCDet/checkpoints/seg_ep199.pth.tar --num_epochs_1 30 --pretrained_model_2 /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100/segcontrast_car_ep30_frozen_bb/ckpt/checkpoint_epoch_30.pth --num_epochs_2 80 --test_only
sbatch --time=8:00:00 --array=1-4%1 --job-name=waymo_seglidarplusdetcar_frozen_fintune_30ep_80ep tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100.yaml --tcp_port 17917 --extra_tag segcontrast_lidarplusdet_car --pretrained_model_1 /OpenPCDet/checkpoints/seg_lidar_plus_det_ep198.pth.tar --num_epochs_1 30 --pretrained_model_2 /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100/segcontrast_lidarplusdet_car_ep30_frozen_bb/ckpt/checkpoint_epoch_30.pth --num_epochs_2 80 --test_only

sbatch --time=8:00:00 --array=1-3%1 --job-name=waymo-scratchcar-80ep tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100.yaml --tcp_port 17910 --extra_tag scratch_car_80ep --num_epochs 80 --test_start_epoch 70
sbatch --time=8:00:00 --array=1-3%1 --job-name=waymo-scratchcar-110ep tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100.yaml --tcp_port 17912 --extra_tag scratch_car_110ep --num_epochs 110 --test_start_epoch 100

# test only on all waymo last 5 epochs
sbatch --time=8:00:00 --array=1-1%1 --job-name=waymo-scratchcar-30ep tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100.yaml --tcp_port 17911 --extra_tag scratch_car_30ep --num_epochs 30 --test_start_epoch 20
sbatch --time=8:00:00 --array=1-1%1 --job-name=waymo-scratchcar-40ep tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100.yaml --tcp_port 17913 --extra_tag scratch_car_40ep --num_epochs 40 --test_start_epoch 30

#all class frozen/finetune-eval on 25% waymo val set left, eval on 5% val set done
# here seg works better than ours
# sbatch --time=8:00:00 --array=1-1%1 --job-name=waymo_seg_frozen_fintune_10ep_30ep tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_eval_all_epochs.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --tcp_port 16914 --extra_tag segcontrast --pretrained_model_1 /OpenPCDet/checkpoints/seg_ep199.pth.tar --num_epochs_1 10 --pretrained_model_2 /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class/segcontrast_ep10_frozen_bb/ckpt/checkpoint_epoch_10.pth --num_epochs_2 30 --test_only
# sbatch --time=8:00:00 --array=1-1%1 --job-name=waymo_seglidarplusdet_frozen_fintune_10ep_30ep tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_eval_all_epochs.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --tcp_port 16915 --extra_tag segcontrast_lidarplusdet --pretrained_model_1 /OpenPCDet/checkpoints/seg_lidar_plus_det_ep198.pth.tar --num_epochs_1 10 --pretrained_model_2 /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class/segcontrast_lidarplusdet_ep10_frozen_bb/ckpt/checkpoint_epoch_10.pth --num_epochs_2 30 --test_only
sbatch --time=8:00:00 --array=1-4%1 --job-name=waymo_seg_frozen_fintune_30ep_80ep tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_eval_all_epochs.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --tcp_port 16916 --extra_tag segcontrast --pretrained_model_1 /OpenPCDet/checkpoints/seg_ep199.pth.tar --num_epochs_1 30 --pretrained_model_2 /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class/segcontrast_ep30_frozen_bb/ckpt/checkpoint_epoch_30.pth --num_epochs_2 80 --test_only
sbatch --time=8:00:00 --array=1-4%1 --job-name=waymo_seglidarplusdet_frozen_fintune_30ep_80ep tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_eval_all_epochs.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --tcp_port 16917 --extra_tag segcontrast_lidarplusdet --pretrained_model_1 /OpenPCDet/checkpoints/seg_lidar_plus_det_ep198.pth.tar --num_epochs_1 30 --pretrained_model_2 /OpenPCDet/output/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class/segcontrast_lidarplusdet_ep30_frozen_bb/ckpt/checkpoint_epoch_30.pth --num_epochs_2 80 --test_only

sbatch --time=8:00:00 --array=1-4%1 --job-name=waymo-scratch-80ep tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --tcp_port 16918 --extra_tag scratch_80ep --num_epochs 80 --test_start_epoch 0
sbatch --time=8:00:00 --array=1-6%1 --job-name=waymo-scratch-110ep tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_scene_sampled_100_all_class.yaml --tcp_port 16919 --extra_tag scratch_110ep --num_epochs 110 --test_start_epoch 0


#only car frozen finetune NuSC-done
# sbatch --time=8:00:00 --array=1-1%1 --job-name=nusc_segcar_frozen_fintune_10ep_30ep tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_1sweeps_sampled_20.yaml --tcp_port 18914 --extra_tag segcontrast_car --pretrained_model_1 /OpenPCDet/checkpoints/seg_ep199.pth.tar --num_epochs_1 10 --pretrained_model_2 /OpenPCDet/output/nuscenes_models/pointrcnn_minkunet_1sweeps_sampled_20/segcontrast_car_ep10_frozen_bb/ckpt/checkpoint_epoch_10.pth --num_epochs_2 30
# sbatch --time=8:00:00 --array=1-1%1 --job-name=nusc_seglidarplusdetcar_frozen_fintune_10ep_30ep tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_1sweeps_sampled_20.yaml --tcp_port 18915 --extra_tag segcontrast_lidarplusdet_car --pretrained_model_1 /OpenPCDet/checkpoints/seg_lidar_plus_det_ep198.pth.tar --num_epochs_1 10 --pretrained_model_2 /OpenPCDet/output/nuscenes_models/pointrcnn_minkunet_1sweeps_sampled_20/segcontrast_lidarplusdet_car_ep10_frozen_bb/ckpt/checkpoint_epoch_10.pth --num_epochs_2 30
# sbatch --time=8:00:00 --array=1-2%1 --job-name=nusc_segcar_frozen_fintune_30ep_80ep tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_1sweeps_sampled_20.yaml --tcp_port 18916 --extra_tag segcontrast_car --pretrained_model_1 /OpenPCDet/checkpoints/seg_ep199.pth.tar --num_epochs_1 30 --pretrained_model_2 /OpenPCDet/output/nuscenes_models/pointrcnn_minkunet_1sweeps_sampled_20/segcontrast_car_ep30_frozen_bb/ckpt/checkpoint_epoch_30.pth --num_epochs_2 80
# sbatch --time=8:00:00 --array=1-2%1 --job-name=nusc_seglidarplusdetcar_frozen_fintune_30ep_80ep tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_1sweeps_sampled_20.yaml --tcp_port 18917 --extra_tag segcontrast_lidarplusdet_car --pretrained_model_1 /OpenPCDet/checkpoints/seg_lidar_plus_det_ep198.pth.tar --num_epochs_1 30 --pretrained_model_2 /OpenPCDet/output/nuscenes_models/pointrcnn_minkunet_1sweeps_sampled_20/segcontrast_lidarplusdet_car_ep30_frozen_bb/ckpt/checkpoint_epoch_30.pth --num_epochs_2 80

# sbatch --time=8:00:00 --array=1-3%1 --job-name=nusc-scratchcar-80ep tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_1sweeps_sampled_20.yaml --tcp_port 16910 --extra_tag scratch_car_80ep --num_epochs 80 --test_start_epoch 70
# sbatch --time=8:00:00 --array=1-3%1 --job-name=nusc-scratchcar-110ep tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_1sweeps_sampled_20.yaml --tcp_port 16912 --extra_tag scratch_car_110ep --num_epochs 110 --test_start_epoch 100
# sbatch --time=8:00:00 --array=1-1%1 --job-name=nusc-scratchcar-30ep tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_1sweeps_sampled_20.yaml --tcp_port 16911 --extra_tag scratch_car_30ep --num_epochs 30 --test_start_epoch 20
# sbatch --time=8:00:00 --array=1-1%1 --job-name=nusc-scratchcar-40ep tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_1sweeps_sampled_20.yaml --tcp_port 16913 --extra_tag scratch_car_40ep --num_epochs 40 --test_start_epoch 30

#all class frozen/finetune NuSC-left-evall all epochs also left
# sbatch --time=8:00:00 --array=1-1%1 --dependency=afterok:28115552 --job-name=nusc_seg_frozen_fintune_10ep_30ep tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_eval_all_epochs.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_1sweeps_sampled_20_all_class.yaml --tcp_port 19914 --extra_tag segcontrast --pretrained_model_1 /OpenPCDet/checkpoints/seg_ep199.pth.tar --num_epochs_1 10 --pretrained_model_2 /OpenPCDet/output/nuscenes_models/pointrcnn_minkunet_1sweeps_sampled_20_all_class/segcontrast_ep10_frozen_bb/ckpt/checkpoint_epoch_10.pth --num_epochs_2 30 --test_only
# sbatch --time=8:00:00 --array=1-1%1 --dependency=afterok:28115553 --job-name=nusc_seglidarplusdet_frozen_fintune_10ep_30ep tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_eval_all_epochs.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_1sweeps_sampled_20_all_class.yaml --tcp_port 19915 --extra_tag segcontrast_lidarplusdet --pretrained_model_1 /OpenPCDet/checkpoints/seg_lidar_plus_det_ep198.pth.tar --num_epochs_1 10 --pretrained_model_2 /OpenPCDet/output/nuscenes_models/pointrcnn_minkunet_1sweeps_sampled_20_all_class/segcontrast_lidarplusdet_ep10_frozen_bb/ckpt/checkpoint_epoch_10.pth --num_epochs_2 30 --test_only
#done
sbatch --time=8:00:00 --array=1-3%1 --job-name=nusc_seg_frozen_fintune_30ep_80ep tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_eval_all_epochs.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_1sweeps_sampled_20_all_class.yaml --tcp_port 19916 --extra_tag segcontrast --pretrained_model_1 /OpenPCDet/checkpoints/seg_ep199.pth.tar --num_epochs_1 30 --pretrained_model_2 /OpenPCDet/output/nuscenes_models/pointrcnn_minkunet_1sweeps_sampled_20_all_class/segcontrast_ep30_frozen_bb/ckpt/checkpoint_epoch_30.pth --num_epochs_2 80 --test_only
sbatch --time=8:00:00 --array=1-3%1 --job-name=nusc_seglidarplusdet_frozen_fintune_30ep_80ep tools/scripts/submit_ddp_${CLUSTER_NAME}_frozen_eval_all_epochs.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_1sweeps_sampled_20_all_class.yaml --tcp_port 19917 --extra_tag segcontrast_lidarplusdet --pretrained_model_1 /OpenPCDet/checkpoints/seg_lidar_plus_det_ep198.pth.tar --num_epochs_1 30 --pretrained_model_2 /OpenPCDet/output/nuscenes_models/pointrcnn_minkunet_1sweeps_sampled_20_all_class/segcontrast_lidarplusdet_ep30_frozen_bb/ckpt/checkpoint_epoch_30.pth --num_epochs_2 80 --test_only
#TODO -in progress
sbatch --time=8:00:00 --array=1-5%1 --job-name=nusc-scratch-80ep tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_1sweeps_sampled_20_all_class.yaml --tcp_port 19910 --extra_tag scratch_80ep --num_epochs 80 --test_start_epoch 0
# sbatch --time=8:00:00 --array=1-5%1 --job-name=nusc-scratch-110ep tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_1sweeps_sampled_20_all_class.yaml --tcp_port 19912 --extra_tag scratch_110ep --num_epochs 110 --test_start_epoch 0
# sbatch --time=8:00:00 --array=1-5%1 --job-name=nusc-scratch-40ep tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_1sweeps_sampled_20_all_class.yaml --tcp_port 19918 --extra_tag scratch_40ep --num_epochs 40 --test_start_epoch 0

# # done
# sbatch --time=8:00:00 --array=1-5%1 --job-name=nusc-scratch-30ep tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_1sweeps_sampled_20_all_class.yaml --tcp_port 19913 --extra_tag scratch_30ep --num_epochs 30 --test_start_epoch 0

# # only car class 200 epochs 1% Waymo
# sbatch --time=8:00:00 --array=1-3%1 --job-name=segcar-200ep-scene100-pretrained_ep_200 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_200ep_scene_sampled_100.yaml --tcp_port 17915 --extra_tag segcontrast_car_pretrained_ep199 --pretrained_model /OpenPCDet/checkpoints/seg_ep199.pth.tar --test_start_epoch 190
# sbatch --time=8:00:00 --array=1-3%1 --job-name=segdetcar-200ep-scene100-pretrained_ep_200 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_200ep_scene_sampled_100.yaml --tcp_port 17916 --extra_tag segcontrast_only_det_car_pretrained_ep199 --pretrained_model /OpenPCDet/checkpoints/seg_only_det_ep199.pth.tar --test_start_epoch 190
# sbatch --time=8:00:00 --array=1-3%1 --job-name=seglidarplusdetcar-200ep-scene100-pretrained_ep_200 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_200ep_scene_sampled_100.yaml --tcp_port 17917 --extra_tag segcontrast_lidarplusdet_car_pretrained_ep198 --pretrained_model /OpenPCDet/checkpoints/seg_lidar_plus_det_ep198.pth.tar --test_start_epoch 190
# sbatch --time=8:00:00 --array=1-3%1 --job-name=car-scratch-200ep-scene100 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_200ep_scene_sampled_100.yaml --tcp_port 17910 --extra_tag scratch_car --test_start_epoch 190

# all class 80 epochs 1% Waymo
# sbatch --time=8:00:00 --array=1-3%1 --job-name=seg-80ep-scene100-pretrained_ep_200 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_80ep_scene_sampled_100_all_class.yaml --tcp_port 17918 --extra_tag segcontrast_pretrained_ep199 --pretrained_model /OpenPCDet/checkpoints/seg_ep199.pth.tar --test_start_epoch 0
# sbatch --time=8:00:00 --array=1-3%1 --job-name=segdet-80ep-scene100-pretrained_ep_200 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_80ep_scene_sampled_100_all_class.yaml --tcp_port 17919 --extra_tag segcontrast_only_det_pretrained_ep199 --pretrained_model /OpenPCDet/checkpoints/seg_only_det_ep199.pth.tar --test_start_epoch 0
# sbatch --time=8:00:00 --array=1-3%1 --job-name=seglidarplusdet-80ep-scene100-pretrained_ep_200 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_80ep_scene_sampled_100_all_class.yaml --tcp_port 17920 --extra_tag segcontrast_lidarplusdet_pretrained_ep198 --pretrained_model /OpenPCDet/checkpoints/seg_lidar_plus_det_ep198.pth.tar --test_start_epoch 0
# sbatch --time=8:00:00 --array=1-3%1 --job-name=scratch-80ep-scene100 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_80ep_scene_sampled_100_all_class.yaml --tcp_port 17921 --extra_tag scratch --test_start_epoch 0

# all class 80 epochs 5% Nuscenes
#sbatch --time=8:00:00 --array=1-3%1 --job-name=nusc-seg-80ep-5perc-pretrained_ep_200 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_80ep_1sweeps_sampled_20_all_class.yaml --tcp_port 18918 --extra_tag segcontrast_pretrained_ep199 --pretrained_model /OpenPCDet/checkpoints/seg_ep199.pth.tar --test_start_epoch 0
#sbatch --time=8:00:00 --array=1-3%1 --job-name=nusc-segdet-80ep-5perc-pretrained_ep_200 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_80ep_1sweeps_sampled_20_all_class.yaml --tcp_port 18919 --extra_tag segcontrast_only_det_pretrained_ep199 --pretrained_model /OpenPCDet/checkpoints/seg_only_det_ep199.pth.tar --test_start_epoch 0
#sbatch --time=8:00:00 --array=1-3%1 --job-name=nusc-seglidarplusdet-80ep-5perc-pretrained_ep_200 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_80ep_1sweeps_sampled_20_all_class.yaml --tcp_port 18920 --extra_tag segcontrast_lidarplusdet_pretrained_ep198 --pretrained_model /OpenPCDet/checkpoints/seg_lidar_plus_det_ep198.pth.tar --test_start_epoch 0
#sbatch --time=8:00:00 --array=1-3%1 --job-name=nusc-scratch-80ep-5perc tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_80ep_1sweeps_sampled_20_all_class.yaml --tcp_port 18921 --extra_tag scratch --test_start_epoch 0

# only car class 80 epochs 5% Nuscenes
# sbatch --time=8:00:00 --array=1-3%1 --job-name=nusc-segcar-80ep-5perc-pretrained_ep_200 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_80ep_1sweeps_sampled_20.yaml --tcp_port 18922 --extra_tag segcontrast_car_pretrained_ep199 --pretrained_model /OpenPCDet/checkpoints/seg_ep199.pth.tar --test_start_epoch 0
# sbatch --time=8:00:00 --array=1-3%1 --job-name=nusc-segdetcar-80ep-5perc-pretrained_ep_200 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_80ep_1sweeps_sampled_20.yaml --tcp_port 18923 --extra_tag segcontrast_only_det_car_pretrained_ep199 --pretrained_model /OpenPCDet/checkpoints/seg_only_det_ep199.pth.tar --test_start_epoch 0
# sbatch --time=8:00:00 --array=1-3%1 --job-name=nusc-seglidarplusdetcar-80ep-5perc-pretrained_ep_200 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_80ep_1sweeps_sampled_20.yaml --tcp_port 18924 --extra_tag segcontrast_lidarplusdet_car_pretrained_ep198 --pretrained_model /OpenPCDet/checkpoints/seg_lidar_plus_det_ep198.pth.tar --test_start_epoch 0
# sbatch --time=8:00:00 --array=1-3%1 --job-name=nusc-scratchcar-80ep-5perc tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_80ep_1sweeps_sampled_20.yaml --tcp_port 18925 --extra_tag scratch_car --test_start_epoch 0
#################################################33
## waymo 1 %, 30 ep
# sbatch --time=8:00:00 --array=1-1%1 --job-name=car-scratch-30ep-scene100 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_100.yaml --tcp_port 17910 --extra_tag scratch_car --test_start_epoch 20
# sbatch --time=1:00:00 --array=1-1%1 --job-name=car-scratch-30ep-scene100_t2 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_100.yaml --tcp_port 17911 --extra_tag scratch_car_t2 --test_start_epoch 20
#sbatch --time=8:00:00 --array=1-1%1 --job-name=segcar-28ep-scene100 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_28ep_scene_sampled_100.yaml --tcp_port 17912 --extra_tag segcontrast_car --pretrained_model /OpenPCDet/checkpoints/seg_ep49.pth.tar --test_start_epoch 18
#sbatch --time=8:00:00 --array=1-1%1 --job-name=segcar-28ep-scene100_t2 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_28ep_scene_sampled_100.yaml --tcp_port 17913 --extra_tag segcontrast_car_t2 --pretrained_model /OpenPCDet/checkpoints/seg_ep49.pth.tar --test_start_epoch 18
# sbatch --time=8:00:00 --array=1-1%1 --job-name=segdetcar-28ep-scene100 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_28ep_scene_sampled_100.yaml --tcp_port 17914 --extra_tag segcontrast_plus_dethead_0p8w_car --pretrained_model /OpenPCDet/checkpoints/seg_plus_det0p8_ep49.pth.tar --test_start_epoch 18
# sbatch --time=8:00:00 --array=1-1%1 --job-name=segdetcar-28ep-scene100_t2 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_28ep_scene_sampled_100.yaml --tcp_port 17915 --extra_tag segcontrast_plus_dethead_0p8w_car_t2 --pretrained_model /OpenPCDet/checkpoints/seg_plus_det0p8_ep49.pth.tar --test_start_epoch 18

sbatch --time=5:00:00 --array=1-1%1 --job-name=segcar-30ep-scene100 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_100.yaml --tcp_port 17912 --extra_tag segcontrast_car --pretrained_model /OpenPCDet/checkpoints/seg_ep49.pth.tar --test_start_epoch 20
#sbatch --time=3:00:00 --array=1-1%1 --job-name=segcar-30ep-scene100_t2 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_100.yaml --tcp_port 17913 --extra_tag segcontrast_car_t2 --pretrained_model /OpenPCDet/checkpoints/seg_ep49_t2.pth.tar --test_start_epoch 20
# sbatch --time=9:00:00 --array=1-1%1 --job-name=segcar-30ep-scene100_t3 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_100.yaml --tcp_port 17922 --extra_tag segcontrast_car_t3 --pretrained_model /OpenPCDet/checkpoints/seg_ep49.pth.tar --test_start_epoch 20
sbatch --time=9:00:00 --array=1-1%1 --job-name=segcar-30ep-scene100_t4 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_100.yaml --tcp_port 17914 --extra_tag segcontrast_car_t4 --pretrained_model /OpenPCDet/checkpoints/seg_ep49.pth.tar --test_start_epoch 20

#sbatch --time=8:00:00 --array=1-1%1 --job-name=segdetcar-30ep-scene100 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_100.yaml --tcp_port 17914 --extra_tag segcontrast_plus_det_car --pretrained_model /OpenPCDet/checkpoints/seg_plus_det_ep49.pth.tar --test_start_epoch 20
# sbatch --time=1:00:00 --array=1-1%1 --job-name=segdetcar-30ep-scene100_t2 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_100.yaml --tcp_port 17915 --extra_tag segcontrast_plus_det_car_t2 --pretrained_model /OpenPCDet/checkpoints/seg_plus_det_ep49_t2.pth.tar --test_start_epoch 20
# sbatch --time=9:00:00 --array=1-1%1 --job-name=segdetcar-30ep-scene100_t3 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_100.yaml --tcp_port 17925 --extra_tag segcontrast_plus_det_car_t3 --pretrained_model /OpenPCDet/checkpoints/seg_plus_det_ep49_t2.pth.tar --test_start_epoch 20
sbatch --time=8:30:00 --array=1-1%1 --job-name=segdetcar-30ep-scene100_t4 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_100.yaml --tcp_port 17925 --extra_tag segcontrast_plus_det_car_t4 --pretrained_model /OpenPCDet/checkpoints/seg_plus_det_ep49_t2.pth.tar --test_start_epoch 20
sbatch --time=8:30:00 --array=1-1%1 --job-name=segdetcar-30ep-scene100_t5 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_100.yaml --tcp_port 17926 --extra_tag segcontrast_plus_det_car_t5 --pretrained_model /OpenPCDet/checkpoints/seg_plus_det_ep49_t2.pth.tar --test_start_epoch 20

sbatch --time=8:30:00 --array=1-1%1 --job-name=segpluslidarORdetcar-30ep-scene100 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_100.yaml --tcp_port 17927 --extra_tag segcontrast_plus_lidar_or_det_car --pretrained_model /OpenPCDet/checkpoints/seg_plus_lidar_or_det_ep49.pth.tar --test_start_epoch 20
sbatch --time=8:30:00 --array=1-1%1 --job-name=segpluslidarORdetcar-30ep-scene100_t2 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_100.yaml --tcp_port 17928 --extra_tag segcontrast_plus_lidar_or_det_car_t2 --pretrained_model /OpenPCDet/checkpoints/seg_plus_lidar_or_det_ep49_t2.pth.tar --test_start_epoch 20

#sbatch --time=8:00:00 --array=1-1%1 --job-name=segonlydetcar-30ep-scene100 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_100.yaml --tcp_port 17916 --extra_tag segcontrast_only_det_car --pretrained_model /OpenPCDet/checkpoints/seg_only_det_ep49.pth.tar --test_start_epoch 20
# sbatch --time=8:00:00 --array=1-1%1 --job-name=segonlydetcar-30ep-scene100_t2 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_100.yaml --tcp_port 17917 --extra_tag segcontrast_only_det_car_t2 --pretrained_model /OpenPCDet/checkpoints/seg_only_det_ep49_t2.pth.tar --test_start_epoch 20
# sbatch --time=9:00:00 --array=1-1%1 --job-name=segonlydetcar-30ep-scene100_t3 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_100.yaml --tcp_port 17927 --extra_tag segcontrast_only_det_car_t3 --pretrained_model /OpenPCDet/checkpoints/seg_only_det_ep49_t2.pth.tar --test_start_epoch 20

#sbatch --time=8:00:00 --array=1-1%1 --job-name=segonlylidarcar-30ep-scene100 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_100.yaml --tcp_port 17918 --extra_tag segcontrast_only_lidar_car --pretrained_model /OpenPCDet/checkpoints/seg_only_lidar_ep49.pth.tar --test_start_epoch 20

# sbatch --time=1:00:00 --array=1-1%1 --job-name=segonlylidarcar-30ep-scene100_t2 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_100.yaml --tcp_port 17919 --extra_tag segcontrast_only_lidar_car_t2 --pretrained_model /OpenPCDet/checkpoints/seg_only_lidar_ep49_t2.pth.tar --test_start_epoch 20
# sbatch --time=9:00:00 --array=1-1%1 --job-name=segonlylidarcar-30ep-scene100_t3 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_100.yaml --tcp_port 17929 --extra_tag segcontrast_only_lidar_car_t3 --pretrained_model /OpenPCDet/checkpoints/seg_only_lidar_ep49_t2.pth.tar --test_start_epoch 20

# waymo 5%, 30 ep 
# sbatch --time=8:00:00 --array=1-3%1 --job-name=car-scratch-30ep-scene20 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_20.yaml --tcp_port 17810 --extra_tag scratch_car --test_start_epoch 20
# sbatch --time=8:00:00 --array=1-3%1 --job-name=car-scratch-30ep-scene20_t2 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_20.yaml --tcp_port 17811 --extra_tag scratch_car_t2 --test_start_epoch 20
sbatch --time=8:00:00 --array=1-3%1 --job-name=segcar-30ep-scene20 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_20.yaml --tcp_port 17812 --extra_tag segcontrast_car --pretrained_model /OpenPCDet/checkpoints/seg_ep49.pth.tar --test_start_epoch 20
sbatch --time=8:00:00 --array=1-3%1 --job-name=segcar-30ep-scene20_t2 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_20.yaml --tcp_port 17813 --extra_tag segcontrast_car_t2 --pretrained_model /OpenPCDet/checkpoints/seg_ep49_t2.pth.tar --test_start_epoch 20
sbatch --time=8:00:00 --array=1-3%1 --job-name=segcar-30ep-scene20_t2 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_20.yaml --tcp_port 17813 --extra_tag segcontrast_car_t2 --pretrained_model /OpenPCDet/checkpoints/seg_ep49_t2.pth.tar --test_start_epoch 20

sbatch --time=8:00:00 --array=1-3%1 --job-name=segdetcar-30ep-scene20 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_20.yaml --tcp_port 17814 --extra_tag segcontrast_plus_det_car --pretrained_model /OpenPCDet/checkpoints/seg_plus_det_ep49.pth.tar --test_start_epoch 20
sbatch --time=8:00:00 --array=1-3%1 --job-name=segdetcar-30ep-scene20_t2 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_20.yaml --tcp_port 17815 --extra_tag segcontrast_plus_det_car_t2 --pretrained_model /OpenPCDet/checkpoints/seg_plus_det_ep49_t2.pth.tar --test_start_epoch 20
sbatch --time=8:00:00 --array=1-1%1 --job-name=segonlydetcar-30ep-scene20 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_20.yaml --tcp_port 17816 --extra_tag segcontrast_only_det_car --pretrained_model /OpenPCDet/checkpoints/seg_only_det_ep49.pth.tar --test_start_epoch 20
sbatch --time=8:00:00 --array=1-1%1 --job-name=segonlydetcar-30ep-scene20_t2 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_20.yaml --tcp_port 17817 --extra_tag segcontrast_only_det_car_t2 --pretrained_model /OpenPCDet/checkpoints/seg_only_det_ep49_t2.pth.tar --test_start_epoch 20

# nusc 1%, 30 ep
# sbatch --time=5:00:00 --array=1-1%1 --job-name=30ep-nus-scratch-1perc tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_30ep_1sweeps_sampled_100.yaml --tcp_port 16910 --extra_tag scratch_car --test_start_epoch 20 --test_only
# sbatch --time=5:00:00 --array=1-1%1 --job-name=t2_30ep-nus-scratch-1perc tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_30ep_1sweeps_sampled_100.yaml --tcp_port 16911 --extra_tag scratch_car_t2 --test_start_epoch 20 --test_only
# sbatch --time=8:00:00 --array=1-1%1 --job-name=30ep-nus-seg-1perc tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_30ep_1sweeps_sampled_100.yaml --tcp_port 16912 --extra_tag segcontrast_car --pretrained_model /OpenPCDet/checkpoints/seg_ep49.pth.tar --test_start_epoch 18
# sbatch --time=8:00:00 --array=1-1%1 --job-name=t2_30ep-nus-seg-1perc tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_30ep_1sweeps_sampled_100.yaml --tcp_port 16913 --extra_tag segcontrast_car_t2 --pretrained_model /OpenPCDet/checkpoints/seg_ep49.pth.tar --test_start_epoch 18
# sbatch --time=8:00:00 --array=1-1%1 --job-name=30ep-nus-segdet-1perc tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_30ep_1sweeps_sampled_100.yaml --tcp_port 16914 --extra_tag segcontrast_plus_dethead_car --pretrained_model /OpenPCDet/checkpoints/seg_plus_det_nusc_ep49.pth.tar --test_start_epoch 18
# sbatch --time=8:00:00 --array=1-1%1 --job-name=t2_30ep-nus-segdet-1perc tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_30ep_1sweeps_sampled_100.yaml --tcp_port 16915 --extra_tag segcontrast_plus_dethead_car_t2 --pretrained_model /OpenPCDet/checkpoints/seg_plus_det_nusc_ep49.pth.tar --test_start_epoch 18

# nusc 5%, 30 ep
sbatch --time=5:00:00 --array=1-1%1 --job-name=30ep-nus-scratch-5perc tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_30ep_1sweeps_sampled_20.yaml --tcp_port 16811 --extra_tag scratch_car --test_start_epoch 20
sbatch --time=5:00:00 --array=1-1%1 --job-name=t2_30ep-nus-scratch-5perc tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_30ep_1sweeps_sampled_20.yaml --tcp_port 16812 --extra_tag scratch_car_t2 --test_start_epoch 20
# sbatch --time=8:00:00 --array=1-3%1 --job-name=30ep-nus-seg-5perc tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_30ep_1sweeps_sampled_20.yaml --tcp_port 16813 --extra_tag segcontrast_car --pretrained_model /OpenPCDet/checkpoints/seg_ep49.pth.tar --test_start_epoch 18
# sbatch --time=8:00:00 --array=1-3%1 --job-name=t2_30ep-nus-seg-5perc tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_30ep_1sweeps_sampled_20.yaml --tcp_port 16814 --extra_tag segcontrast_car_t2 --pretrained_model /OpenPCDet/checkpoints/seg_ep49.pth.tar --test_start_epoch 18
# sbatch --time=8:00:00 --array=1-3%1 --job-name=30ep-nus-segdet-5perc tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_30ep_1sweeps_sampled_20.yaml --tcp_port 16815 --extra_tag segcontrast_plus_dethead_car --pretrained_model /OpenPCDet/checkpoints/seg_plus_det_nusc_ep49.pth.tar --test_start_epoch 18
# sbatch --time=8:00:00 --array=1-3%1 --job-name=t2_30ep-nus-segdet-5perc tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_30ep_1sweeps_sampled_20.yaml --tcp_port 16816 --extra_tag segcontrast_plus_dethead_car_t2 --pretrained_model /OpenPCDet/checkpoints/seg_plus_det_nusc_ep49.pth.tar --test_start_epoch 18

##left
# sbatch --time=8:00:00 --array=1-1%1 --job-name=30ep-nus-seg-5perc tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_30ep_1sweeps_sampled_20.yaml --tcp_port 16813 --extra_tag segcontrast_car_t3 --pretrained_model /OpenPCDet/checkpoints/seg_ep49.pth.tar --test_start_epoch 20
# sbatch --time=8:00:00 --array=1-1%1 --job-name=t2_30ep-nus-seg-5perc tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_30ep_1sweeps_sampled_20.yaml --tcp_port 16814 --extra_tag segcontrast_car_t2 --pretrained_model /OpenPCDet/checkpoints/seg_ep49_t2.pth.tar --test_start_epoch 20
# sbatch --time=8:00:00 --array=1-1%1 --job-name=30ep-nus-segdet-5perc tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_30ep_1sweeps_sampled_20.yaml --tcp_port 16815 --extra_tag segcontrast_plus_dethead_car --pretrained_model /OpenPCDet/checkpoints/seg_plus_det_ep49.pth.tar --test_start_epoch 20
# sbatch --time=5:00:00 --array=1-1%1 --job-name=t2_30ep-nus-segdet-5perc tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_30ep_1sweeps_sampled_20.yaml --tcp_port 16816 --extra_tag segcontrast_plus_dethead_car_t3 --pretrained_model /OpenPCDet/checkpoints/seg_plus_det_ep49_t2.pth.tar --test_start_epoch 20

# sbatch --time=8:00:00 --array=1-1%1 --job-name=30ep-nus-sconlylidar-5perc tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_30ep_1sweeps_sampled_20.yaml --tcp_port 16817 --extra_tag segcontrast_only_lidar_car --pretrained_model /OpenPCDet/checkpoints/seg_only_lidar_ep49.pth.tar --test_start_epoch 20
sbatch --time=4:00:00 --array=1-1%1 --job-name=t4_30ep-nus-sconlylidar-5perc tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_30ep_1sweeps_sampled_20.yaml --tcp_port 16818 --extra_tag segcontrast_only_lidar_car_t4 --pretrained_model /OpenPCDet/checkpoints/seg_only_lidar_ep49_t2.pth.tar --test_start_epoch 20
sbatch --time=4:00:00 --array=1-1%1 --job-name=30ep-nus-sconlydet-5perc tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_30ep_1sweeps_sampled_20.yaml --tcp_port 16819 --extra_tag segcontrast_only_det --pretrained_model /OpenPCDet/checkpoints/seg_only_det_ep49_t2.pth.tar --test_start_epoch 20
sbatch --time=4:00:00 --array=1-1%1 --job-name=t2_30ep-nus-sconlydet-5perc tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_30ep_1sweeps_sampled_20.yaml --tcp_port 16820 --extra_tag segcontrast_only_det_t2 --pretrained_model /OpenPCDet/checkpoints/seg_only_det_ep49_t2.pth.tar --test_start_epoch 20

## waymo 1 %, 80 ep
sbatch --time=8:00:00 --array=1-2%1 --job-name=car-scratch-80ep-scene100 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_80ep_scene_sampled_100.yaml --tcp_port 18910 --extra_tag scratch_car --test_start_epoch 70
sbatch --time=8:00:00 --array=1-2%1 --job-name=car-scratch-80ep-scene100_t2 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_80ep_scene_sampled_100.yaml --tcp_port 18911 --extra_tag scratch_car_t2 --test_start_epoch 70
sbatch --time=8:00:00 --array=1-2%1 --job-name=segcar-78ep-scene100 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_78ep_scene_sampled_100.yaml --tcp_port 18912 --extra_tag segcontrast_car --pretrained_model /OpenPCDet/checkpoints/seg_ep49.pth.tar --test_start_epoch 68
sbatch --time=8:00:00 --array=1-2%1 --job-name=segcar-78ep-scene100_t2 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_78ep_scene_sampled_100.yaml --tcp_port 18913 --extra_tag segcontrast_car_t2 --pretrained_model /OpenPCDet/checkpoints/seg_ep49.pth.tar --test_start_epoch 68
sbatch --time=8:00:00 --array=1-2%1 --job-name=segdetcar-78ep-scene100 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_78ep_scene_sampled_100.yaml --tcp_port 18914 --extra_tag segcontrast_plus_dethead_0p8w_car --pretrained_model /OpenPCDet/checkpoints/seg_plus_det0p8_ep49.pth.tar --test_start_epoch 68
sbatch --time=8:00:00 --array=1-2%1 --job-name=segdetcar-78ep-scene100_t2 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_78ep_scene_sampled_100.yaml --tcp_port 18915 --extra_tag segcontrast_plus_dethead_0p8w_car_t2 --pretrained_model /OpenPCDet/checkpoints/seg_plus_det0p8_ep49.pth.tar --test_start_epoch 68


# To see hanging threads
#ps -ef | grep -i '[p]ython'
pids=$(ps aux | grep 'nisarbar' | grep 'python' | awk '{print $2}')
echo "$pids" | xargs kill