# # Train on FOV3000

########################################## Finetune SSL models ########################################## 

########### Finetune with one LR for both head and BB #############

########### Pretrained on dense + kitti ###########
########### dc ###########


sbatch --time=05:00:00 --gres=gpu:v100:4 --array=1-6%1 --job-name=finetune-all_splits_5_dc_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_5.yaml --extra_tag dc_dense_kitti_ep330 --tcp_port 18855 --ckpt_save_interval 20 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_b14_lr0p15_red_dense_kitti_ep330.pth.tar
# TODO (High priority)
# sbatch --time=05:00:00 --array=1-3%1 --job-name=finetune-all_splits_10_dc_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_10.yaml --extra_tag dc_dense_kitti_ep330 --tcp_port 18855 --ckpt_save_interval 10 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_b14_lr0p15_red_dense_kitti_ep330.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_splits_20_dc_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_20.yaml --extra_tag dc_dense_kitti_ep330 --tcp_port 18855 --ckpt_save_interval 5 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_b14_lr0p15_red_dense_kitti_ep330.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_splits_30_dc_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_30.yaml --extra_tag dc_dense_kitti_ep330 --tcp_port 18855 --ckpt_save_interval 3 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_b14_lr0p15_red_dense_kitti_ep330.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_splits_40_dc_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_40.yaml --extra_tag dc_dense_kitti_ep330 --tcp_port 18855 --ckpt_save_interval 2 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_b14_lr0p15_red_dense_kitti_ep330.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_splits_50_dc_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_50.yaml --extra_tag dc_dense_kitti_ep330 --tcp_port 18855 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_b14_lr0p15_red_dense_kitti_ep330.pth.tar

sbatch --time=05:00:00 --gres=gpu:v100:4 --array=1-3%1 --job-name=finetune-all_60_0_dc_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_0.yaml --extra_tag dc_dense_kitti_ep330 --tcp_port 18845 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_b14_lr0p15_red_dense_kitti_ep330.pth.tar
sbatch --time=05:00:00 --gres=gpu:v100:4 --array=1-3%1 --job-name=finetune-all_60_1_dc_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_1.yaml --extra_tag dc_dense_kitti_ep330 --tcp_port 18875 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_b14_lr0p15_red_dense_kitti_ep330.pth.tar
sbatch --time=05:00:00 --gres=gpu:v100:4 --array=1-3%1 --job-name=finetune-all_60_5_dc_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_5.yaml --extra_tag dc_dense_kitti_ep330 --tcp_port 18865 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_b14_lr0p15_red_dense_kitti_ep330.pth.tar
# TODO (High priority)
# sbatch --time=05:00:00 --array=1-3%1 --job-name=finetune-all_60_10_dc_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_10.yaml --extra_tag dc_dense_kitti_ep330 --tcp_port 18855 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_b14_lr0p15_red_dense_kitti_ep330.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_60_20_dc_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_20.yaml --extra_tag dc_dense_kitti_ep330 --tcp_port 18855 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_b14_lr0p15_red_dense_kitti_ep330.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_60_30_dc_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_30.yaml --extra_tag dc_dense_kitti_ep330 --tcp_port 18855 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_b14_lr0p15_red_dense_kitti_ep330.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_60_40_dc_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_40.yaml --extra_tag dc_dense_kitti_ep330 --tcp_port 18855 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_b14_lr0p15_red_dense_kitti_ep330.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_60_50_dc_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_50.yaml --extra_tag dc_dense_kitti_ep330 --tcp_port 18855 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_b14_lr0p15_red_dense_kitti_ep330.pth.tar