# # Train on FOV3000

########################################## Baselines (scratch training) ########################################## 
# # Adam one cycle
# sbatch --time=15:00:00 --array=1-1%1 --job-name=pointrcnn-clear-60-FOV3000 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_train_clear_FOV3000_60.yaml --tcp_port 18860 --ckpt_save_interval 1 --fix_random_seed
# sbatch --time=15:00:00 --array=1-1%1 --job-name=pointrcnn_snow_wet_coupled_barza tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_snow_wet_coupled_barza.yaml --tcp_port 18861 --ckpt_save_interval 1 --fix_random_seed
# sbatch --time=15:00:00 --array=1-1%1 --job-name=pointrcnn-all-60-FOV3000 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_train_all_FOV3000_60.yaml --tcp_port 18862 --ckpt_save_interval 1 --fix_random_seed

## TODO (Low priority) need code changes
# sbatch --time=15:00:00 --array=1-1%1 --job-name=pointrcnn_fog_sim tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_fog_sim.yaml --tcp_port 18861 --ckpt_save_interval 1 --fix_random_seed

# # Adam one cycle (on 5%, 10% etc of all weather data)
#sbatch --time=15:00:00 --array=1-2%1 --job-name=pointrcnn-all-splits-60-5 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_train_all_splits_60_5.yaml -tcp_port 18861 --ckpt_save_interval 20 --fix_random_seed
#sbatch --time=15:00:00 --array=1-1%1 --job-name=pointrcnn-all-splits-60-10 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_train_all_splits_60_10.yaml -tcp_port 18863 --ckpt_save_interval 10 --fix_random_seed
#sbatch --time=15:00:00 --array=1-1%1 --job-name=pointrcnn-all-splits-60-20 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_train_all_splits_60_20.yaml -tcp_port 18864 --ckpt_save_interval 5 --fix_random_seed

## TODO (low priority)
#sbatch --time=15:00:00 --array=1-1%1 --job-name=pointrcnn-all-splits-60-30 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_train_all_splits_60_30.yaml -tcp_port 18865 --ckpt_save_interval 3 --fix_random_seed
#sbatch --time=15:00:00 --array=1-1%1 --job-name=pointrcnn-all-splits-60-40 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_train_all_splits_60_40.yaml -tcp_port 18866 --ckpt_save_interval 2 --fix_random_seed
#sbatch --time=15:00:00 --array=1-1%1 --job-name=pointrcnn-all-splits-60-50 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_train_all_splits_60_50.yaml -tcp_port 18862 --ckpt_save_interval 1 --fix_random_seed

## TODO (High priority)
# # Adam one cycle (on 60% clear and 5%, 10% etc of adverse weather data)
#sbatch --time=15:00:00 --array=1-1%1 --job-name=pointrcnn-all-60-5 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_train_all_60_5.yaml -tcp_port 18861 --ckpt_save_interval 1 --fix_random_seed
#sbatch --time=15:00:00 --array=1-1%1 --job-name=pointrcnn-all-60-10 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_train_all_60_10.yaml -tcp_port 18863 --ckpt_save_interval 1 --fix_random_seed
#sbatch --time=15:00:00 --array=1-1%1 --job-name=pointrcnn-all-60-20 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_train_all_60_20.yaml -tcp_port 18864 --ckpt_save_interval 1 --fix_random_seed
#sbatch --time=15:00:00 --array=1-1%1 --job-name=pointrcnn-all-60-30 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_train_all_60_30.yaml -tcp_port 18865 --ckpt_save_interval 1 --fix_random_seed
#sbatch --time=15:00:00 --array=1-1%1 --job-name=pointrcnn-all-60-40 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_train_all_60_40.yaml -tcp_port 18866 --ckpt_save_interval 1 --fix_random_seed
#sbatch --time=15:00:00 --array=1-1%1 --job-name=pointrcnn-all-60-50 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_train_all_60_50.yaml -tcp_port 18862 --ckpt_save_interval 1 --fix_random_seed

########################################## Finetune SSL models ########################################## 

########### Finetune with one LR for both head and BB #############

########### Pretrained on dense + kitti ###########
########### dc+weather aug ###########
#---------------------------------------- Tuning params REMOVE ------------------------------------------------------------
# adamOnecycle 
# Bestest
# sbatch --time=24:00:00 --array=1-2%1 --job-name=finetune-all_splits_5_adamO_dc_1in2_cube_up_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_5_adamO.yaml --extra_tag dc_1in2_cube_up_red_dense_kitti_ep330 --tcp_port 18855 --ckpt_save_interval 20 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_1in2_cube_up_b14_lr0p15_red_dense_kitti_ep330.pth.tar
# sbatch --time=24:00:00 --array=1-2%1 --job-name=finetune-all_splits_5_adamO_wd0p001_dc_1in2_cube_up_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_5_adamO_wd0p001.yaml --extra_tag dc_1in2_cube_up_red_dense_kitti_ep330 --tcp_port 18865 --ckpt_save_interval 20 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_1in2_cube_up_b14_lr0p15_red_dense_kitti_ep330.pth.tar
# sbatch --time=24:00:00 --array=1-2%1 --job-name=finetune-all_splits_5_adamO_0p02_dc_1in2_cube_up_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_5_adamO_0p02.yaml --extra_tag dc_1in2_cube_up_red_dense_kitti_ep330 --tcp_port 18875 --ckpt_save_interval 20 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_1in2_cube_up_b14_lr0p15_red_dense_kitti_ep330.pth.tar
sbatch --time=10:00:00 --array=1-1%1 --job-name=finetune-all_splits_5_adamO_0p015_dc_1in2_cube_up_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_5_adamO_0p015.yaml --extra_tag dc_1in2_cube_up_red_dense_kitti_ep330 --tcp_port 18875 --ckpt_save_interval 20 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_1in2_cube_up_b14_lr0p15_red_dense_kitti_ep330.pth.tar

# # adamw_cosine 
# sbatch --time=24:00:00 --array=1-2%1 --job-name=finetune-all_splits_5_adamC_dc_1in2_cube_up_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_5_adamw_cosine_0p001.yaml --extra_tag dc_1in2_cube_up_red_dense_kitti_ep330 --tcp_port 18655 --ckpt_save_interval 20 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_1in2_cube_up_b14_lr0p15_red_dense_kitti_ep330.pth.tar
# sbatch --time=24:00:00 --array=1-2%1 --job-name=finetune-all_splits_5_adamC_wd0p001_dc_1in2_cube_up_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_5_adamw_cosine_0p001_wd0p001.yaml --extra_tag dc_1in2_cube_up_red_dense_kitti_ep330 --tcp_port 18665 --ckpt_save_interval 20 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_1in2_cube_up_b14_lr0p15_red_dense_kitti_ep330.pth.tar
# Best
# sbatch --time=24:00:00 --array=1-2%1 --job-name=finetune-all_splits_5_adamC_0p002_dc_1in2_cube_up_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_5_adamw_cosine_0p002.yaml --extra_tag dc_1in2_cube_up_red_dense_kitti_ep330 --tcp_port 18675 --ckpt_save_interval 20 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_1in2_cube_up_b14_lr0p15_red_dense_kitti_ep330.pth.tar
#---------------------------------------- Tuning params REMOVE ------------------------------------------------------------

# sbatch --time=15:00:00 --array=1-2%1 --job-name=finetune-all_splits_5_adamO_dc_1in2_cube_up_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_5_adamO.yaml --extra_tag dc_1in2_cube_up_red_dense_kitti_ep330 --tcp_port 18855 --ckpt_save_interval 20 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_1in2_cube_up_b14_lr0p15_red_dense_kitti_ep330.pth.tar

# TODO (High priority)
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_splits_10_dc_1in2_cube_up_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_10.yaml --extra_tag dc_1in2_cube_up_red_dense_kitti_ep330 --tcp_port 18855 --ckpt_save_interval 10 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_1in2_cube_up_b14_lr0p15_red_dense_kitti_ep330.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_splits_20_dc_1in2_cube_up_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_20.yaml --extra_tag dc_1in2_cube_up_red_dense_kitti_ep330 --tcp_port 18855 --ckpt_save_interval 5 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_1in2_cube_up_b14_lr0p15_red_dense_kitti_ep330.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_splits_30_dc_1in2_cube_up_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_30.yaml --extra_tag dc_1in2_cube_up_red_dense_kitti_ep330 --tcp_port 18855 --ckpt_save_interval 3 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_1in2_cube_up_b14_lr0p15_red_dense_kitti_ep330.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_splits_40_dc_1in2_cube_up_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_40.yaml --extra_tag dc_1in2_cube_up_red_dense_kitti_ep330 --tcp_port 18855 --ckpt_save_interval 2 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_1in2_cube_up_b14_lr0p15_red_dense_kitti_ep330.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_splits_50_dc_1in2_cube_up_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_50.yaml --extra_tag dc_1in2_cube_up_red_dense_kitti_ep330 --tcp_port 18855 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_1in2_cube_up_b14_lr0p15_red_dense_kitti_ep330.pth.tar

# TODO (High priority)
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_60_5_dc_1in2_cube_up_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_5.yaml --extra_tag dc_1in2_cube_up_red_dense_kitti_ep330 --tcp_port 18855 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_1in2_cube_up_b14_lr0p15_red_dense_kitti_ep330.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_60_10_dc_1in2_cube_up_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_10.yaml --extra_tag dc_1in2_cube_up_red_dense_kitti_ep330 --tcp_port 18855 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_1in2_cube_up_b14_lr0p15_red_dense_kitti_ep330.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_60_20_dc_1in2_cube_up_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_20.yaml --extra_tag dc_1in2_cube_up_red_dense_kitti_ep330 --tcp_port 18855 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_1in2_cube_up_b14_lr0p15_red_dense_kitti_ep330.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_60_30_dc_1in2_cube_up_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_30.yaml --extra_tag dc_1in2_cube_up_red_dense_kitti_ep330 --tcp_port 18855 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_1in2_cube_up_b14_lr0p15_red_dense_kitti_ep330.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_60_40_dc_1in2_cube_up_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_40.yaml --extra_tag dc_1in2_cube_up_red_dense_kitti_ep330 --tcp_port 18855 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_1in2_cube_up_b14_lr0p15_red_dense_kitti_ep330.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_60_50_dc_1in2_cube_up_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_50.yaml --extra_tag dc_1in2_cube_up_red_dense_kitti_ep330 --tcp_port 18855 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_1in2_cube_up_b14_lr0p15_red_dense_kitti_ep330.pth.tar

########### Pretrained on dense + kitti ###########
########### dc ###########
# TODO (High priority)
sbatch --time=10:00:00 --array=1-1%1 --job-name=finetune-all_splits_5_dc_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_5.yaml --extra_tag dc_dense_kitti_ep330 --tcp_port 18855 --ckpt_save_interval 20 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_b14_lr0p15_red_dense_kitti_ep330.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_splits_10_dc_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_10.yaml --extra_tag dc_dense_kitti_ep330 --tcp_port 18855 --ckpt_save_interval 10 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_b14_lr0p15_red_dense_kitti_ep330.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_splits_20_dc_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_20.yaml --extra_tag dc_dense_kitti_ep330 --tcp_port 18855 --ckpt_save_interval 5 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_b14_lr0p15_red_dense_kitti_ep330.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_splits_30_dc_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_30.yaml --extra_tag dc_dense_kitti_ep330 --tcp_port 18855 --ckpt_save_interval 3 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_b14_lr0p15_red_dense_kitti_ep330.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_splits_40_dc_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_40.yaml --extra_tag dc_dense_kitti_ep330 --tcp_port 18855 --ckpt_save_interval 2 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_b14_lr0p15_red_dense_kitti_ep330.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_splits_50_dc_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_50.yaml --extra_tag dc_dense_kitti_ep330 --tcp_port 18855 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_b14_lr0p15_red_dense_kitti_ep330.pth.tar

# TODO (High priority)
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_60_5_dc_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_5.yaml --extra_tag dc_dense_kitti_ep330 --tcp_port 18855 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_b14_lr0p15_red_dense_kitti_ep330.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_60_10_dc_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_10.yaml --extra_tag dc_dense_kitti_ep330 --tcp_port 18855 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_b14_lr0p15_red_dense_kitti_ep330.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_60_20_dc_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_20.yaml --extra_tag dc_dense_kitti_ep330 --tcp_port 18855 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_b14_lr0p15_red_dense_kitti_ep330.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_60_30_dc_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_30.yaml --extra_tag dc_dense_kitti_ep330 --tcp_port 18855 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_b14_lr0p15_red_dense_kitti_ep330.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_60_40_dc_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_40.yaml --extra_tag dc_dense_kitti_ep330 --tcp_port 18855 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_b14_lr0p15_red_dense_kitti_ep330.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_60_50_dc_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_50.yaml --extra_tag dc_dense_kitti_ep330 --tcp_port 18855 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_b14_lr0p15_red_dense_kitti_ep330.pth.tar


########### Pretrained on dense + kitti ###########
########### seg + weather aug ###########

# TODO (2nd High priority)
# sbatch --time=15:00:00 --array=1-2%1 --job-name=finetune-all_splits_5_seg_1in2_cube_up_dense_kitti_ep200 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_5.yaml --extra_tag seg_1in2_cube_up_dense_kitti_ep200 --tcp_port 18855 --ckpt_save_interval 20 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/seg_1in2_cube_up_dense_kitti_ep200.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_splits_10_seg_1in2_cube_up_dense_kitti_ep200 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_10.yaml --extra_tag seg_1in2_cube_up_dense_kitti_ep200 --tcp_port 18855 --ckpt_save_interval 10 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/seg_1in2_cube_up_dense_kitti_ep200.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_splits_20_seg_1in2_cube_up_dense_kitti_ep200 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_20.yaml --extra_tag seg_1in2_cube_up_dense_kitti_ep200 --tcp_port 18855 --ckpt_save_interval 5 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/seg_1in2_cube_up_dense_kitti_ep200.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_splits_30_seg_1in2_cube_up_dense_kitti_ep200 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_30.yaml --extra_tag seg_1in2_cube_up_dense_kitti_ep200 --tcp_port 18855 --ckpt_save_interval 3 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/seg_1in2_cube_up_dense_kitti_ep200.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_splits_40_seg_1in2_cube_up_dense_kitti_ep200 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_40.yaml --extra_tag seg_1in2_cube_up_dense_kitti_ep200 --tcp_port 18855 --ckpt_save_interval 2 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/seg_1in2_cube_up_dense_kitti_ep200.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_splits_50_seg_1in2_cube_up_dense_kitti_ep200 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_50.yaml --extra_tag seg_1in2_cube_up_dense_kitti_ep200 --tcp_port 18855 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/seg_1in2_cube_up_dense_kitti_ep200.pth.tar

# TODO (2nd High priority)
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_60_5_seg_1in2_cube_up_dense_kitti_ep200 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_5.yaml --extra_tag seg_1in2_cube_up_dense_kitti_ep200 --tcp_port 18855 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/seg_1in2_cube_up_dense_kitti_ep200.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_60_10_seg_1in2_cube_up_dense_kitti_ep200 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_10.yaml --extra_tag seg_1in2_cube_up_dense_kitti_ep200 --tcp_port 18855 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/seg_1in2_cube_up_dense_kitti_ep200.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_60_20_seg_1in2_cube_up_dense_kitti_ep200 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_20.yaml --extra_tag seg_1in2_cube_up_dense_kitti_ep200 --tcp_port 18855 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/seg_1in2_cube_up_dense_kitti_ep200.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_60_30_seg_1in2_cube_up_dense_kitti_ep200 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_30.yaml --extra_tag seg_1in2_cube_up_dense_kitti_ep200 --tcp_port 18855 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/seg_1in2_cube_up_dense_kitti_ep200.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_60_40_seg_1in2_cube_up_dense_kitti_ep200 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_40.yaml --extra_tag seg_1in2_cube_up_dense_kitti_ep200 --tcp_port 18855 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/seg_1in2_cube_up_dense_kitti_ep200.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_60_50_seg_1in2_cube_up_dense_kitti_ep200 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_50.yaml --extra_tag seg_1in2_cube_up_dense_kitti_ep200 --tcp_port 18855 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/seg_1in2_cube_up_dense_kitti_ep200.pth.tar

########### Pretrained on dense + kitti ###########
########### seg ###########
# TODO (2nd High priority)
# sbatch --time=15:00:00 --array=1-2%1 --job-name=finetune-all_splits_5_seg_dense_kitti_ep200 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_5.yaml --extra_tag seg_dense_kitti_ep200 --tcp_port 18855 --ckpt_save_interval 20 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/seg_dense_kitti_ep200.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_splits_10_seg_dense_kitti_ep200 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_10.yaml --extra_tag seg_dense_kitti_ep200 --tcp_port 18855 --ckpt_save_interval 10 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/seg_dense_kitti_ep200.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_splits_20_seg_dense_kitti_ep200 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_20.yaml --extra_tag seg_dense_kitti_ep200 --tcp_port 18855 --ckpt_save_interval 5 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/seg_dense_kitti_ep200.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_splits_30_seg_dense_kitti_ep200 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_30.yaml --extra_tag seg_dense_kitti_ep200 --tcp_port 18855 --ckpt_save_interval 3 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/seg_dense_kitti_ep200.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_splits_40_seg_dense_kitti_ep200 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_40.yaml --extra_tag seg_dense_kitti_ep200 --tcp_port 18855 --ckpt_save_interval 2 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/seg_dense_kitti_ep200.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_splits_50_seg_dense_kitti_ep200 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_50.yaml --extra_tag seg_dense_kitti_ep200 --tcp_port 18855 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/seg_dense_kitti_ep200.pth.tar

# TODO (2nd High priority)
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_60_5_seg_dense_kitti_ep200 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_5.yaml --extra_tag seg_dense_kitti_ep200 --tcp_port 18855 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/seg_dense_kitti_ep200.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_60_10_seg_dense_kitti_ep200 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_10.yaml --extra_tag seg_dense_kitti_ep200 --tcp_port 18855 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/seg_dense_kitti_ep200.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_60_20_seg_dense_kitti_ep200 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_20.yaml --extra_tag seg_dense_kitti_ep200 --tcp_port 18855 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/seg_dense_kitti_ep200.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_60_30_seg_dense_kitti_ep200 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_30.yaml --extra_tag seg_dense_kitti_ep200 --tcp_port 18855 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/seg_dense_kitti_ep200.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_60_40_seg_dense_kitti_ep200 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_40.yaml --extra_tag seg_dense_kitti_ep200 --tcp_port 18855 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/seg_dense_kitti_ep200.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_60_50_seg_dense_kitti_ep200 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_50.yaml --extra_tag seg_dense_kitti_ep200 --tcp_port 18855 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/seg_dense_kitti_ep200.pth.tar



#(Pretrained on dense + semkitti: Lowest Priority)