
#seg_49 is from turing segcontrast_waymo10
#seg_plus_det_nusc_ep49 is from lovelace segcontrast_waymo10_lidar_aug_single_randh_det0p5w
#seg_plus_det0p8_ep49 is from narval /home/nisarbar/projects/rrg-swasland/nisarbar/DepthContrast/checkpoints/minkunet/minkunet_pretrain_segcontrast_waymo10_dethead_0p8w/pretrain_waymo

tools/scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 0,1 --tcp_port 19835 --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_100.yaml --extra_tag turing_segcontrast_car --pretrained_model /OpenPCDet/checkpoints/seg_ep49.pth.tar --test_start_epoch 20 > ./output/log/seg_car_30ep_1perc_waymo_$(date +%Y-%m-%d_%H:%M).out 2>&1
tools/scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 0,1 --tcp_port 19835 --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_100.yaml --extra_tag turing_segcontrast_plus_det_car --pretrained_model /OpenPCDet/checkpoints/seg_plus_det_ep49_t2.pth.tar --test_start_epoch 20 > ./output/log/segdet_car_30ep_1perc_waymo_$(date +%Y-%m-%d_%H:%M).out 2>&1
tools/scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 2,3 --tcp_port 19836 --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_100.yaml --extra_tag turing_scratch_car --test_start_epoch 20 > ./output/log/scratch_car_30ep_1perc_waymo_$(date +%Y-%m-%d_%H:%M).out 2>&1

tools/scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 0,1 --tcp_port 19835 --cfg_file tools/cfgs/waymo_models/pointrcnn_scene_sampled_100.yaml --extra_tag turing_pts_seg_car_ep30_t2 --pretrained_model /OpenPCDet/checkpoints/pts_seg_ep49_t2.pth.tar --test_start_epoch 20 --test_only > ./output/log/pts_seg_car_30ep_1perc_waymo_t2_$(date +%Y-%m-%d_%H:%M).out 2>&1
tools/scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 2,3 --tcp_port 19836 --cfg_file tools/cfgs/waymo_models/pointrcnn_scene_sampled_100.yaml --extra_tag turing_pts_seg_only_det_car_ep30 --pretrained_model /OpenPCDet/checkpoints/pts_seg_only_det_ep49.pth.tar --test_start_epoch 20 > ./output/log/pts_seg_only_det_car_30ep_1perc_waymo_$(date +%Y-%m-%d_%H:%M).out 2>&1

tools/scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 0,1 --tcp_port 19835 --cfg_file tools/cfgs/waymo_models/pointrcnn_scene_sampled_100.yaml --extra_tag turing_pts_seg_car_ep100_t2 --pretrained_model /OpenPCDet/checkpoints/pts_seg_ep49_t2.pth.tar --test_start_epoch 20 --test_only > ./output/log/pts_seg_car_30ep_1perc_waymo_t2_$(date +%Y-%m-%d_%H:%M).out 2>&1
tools/scripts/submit_ddp_turing.sh --num_gpus 2 --cuda_visible_devices 2,3 --tcp_port 19836 --cfg_file tools/cfgs/waymo_models/pointrcnn_scene_sampled_100.yaml --extra_tag turing_pts_seg_only_det_car_ep100 --pretrained_model /OpenPCDet/checkpoints/pts_seg_only_det_ep49.pth.tar --test_start_epoch 20 > ./output/log/pts_seg_only_det_car_30ep_1perc_waymo_$(date +%Y-%m-%d_%H:%M).out 2>&1

sbatch --time=4:00:00 --array=1-1%1 --job-name=segcar-30ep-scene100-pretrained_ep_200 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_100.yaml --tcp_port 17912 --extra_tag segcontrast_car_pretrained_ep199 --pretrained_model /OpenPCDet/checkpoints/seg_ep199.pth.tar --test_only --test_start_epoch 0
sbatch --time=4:00:00 --array=1-1%1 --job-name=segdetcar-30ep-scene100-pretrained_ep_200 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_100.yaml --tcp_port 17913 --extra_tag segcontrast_only_det_car_pretrained_ep199 --pretrained_model /OpenPCDet/checkpoints/seg_only_det_ep199.pth.tar --test_only --test_start_epoch 0
sbatch --time=4:00:00 --array=1-1%1 --job-name=seglidarplusdetcar-30ep-scene100-pretrained_ep_200 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_100.yaml --tcp_port 17914 --extra_tag segcontrast_lidarplusdet_car_pretrained_ep198 --pretrained_model /OpenPCDet/checkpoints/seg_lidar_plus_det_ep198.pth.tar --test_only --test_start_epoch 0

sbatch --time=3:00:00 --array=1-1%1 --job-name=segcar-30ep-scene100-pretrained_ep_200 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_100.yaml --tcp_port 17912 --extra_tag segcontrast_car_pretrained_ep199 --pretrained_model /OpenPCDet/checkpoints/seg_ep199.pth.tar --test_start_epoch 20
sbatch --time=3:00:00 --array=1-1%1 --job-name=segdetcar-30ep-scene100-pretrained_ep_200 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_100.yaml --tcp_port 17913 --extra_tag segcontrast_only_det_car_pretrained_ep199 --pretrained_model /OpenPCDet/checkpoints/seg_only_det_ep199.pth.tar --test_start_epoch 20
# sbatch --time=8:30:00 --array=1-1%1 --job-name=seglidarplusdetcar-30ep-scene100-pretrained_ep_200 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_100.yaml --tcp_port 17914 --extra_tag segcontrast_lidarplusdet_car_pretrained_ep199 --pretrained_model /OpenPCDet/checkpoints/seg_lidar_plus_det_ep199.pth.tar --test_start_epoch 20
sbatch --time=3:00:00 --array=1-1%1 --job-name=seglidarplusdetcar-30ep-scene100-pretrained_ep_200 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_100.yaml --tcp_port 17914 --extra_tag segcontrast_lidarplusdet_car_pretrained_ep198 --pretrained_model /OpenPCDet/checkpoints/seg_lidar_plus_det_ep198.pth.tar --test_start_epoch 20

sbatch --time=8:30:00 --array=1-3%1 --job-name=segcar-80ep-scene100-pretrained_ep_200 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_80ep_scene_sampled_100.yaml --tcp_port 17915 --extra_tag segcontrast_car_pretrained_ep199 --pretrained_model /OpenPCDet/checkpoints/seg_ep199.pth.tar --test_start_epoch 70
sbatch --time=8:30:00 --array=1-3%1 --job-name=segdetcar-80ep-scene100-pretrained_ep_200 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_80ep_scene_sampled_100.yaml --tcp_port 17916 --extra_tag segcontrast_only_det_car_pretrained_ep199 --pretrained_model /OpenPCDet/checkpoints/seg_only_det_ep199.pth.tar --test_start_epoch 70
sbatch --time=8:30:00 --array=1-3%1 --job-name=seglidarplusdetcar-80ep-scene100-pretrained_ep_200 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_80ep_scene_sampled_100.yaml --tcp_port 17917 --extra_tag segcontrast_lidarplusdet_car_pretrained_ep198 --pretrained_model /OpenPCDet/checkpoints/seg_lidar_plus_det_ep198.pth.tar --test_start_epoch 70

# only car class 200 epochs 1% Waymo
sbatch --time=8:00:00 --array=1-3%1 --job-name=segcar-200ep-scene100-pretrained_ep_200 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_200ep_scene_sampled_100.yaml --tcp_port 17915 --extra_tag segcontrast_car_pretrained_ep199 --pretrained_model /OpenPCDet/checkpoints/seg_ep199.pth.tar --test_start_epoch 0
sbatch --time=8:00:00 --array=1-3%1 --job-name=segdetcar-200ep-scene100-pretrained_ep_200 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_200ep_scene_sampled_100.yaml --tcp_port 17916 --extra_tag segcontrast_only_det_car_pretrained_ep199 --pretrained_model /OpenPCDet/checkpoints/seg_only_det_ep199.pth.tar --test_start_epoch 0
sbatch --time=8:00:00 --array=1-3%1 --job-name=seglidarplusdetcar-200ep-scene100-pretrained_ep_200 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_200ep_scene_sampled_100.yaml --tcp_port 17917 --extra_tag segcontrast_lidarplusdet_car_pretrained_ep198 --pretrained_model /OpenPCDet/checkpoints/seg_lidar_plus_det_ep198.pth.tar --test_start_epoch 0
sbatch --time=8:00:00 --array=1-3%1 --job-name=car-scratch-200ep-scene100 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_200ep_scene_sampled_100.yaml --tcp_port 17910 --extra_tag scratch_car --test_start_epoch 0

# all class 80 epochs 1% Waymo
sbatch --time=8:00:00 --array=1-3%1 --job-name=seg-80ep-scene100-pretrained_ep_200 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_80ep_scene_sampled_100_all_class.yaml --tcp_port 17918 --extra_tag segcontrast_pretrained_ep199 --pretrained_model /OpenPCDet/checkpoints/seg_ep199.pth.tar --test_start_epoch 0
sbatch --time=8:00:00 --array=1-3%1 --job-name=segdet-80ep-scene100-pretrained_ep_200 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_80ep_scene_sampled_100_all_class.yaml --tcp_port 17919 --extra_tag segcontrast_only_det_pretrained_ep199 --pretrained_model /OpenPCDet/checkpoints/seg_only_det_ep199.pth.tar --test_start_epoch 0
sbatch --time=8:00:00 --array=1-3%1 --job-name=seglidarplusdet-80ep-scene100-pretrained_ep_200 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_80ep_scene_sampled_100_all_class.yaml --tcp_port 17920 --extra_tag segcontrast_lidarplusdet_pretrained_ep198 --pretrained_model /OpenPCDet/checkpoints/seg_lidar_plus_det_ep198.pth.tar --test_start_epoch 0
sbatch --time=8:00:00 --array=1-3%1 --job-name=scratch-80ep-scene100 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_80ep_scene_sampled_100_all_class.yaml --tcp_port 17921 --extra_tag scratch --test_start_epoch 0

# all class 80 epochs 5% Nuscenes
sbatch --time=8:00:00 --array=1-3%1 --job-name=nusc-seg-80ep-5perc-pretrained_ep_200 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_80ep_1sweeps_sampled_20_all_class.yaml --tcp_port 18918 --extra_tag segcontrast_pretrained_ep199 --pretrained_model /OpenPCDet/checkpoints/seg_ep199.pth.tar --test_start_epoch 0
sbatch --time=8:00:00 --array=1-3%1 --job-name=nusc-segdet-80ep-5perc-pretrained_ep_200 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_80ep_1sweeps_sampled_20_all_class.yaml --tcp_port 18919 --extra_tag segcontrast_only_det_pretrained_ep199 --pretrained_model /OpenPCDet/checkpoints/seg_only_det_ep199.pth.tar --test_start_epoch 0
sbatch --time=8:00:00 --array=1-3%1 --job-name=nusc-seglidarplusdet-80ep-5perc-pretrained_ep_200 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_80ep_1sweeps_sampled_20_all_class.yaml --tcp_port 18920 --extra_tag segcontrast_lidarplusdet_pretrained_ep198 --pretrained_model /OpenPCDet/checkpoints/seg_lidar_plus_det_ep198.pth.tar --test_start_epoch 0
sbatch --time=8:00:00 --array=1-3%1 --job-name=nusc-scratch-80ep-5perc tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_80ep_1sweeps_sampled_20_all_class.yaml --tcp_port 18921 --extra_tag scratch --test_start_epoch 0

# only car class 80 epochs 5% Nuscenes
sbatch --time=8:00:00 --array=1-3%1 --job-name=nusc-segcar-80ep-5perc-pretrained_ep_200 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_80ep_1sweeps_sampled_20.yaml --tcp_port 18922 --extra_tag segcontrast_car_pretrained_ep199 --pretrained_model /OpenPCDet/checkpoints/seg_ep199.pth.tar --test_start_epoch 0
sbatch --time=8:00:00 --array=1-3%1 --job-name=nusc-segdetcar-80ep-5perc-pretrained_ep_200 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_80ep_1sweeps_sampled_20.yaml --tcp_port 18923 --extra_tag segcontrast_only_det_car_pretrained_ep199 --pretrained_model /OpenPCDet/checkpoints/seg_only_det_ep199.pth.tar --test_start_epoch 0
sbatch --time=8:00:00 --array=1-3%1 --job-name=nusc-seglidarplusdetcar-80ep-5perc-pretrained_ep_200 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_80ep_1sweeps_sampled_20.yaml --tcp_port 18924 --extra_tag segcontrast_lidarplusdet_car_pretrained_ep198 --pretrained_model /OpenPCDet/checkpoints/seg_lidar_plus_det_ep198.pth.tar --test_start_epoch 0
sbatch --time=8:00:00 --array=1-3%1 --job-name=nusc-scratchcar-80ep-5perc tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_80ep_1sweeps_sampled_20.yaml --tcp_port 18925 --extra_tag scratch_car --test_start_epoch 0

## waymo 1 %, 30 ep
# sbatch --time=8:00:00 --array=1-1%1 --job-name=car-scratch-30ep-scene100 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_100.yaml --tcp_port 17910 --extra_tag scratch_car --test_start_epoch 20
# sbatch --time=1:00:00 --array=1-1%1 --job-name=car-scratch-30ep-scene100_t2 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_100.yaml --tcp_port 17911 --extra_tag scratch_car_t2 --test_start_epoch 20
#sbatch --time=8:00:00 --array=1-1%1 --job-name=segcar-28ep-scene100 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_28ep_scene_sampled_100.yaml --tcp_port 17912 --extra_tag segcontrast_car --pretrained_model /OpenPCDet/checkpoints/seg_ep49.pth.tar --test_start_epoch 18
#sbatch --time=8:00:00 --array=1-1%1 --job-name=segcar-28ep-scene100_t2 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_28ep_scene_sampled_100.yaml --tcp_port 17913 --extra_tag segcontrast_car_t2 --pretrained_model /OpenPCDet/checkpoints/seg_ep49.pth.tar --test_start_epoch 18
# sbatch --time=8:00:00 --array=1-1%1 --job-name=segdetcar-28ep-scene100 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_28ep_scene_sampled_100.yaml --tcp_port 17914 --extra_tag segcontrast_plus_dethead_0p8w_car --pretrained_model /OpenPCDet/checkpoints/seg_plus_det0p8_ep49.pth.tar --test_start_epoch 18
# sbatch --time=8:00:00 --array=1-1%1 --job-name=segdetcar-28ep-scene100_t2 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_28ep_scene_sampled_100.yaml --tcp_port 17915 --extra_tag segcontrast_plus_dethead_0p8w_car_t2 --pretrained_model /OpenPCDet/checkpoints/seg_plus_det0p8_ep49.pth.tar --test_start_epoch 18

sbatch --time=5:00:00 --array=1-1%1 --job-name=segcar-30ep-scene100 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_100.yaml --tcp_port 17912 --extra_tag segcontrast_car --pretrained_model /OpenPCDet/checkpoints/seg_ep49.pth.tar --test_start_epoch 20
#sbatch --time=3:00:00 --array=1-1%1 --job-name=segcar-30ep-scene100_t2 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_100.yaml --tcp_port 17913 --extra_tag segcontrast_car_t2 --pretrained_model /OpenPCDet/checkpoints/seg_ep49_t2.pth.tar --test_start_epoch 20
# sbatch --time=9:00:00 --array=1-1%1 --job-name=segcar-30ep-scene100_t3 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_100.yaml --tcp_port 17922 --extra_tag segcontrast_car_t3 --pretrained_model /OpenPCDet/checkpoints/seg_ep49.pth.tar --test_start_epoch 20
sbatch --time=9:00:00 --array=1-1%1 --job-name=segcar-30ep-scene100_t4 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_100.yaml --tcp_port 17914 --extra_tag segcontrast_car_t4 --pretrained_model /OpenPCDet/checkpoints/seg_ep49.pth.tar --test_start_epoch 20

#sbatch --time=8:00:00 --array=1-1%1 --job-name=segdetcar-30ep-scene100 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_100.yaml --tcp_port 17914 --extra_tag segcontrast_plus_det_car --pretrained_model /OpenPCDet/checkpoints/seg_plus_det_ep49.pth.tar --test_start_epoch 20
# sbatch --time=1:00:00 --array=1-1%1 --job-name=segdetcar-30ep-scene100_t2 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_100.yaml --tcp_port 17915 --extra_tag segcontrast_plus_det_car_t2 --pretrained_model /OpenPCDet/checkpoints/seg_plus_det_ep49_t2.pth.tar --test_start_epoch 20
# sbatch --time=9:00:00 --array=1-1%1 --job-name=segdetcar-30ep-scene100_t3 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_100.yaml --tcp_port 17925 --extra_tag segcontrast_plus_det_car_t3 --pretrained_model /OpenPCDet/checkpoints/seg_plus_det_ep49_t2.pth.tar --test_start_epoch 20
sbatch --time=8:30:00 --array=1-1%1 --job-name=segdetcar-30ep-scene100_t4 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_100.yaml --tcp_port 17925 --extra_tag segcontrast_plus_det_car_t4 --pretrained_model /OpenPCDet/checkpoints/seg_plus_det_ep49_t2.pth.tar --test_start_epoch 20
sbatch --time=8:30:00 --array=1-1%1 --job-name=segdetcar-30ep-scene100_t5 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_100.yaml --tcp_port 17926 --extra_tag segcontrast_plus_det_car_t5 --pretrained_model /OpenPCDet/checkpoints/seg_plus_det_ep49_t2.pth.tar --test_start_epoch 20

sbatch --time=8:30:00 --array=1-1%1 --job-name=segpluslidarORdetcar-30ep-scene100 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_100.yaml --tcp_port 17927 --extra_tag segcontrast_plus_lidar_or_det_car --pretrained_model /OpenPCDet/checkpoints/seg_plus_lidar_or_det_ep49.pth.tar --test_start_epoch 20
sbatch --time=8:30:00 --array=1-1%1 --job-name=segpluslidarORdetcar-30ep-scene100_t2 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_100.yaml --tcp_port 17928 --extra_tag segcontrast_plus_lidar_or_det_car_t2 --pretrained_model /OpenPCDet/checkpoints/seg_plus_lidar_or_det_ep49_t2.pth.tar --test_start_epoch 20

#sbatch --time=8:00:00 --array=1-1%1 --job-name=segonlydetcar-30ep-scene100 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_100.yaml --tcp_port 17916 --extra_tag segcontrast_only_det_car --pretrained_model /OpenPCDet/checkpoints/seg_only_det_ep49.pth.tar --test_start_epoch 20
# sbatch --time=8:00:00 --array=1-1%1 --job-name=segonlydetcar-30ep-scene100_t2 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_100.yaml --tcp_port 17917 --extra_tag segcontrast_only_det_car_t2 --pretrained_model /OpenPCDet/checkpoints/seg_only_det_ep49_t2.pth.tar --test_start_epoch 20
# sbatch --time=9:00:00 --array=1-1%1 --job-name=segonlydetcar-30ep-scene100_t3 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_100.yaml --tcp_port 17927 --extra_tag segcontrast_only_det_car_t3 --pretrained_model /OpenPCDet/checkpoints/seg_only_det_ep49_t2.pth.tar --test_start_epoch 20

#sbatch --time=8:00:00 --array=1-1%1 --job-name=segonlylidarcar-30ep-scene100 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_100.yaml --tcp_port 17918 --extra_tag segcontrast_only_lidar_car --pretrained_model /OpenPCDet/checkpoints/seg_only_lidar_ep49.pth.tar --test_start_epoch 20

# sbatch --time=1:00:00 --array=1-1%1 --job-name=segonlylidarcar-30ep-scene100_t2 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_100.yaml --tcp_port 17919 --extra_tag segcontrast_only_lidar_car_t2 --pretrained_model /OpenPCDet/checkpoints/seg_only_lidar_ep49_t2.pth.tar --test_start_epoch 20
# sbatch --time=9:00:00 --array=1-1%1 --job-name=segonlylidarcar-30ep-scene100_t3 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_100.yaml --tcp_port 17929 --extra_tag segcontrast_only_lidar_car_t3 --pretrained_model /OpenPCDet/checkpoints/seg_only_lidar_ep49_t2.pth.tar --test_start_epoch 20

# waymo 5%, 30 ep 
# sbatch --time=8:00:00 --array=1-3%1 --job-name=car-scratch-30ep-scene20 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_20.yaml --tcp_port 17810 --extra_tag scratch_car --test_start_epoch 20
# sbatch --time=8:00:00 --array=1-3%1 --job-name=car-scratch-30ep-scene20_t2 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_20.yaml --tcp_port 17811 --extra_tag scratch_car_t2 --test_start_epoch 20
sbatch --time=8:00:00 --array=1-3%1 --job-name=segcar-30ep-scene20 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_20.yaml --tcp_port 17812 --extra_tag segcontrast_car --pretrained_model /OpenPCDet/checkpoints/seg_ep49.pth.tar --test_start_epoch 20
sbatch --time=8:00:00 --array=1-3%1 --job-name=segcar-30ep-scene20_t2 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_20.yaml --tcp_port 17813 --extra_tag segcontrast_car_t2 --pretrained_model /OpenPCDet/checkpoints/seg_ep49_t2.pth.tar --test_start_epoch 20
sbatch --time=8:00:00 --array=1-3%1 --job-name=segcar-30ep-scene20_t2 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_20.yaml --tcp_port 17813 --extra_tag segcontrast_car_t2 --pretrained_model /OpenPCDet/checkpoints/seg_ep49_t2.pth.tar --test_start_epoch 20

sbatch --time=8:00:00 --array=1-3%1 --job-name=segdetcar-30ep-scene20 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_20.yaml --tcp_port 17814 --extra_tag segcontrast_plus_det_car --pretrained_model /OpenPCDet/checkpoints/seg_plus_det_ep49.pth.tar --test_start_epoch 20
sbatch --time=8:00:00 --array=1-3%1 --job-name=segdetcar-30ep-scene20_t2 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_20.yaml --tcp_port 17815 --extra_tag segcontrast_plus_det_car_t2 --pretrained_model /OpenPCDet/checkpoints/seg_plus_det_ep49_t2.pth.tar --test_start_epoch 20
sbatch --time=8:00:00 --array=1-1%1 --job-name=segonlydetcar-30ep-scene20 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_20.yaml --tcp_port 17816 --extra_tag segcontrast_only_det_car --pretrained_model /OpenPCDet/checkpoints/seg_only_det_ep49.pth.tar --test_start_epoch 20
sbatch --time=8:00:00 --array=1-1%1 --job-name=segonlydetcar-30ep-scene20_t2 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_30ep_scene_sampled_20.yaml --tcp_port 17817 --extra_tag segcontrast_only_det_car_t2 --pretrained_model /OpenPCDet/checkpoints/seg_only_det_ep49_t2.pth.tar --test_start_epoch 20

# nusc 1%, 30 ep
# sbatch --time=5:00:00 --array=1-1%1 --job-name=30ep-nus-scratch-1perc tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_30ep_1sweeps_sampled_100.yaml --tcp_port 16910 --extra_tag scratch_car --test_start_epoch 20 --test_only
# sbatch --time=5:00:00 --array=1-1%1 --job-name=t2_30ep-nus-scratch-1perc tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_30ep_1sweeps_sampled_100.yaml --tcp_port 16911 --extra_tag scratch_car_t2 --test_start_epoch 20 --test_only
# sbatch --time=8:00:00 --array=1-1%1 --job-name=30ep-nus-seg-1perc tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_30ep_1sweeps_sampled_100.yaml --tcp_port 16912 --extra_tag segcontrast_car --pretrained_model /OpenPCDet/checkpoints/seg_ep49.pth.tar --test_start_epoch 18
# sbatch --time=8:00:00 --array=1-1%1 --job-name=t2_30ep-nus-seg-1perc tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_30ep_1sweeps_sampled_100.yaml --tcp_port 16913 --extra_tag segcontrast_car_t2 --pretrained_model /OpenPCDet/checkpoints/seg_ep49.pth.tar --test_start_epoch 18
# sbatch --time=8:00:00 --array=1-1%1 --job-name=30ep-nus-segdet-1perc tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_30ep_1sweeps_sampled_100.yaml --tcp_port 16914 --extra_tag segcontrast_plus_dethead_car --pretrained_model /OpenPCDet/checkpoints/seg_plus_det_nusc_ep49.pth.tar --test_start_epoch 18
# sbatch --time=8:00:00 --array=1-1%1 --job-name=t2_30ep-nus-segdet-1perc tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_30ep_1sweeps_sampled_100.yaml --tcp_port 16915 --extra_tag segcontrast_plus_dethead_car_t2 --pretrained_model /OpenPCDet/checkpoints/seg_plus_det_nusc_ep49.pth.tar --test_start_epoch 18

# nusc 5%, 30 ep
sbatch --time=5:00:00 --array=1-1%1 --job-name=30ep-nus-scratch-5perc tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_30ep_1sweeps_sampled_20.yaml --tcp_port 16811 --extra_tag scratch_car --test_start_epoch 20
sbatch --time=5:00:00 --array=1-1%1 --job-name=t2_30ep-nus-scratch-5perc tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_30ep_1sweeps_sampled_20.yaml --tcp_port 16812 --extra_tag scratch_car_t2 --test_start_epoch 20
# sbatch --time=8:00:00 --array=1-3%1 --job-name=30ep-nus-seg-5perc tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_30ep_1sweeps_sampled_20.yaml --tcp_port 16813 --extra_tag segcontrast_car --pretrained_model /OpenPCDet/checkpoints/seg_ep49.pth.tar --test_start_epoch 18
# sbatch --time=8:00:00 --array=1-3%1 --job-name=t2_30ep-nus-seg-5perc tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_30ep_1sweeps_sampled_20.yaml --tcp_port 16814 --extra_tag segcontrast_car_t2 --pretrained_model /OpenPCDet/checkpoints/seg_ep49.pth.tar --test_start_epoch 18
# sbatch --time=8:00:00 --array=1-3%1 --job-name=30ep-nus-segdet-5perc tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_30ep_1sweeps_sampled_20.yaml --tcp_port 16815 --extra_tag segcontrast_plus_dethead_car --pretrained_model /OpenPCDet/checkpoints/seg_plus_det_nusc_ep49.pth.tar --test_start_epoch 18
# sbatch --time=8:00:00 --array=1-3%1 --job-name=t2_30ep-nus-segdet-5perc tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_30ep_1sweeps_sampled_20.yaml --tcp_port 16816 --extra_tag segcontrast_plus_dethead_car_t2 --pretrained_model /OpenPCDet/checkpoints/seg_plus_det_nusc_ep49.pth.tar --test_start_epoch 18

##left
# sbatch --time=8:00:00 --array=1-1%1 --job-name=30ep-nus-seg-5perc tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_30ep_1sweeps_sampled_20.yaml --tcp_port 16813 --extra_tag segcontrast_car_t3 --pretrained_model /OpenPCDet/checkpoints/seg_ep49.pth.tar --test_start_epoch 20
# sbatch --time=8:00:00 --array=1-1%1 --job-name=t2_30ep-nus-seg-5perc tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_30ep_1sweeps_sampled_20.yaml --tcp_port 16814 --extra_tag segcontrast_car_t2 --pretrained_model /OpenPCDet/checkpoints/seg_ep49_t2.pth.tar --test_start_epoch 20
# sbatch --time=8:00:00 --array=1-1%1 --job-name=30ep-nus-segdet-5perc tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_30ep_1sweeps_sampled_20.yaml --tcp_port 16815 --extra_tag segcontrast_plus_dethead_car --pretrained_model /OpenPCDet/checkpoints/seg_plus_det_ep49.pth.tar --test_start_epoch 20
# sbatch --time=5:00:00 --array=1-1%1 --job-name=t2_30ep-nus-segdet-5perc tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_30ep_1sweeps_sampled_20.yaml --tcp_port 16816 --extra_tag segcontrast_plus_dethead_car_t3 --pretrained_model /OpenPCDet/checkpoints/seg_plus_det_ep49_t2.pth.tar --test_start_epoch 20

# sbatch --time=8:00:00 --array=1-1%1 --job-name=30ep-nus-sconlylidar-5perc tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_30ep_1sweeps_sampled_20.yaml --tcp_port 16817 --extra_tag segcontrast_only_lidar_car --pretrained_model /OpenPCDet/checkpoints/seg_only_lidar_ep49.pth.tar --test_start_epoch 20
sbatch --time=4:00:00 --array=1-1%1 --job-name=t4_30ep-nus-sconlylidar-5perc tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_30ep_1sweeps_sampled_20.yaml --tcp_port 16818 --extra_tag segcontrast_only_lidar_car_t4 --pretrained_model /OpenPCDet/checkpoints/seg_only_lidar_ep49_t2.pth.tar --test_start_epoch 20
sbatch --time=4:00:00 --array=1-1%1 --job-name=30ep-nus-sconlydet-5perc tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_30ep_1sweeps_sampled_20.yaml --tcp_port 16819 --extra_tag segcontrast_only_det --pretrained_model /OpenPCDet/checkpoints/seg_only_det_ep49_t2.pth.tar --test_start_epoch 20
sbatch --time=4:00:00 --array=1-1%1 --job-name=t2_30ep-nus-sconlydet-5perc tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/nuscenes_models/pointrcnn_minkunet_30ep_1sweeps_sampled_20.yaml --tcp_port 16820 --extra_tag segcontrast_only_det_t2 --pretrained_model /OpenPCDet/checkpoints/seg_only_det_ep49_t2.pth.tar --test_start_epoch 20

## waymo 1 %, 80 ep
sbatch --time=8:00:00 --array=1-2%1 --job-name=car-scratch-80ep-scene100 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_80ep_scene_sampled_100.yaml --tcp_port 18910 --extra_tag scratch_car --test_start_epoch 70
sbatch --time=8:00:00 --array=1-2%1 --job-name=car-scratch-80ep-scene100_t2 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_80ep_scene_sampled_100.yaml --tcp_port 18911 --extra_tag scratch_car_t2 --test_start_epoch 70
sbatch --time=8:00:00 --array=1-2%1 --job-name=segcar-78ep-scene100 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_78ep_scene_sampled_100.yaml --tcp_port 18912 --extra_tag segcontrast_car --pretrained_model /OpenPCDet/checkpoints/seg_ep49.pth.tar --test_start_epoch 68
sbatch --time=8:00:00 --array=1-2%1 --job-name=segcar-78ep-scene100_t2 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_78ep_scene_sampled_100.yaml --tcp_port 18913 --extra_tag segcontrast_car_t2 --pretrained_model /OpenPCDet/checkpoints/seg_ep49.pth.tar --test_start_epoch 68
sbatch --time=8:00:00 --array=1-2%1 --job-name=segdetcar-78ep-scene100 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_78ep_scene_sampled_100.yaml --tcp_port 18914 --extra_tag segcontrast_plus_dethead_0p8w_car --pretrained_model /OpenPCDet/checkpoints/seg_plus_det0p8_ep49.pth.tar --test_start_epoch 68
sbatch --time=8:00:00 --array=1-2%1 --job-name=segdetcar-78ep-scene100_t2 tools/scripts/submit_ddp_$CLUSTER_NAME.sh --cfg_file tools/cfgs/waymo_models/pointrcnn_minkunet_78ep_scene_sampled_100.yaml --tcp_port 18915 --extra_tag segcontrast_plus_dethead_0p8w_car_t2 --pretrained_model /OpenPCDet/checkpoints/seg_plus_det0p8_ep49.pth.tar --test_start_epoch 68


# To see hanging threads
#ps -ef | grep -i '[p]ython'
pids=$(ps aux | grep 'nisarbar' | grep 'python' | awk '{print $2}')
echo "$pids" | xargs kill