# # Train on FOV3000

########################################## Finetune SSL models ########################################## 

########### Finetune with one LR for both head and BB #############

########### Pretrained on dense + kitti ###########
########### dc+weather aug ###########
#---------------------------------------- Tuning params REMOVE ------------------------------------------------------------
# adamOnecycle 
# Bestest
# sbatch --time=24:00:00 --array=1-2%1 --job-name=finetune-all_splits_5_adamO_dc_1in2_cube_up_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_5_adamO.yaml --extra_tag dc_1in2_cube_up_red_dense_kitti_ep330 --tcp_port 18855 --ckpt_save_interval 20 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_1in2_cube_up_b14_lr0p15_red_dense_kitti_ep330.pth.tar
# Not known 
# sbatch --time=24:00:00 --array=1-2%1 --job-name=finetune-all_splits_5_adamO_wd0p001_dc_1in2_cube_up_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_5_adamO_wd0p001.yaml --extra_tag dc_1in2_cube_up_red_dense_kitti_ep330 --tcp_port 18865 --ckpt_save_interval 20 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_1in2_cube_up_b14_lr0p15_red_dense_kitti_ep330.pth.tar
# sbatch --time=24:00:00 --array=1-2%1 --job-name=finetune-all_splits_5_adamO_0p02_dc_1in2_cube_up_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_5_adamO_0p02.yaml --extra_tag dc_1in2_cube_up_red_dense_kitti_ep330 --tcp_port 18875 --ckpt_save_interval 20 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_1in2_cube_up_b14_lr0p15_red_dense_kitti_ep330.pth.tar
# sbatch --time=10:00:00 --array=1-1%1 --job-name=finetune-all_splits_5_adamO_0p015_dc_1in2_cube_up_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_5_adamO_0p015.yaml --extra_tag dc_1in2_cube_up_red_dense_kitti_ep330 --tcp_port 18875 --ckpt_save_interval 20 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_1in2_cube_up_b14_lr0p15_red_dense_kitti_ep330.pth.tar

# # adamw_cosine 
# sbatch --time=24:00:00 --array=1-2%1 --job-name=finetune-all_splits_5_adamC_dc_1in2_cube_up_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_5_adamw_cosine_0p001.yaml --extra_tag dc_1in2_cube_up_red_dense_kitti_ep330 --tcp_port 18655 --ckpt_save_interval 20 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_1in2_cube_up_b14_lr0p15_red_dense_kitti_ep330.pth.tar
# sbatch --time=24:00:00 --array=1-2%1 --job-name=finetune-all_splits_5_adamC_wd0p001_dc_1in2_cube_up_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_5_adamw_cosine_0p001_wd0p001.yaml --extra_tag dc_1in2_cube_up_red_dense_kitti_ep330 --tcp_port 18665 --ckpt_save_interval 20 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_1in2_cube_up_b14_lr0p15_red_dense_kitti_ep330.pth.tar
# Best
# sbatch --time=24:00:00 --array=1-2%1 --job-name=finetune-all_splits_5_adamC_0p002_dc_1in2_cube_up_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_5_adamw_cosine_0p002.yaml --extra_tag dc_1in2_cube_up_red_dense_kitti_ep330 --tcp_port 18675 --ckpt_save_interval 20 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_1in2_cube_up_b14_lr0p15_red_dense_kitti_ep330.pth.tar
#---------------------------------------- Tuning params REMOVE ------------------------------------------------------------

# TODO (High priority)!!!!!!!!11
# sbatch --time=05:00:00 --gres=gpu:v100:4 --array=1-6%1  --job-name=finetune-all_splits_5_adamO_dc_1in2_cube_up_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_5.yaml --extra_tag dc_1in2_cube_up_red_dense_kitti_ep330 --tcp_port 18855 --ckpt_save_interval 20 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_1in2_cube_up_b14_lr0p15_red_dense_kitti_ep330.pth.tar
# TODO (High priority)
# sbatch --time=05:00:00 --gres=gpu:v100:4 --array=1-3%1 --job-name=finetune-all_splits_10_dc_1in2_cube_up_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_10.yaml --extra_tag dc_1in2_cube_up_red_dense_kitti_ep330 --tcp_port 18855 --ckpt_save_interval 10 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_1in2_cube_up_b14_lr0p15_red_dense_kitti_ep330.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_splits_20_dc_1in2_cube_up_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_20.yaml --extra_tag dc_1in2_cube_up_red_dense_kitti_ep330 --tcp_port 18855 --ckpt_save_interval 5 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_1in2_cube_up_b14_lr0p15_red_dense_kitti_ep330.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_splits_30_dc_1in2_cube_up_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_30.yaml --extra_tag dc_1in2_cube_up_red_dense_kitti_ep330 --tcp_port 18855 --ckpt_save_interval 3 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_1in2_cube_up_b14_lr0p15_red_dense_kitti_ep330.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_splits_40_dc_1in2_cube_up_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_40.yaml --extra_tag dc_1in2_cube_up_red_dense_kitti_ep330 --tcp_port 18855 --ckpt_save_interval 2 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_1in2_cube_up_b14_lr0p15_red_dense_kitti_ep330.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_splits_50_dc_1in2_cube_up_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_splits_60_50.yaml --extra_tag dc_1in2_cube_up_red_dense_kitti_ep330 --tcp_port 18855 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_1in2_cube_up_b14_lr0p15_red_dense_kitti_ep330.pth.tar

# TODO (High priority)!!!!!!!!11
#sbatch --time=05:00:00 --gres=gpu:v100:4 --array=1-3%1 --job-name=finetune-all_60_0_dc_1in2_cube_up_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_0.yaml --extra_tag dc_1in2_cube_up_red_dense_kitti_ep330 --tcp_port 18835 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_1in2_cube_up_b14_lr0p15_red_dense_kitti_ep330.pth.tar
sbatch --time=05:00:00 --gres=gpu:v100:4 --array=1-3%1 --job-name=finetune-all_60_1_dc_1in2_cube_up_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_1.yaml --extra_tag dc_1in2_cube_up_red_dense_kitti_ep330 --tcp_port 18825 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_1in2_cube_up_b14_lr0p15_red_dense_kitti_ep330.pth.tar
sbatch --time=05:00:00 --gres=gpu:v100:4 --array=1-3%1 --job-name=finetune-all_60_1_lr_0p02_60epochs_dc_1in2_cube_up_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_1_lr0p02_60epochs.yaml --extra_tag dc_1in2_cube_up_red_dense_kitti_ep330 --tcp_port 18825 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_1in2_cube_up_b14_lr0p15_red_dense_kitti_ep330.pth.tar
sbatch --time=05:00:00 --gres=gpu:v100:4 --array=1-3%1 --job-name=finetune-all_60_1_lr_0p015_dc_1in2_cube_up_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_1_lr0p015.yaml --extra_tag dc_1in2_cube_up_red_dense_kitti_ep330 --tcp_port 18825 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_1in2_cube_up_b14_lr0p15_red_dense_kitti_ep330.pth.tar
sbatch --time=05:00:00 --gres=gpu:v100:4 --array=1-3%1 --job-name=finetune-all_60_1_wd_0p001_dc_1in2_cube_up_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_1_wd_0p001.yaml --extra_tag dc_1in2_cube_up_red_dense_kitti_ep330 --tcp_port 18825 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_1in2_cube_up_b14_lr0p15_red_dense_kitti_ep330.pth.tar

# TODO (High priority)!!!!!!!!11
#sbatch --time=05:00:00 --gres=gpu:v100:4 --array=1-3%1 --job-name=finetune-all_60_5_dc_1in2_cube_up_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_5.yaml --extra_tag dc_1in2_cube_up_red_dense_kitti_ep330 --tcp_port 18855 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_1in2_cube_up_b14_lr0p15_red_dense_kitti_ep330.pth.tar
# TODO (High priority)
#sbatch --time=05:00:00 --array=1-3%1 --job-name=finetune-all_60_10_dc_1in2_cube_up_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_10.yaml --extra_tag dc_1in2_cube_up_red_dense_kitti_ep330 --tcp_port 18855 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_1in2_cube_up_b14_lr0p15_red_dense_kitti_ep330.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_60_20_dc_1in2_cube_up_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_20.yaml --extra_tag dc_1in2_cube_up_red_dense_kitti_ep330 --tcp_port 18855 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_1in2_cube_up_b14_lr0p15_red_dense_kitti_ep330.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_60_30_dc_1in2_cube_up_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_30.yaml --extra_tag dc_1in2_cube_up_red_dense_kitti_ep330 --tcp_port 18855 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_1in2_cube_up_b14_lr0p15_red_dense_kitti_ep330.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_60_40_dc_1in2_cube_up_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_40.yaml --extra_tag dc_1in2_cube_up_red_dense_kitti_ep330 --tcp_port 18855 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_1in2_cube_up_b14_lr0p15_red_dense_kitti_ep330.pth.tar
# sbatch --time=15:00:00 --array=1-1%1 --job-name=finetune-all_60_50_dc_1in2_cube_up_red_dense_kitti_ep330 tools/scripts/compute_canada_train_eval_dense.sh --cfg_file tools/cfgs/dense_models/pointrcnn_finetune_train_all_60_50.yaml --extra_tag dc_1in2_cube_up_red_dense_kitti_ep330 --tcp_port 18855 --ckpt_save_interval 1 --fix_random_seed --pretrained_model /OpenPCDet/checkpoints/pointnet_train_all_FOV3000_60/dc_1in2_cube_up_b14_lr0p15_red_dense_kitti_ep330.pth.tar